Repository dynatrace-oss/barista, pull requests merged in 2019-12, with the labels that each got.

#247 Fix barista fonts
  apps/demos/src/side-nav.component.scss
  apps/dev/src/devapp.component.scss
  components/chart/src/chart-options.ts
  components/style/README.md
Labels: pr: lgtm, pr: merge-ready

#253 barista(font): Adjust fonts output path and styles imports.
  angular.json
Labels: pr: lgtm, pr: merge-ready

#231 barista: Added icon-page builder.
  apps/barista/src/components/icon-color-wheel/icon-color-wheel.html
  apps/barista/src/components/icon-color-wheel/icon-color-wheel.ts
  apps/barista/src/layout/page-header/page-header.scss
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/src/builder/components.ts
  tools/barista/src/builder/homepage.ts
  tools/barista/src/builder/icons.ts
  tools/barista/src/builder/strapi.ts
  tools/barista/src/main.ts
  tools/barista/src/types.ts
  tools/barista/src/utils/convert-json-changelog-to-markdown.ts
  tools/barista/src/utils/fetch-strapi-content.ts
  tools/barista/src/utils/isPublicBuild.ts
Labels: pr: lgtm, pr: merge-ready

#180 barista(overview-pages): Created overview page json output.
  apps/barista/src/layout/tile/tile.html
  apps/barista/src/layout/tile/tile.ts
  apps/barista/src/pages/overview-page/overview-page.ts
  apps/barista/src/shared/page-contents.ts
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/src/builder/components.ts
  tools/barista/src/builder/overview.ts
  tools/barista/src/main.ts
Labels: pr: lgtm, pr: merge-ready

#232 barista(component-pages): Generate json output for all component pages.
  tools/barista/src/builder/components.ts
Labels: pr: lgtm, pr: merge-ready

#186 feat/Barista Breadcrumbs
  apps/barista/src/app.html
  apps/barista/src/app.module.ts
  apps/barista/src/app.ts
Labels: design-system, pr: lgtm, pr: merge-ready

#266 barista: Update nav groups and section headlines on overview pages.
  tools/barista/src/builder/components.ts
  tools/barista/src/builder/overview.ts
Labels: pr: lgtm, pr: merge-ready

#265 barista: Add favicon.
  apps/barista/src/index.html
Labels: pr: lgtm, pr: merge-ready

#268 barista(page-builder): Filter directories before generating overview …
  tools/barista/src/builder/overview.ts
  tools/barista/src/main.ts
Labels: pr: lgtm, pr: merge-ready

#269 barista: Show TOC by default.
  apps/barista/src/pages/single-page/single-page.html
  apps/barista/src/pages/single-page/single-page.ts
  tools/barista/src/builder/icons.ts
Labels: pr: lgtm, pr: merge-ready

#261 barista(icon-color-wheel): Set fill color before download.
  apps/barista/src/components/icon-color-wheel/icon-color-wheel.ts
Labels: pr: lgtm, pr: merge-ready

#271 barista: Rename nav-group property.
  components/core/src/indicator/barista.json
  components/core/src/viewport/barista.json
  components/schematics/barista.json
  components/style/barista.json
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/src/builder/components.ts
  tools/barista/src/builder/icons.ts
  tools/barista/src/builder/overview.ts
Labels: pr: lgtm, pr: merge-ready

#259 chore: Fix user syntax error in codeowners and remove unused paths
  .github/CODEOWNERS
Labels: pr: lgtm

#257 fix(event-chart): Fixes an issue where colors did not match up
  components/event-chart/src/event-chart-legend.scss
Labels: pr: lgtm, pr: merge-ready

#272 barista: Remove sidenav temporarily.
  apps/barista/src/pages/single-page/single-page.html
Labels: pr: lgtm, pr: merge-ready

#273 docs: Remove handlebars syntax from readme files.
  components/breadcrumbs/README.md
  components/chart/README.md
  components/filter-field/README.md
  components/micro-chart/README.md
  components/table/README.md
  components/tabs/README.md
  components/toggle-button-group/README.md
Labels: pr: lgtm, pr: merge-ready

#267 fix(barista-breadcrumbs): Better breadcrumb-item text
  apps/barista/src/app.html
  apps/barista/src/app.ts
Labels: bug, pr: lgtm, pr: merge-ready

#274 barista: Remove sidenav on icon-overview temporarily.
  apps/barista/src/pages/icon-overview-page/icon-overview-page.html
Labels: pr: lgtm, pr: merge-ready

#275 barista: Added markdown-it dl plugin and dl styles.
  apps/barista/src/styles/global/_base.scss
  package-lock.json
  package.json
  tools/barista/Dockerfile
  tools/barista/src/transform.ts
Labels: pr: lgtm, pr: merge-ready

#292 barista: Fix links on most-ordered-tiles on homepage.
  tools/barista/src/builder/homepage.ts
Labels: pr: lgtm, pr: merge-ready

#281 barista: Added headline id transformer.
  tools/barista/src/builder/components.ts
  tools/barista/src/builder/strapi.ts
  tools/barista/src/transform.ts
Labels: pr: lgtm, pr: merge-ready

#293 barista: Fixes icon config provider to be a static string.
  apps/barista/src/app.module.ts
Labels: design-system, pr: lgtm, pr: merge-ready

#299 barista: Remove internal links from public content.
  apps/barista/src/styles/items/_items-dir.scss
  apps/barista/src/styles/items/_link.scss
  tools/barista/README.md
  tools/barista/src/builder/components.ts
  tools/barista/src/builder/strapi.ts
  tools/barista/src/transform.ts
Labels: design-system, pr: lgtm, pr: merge-ready

#255 ci: Run affected targets correctly on master and on PR as on 4.x and 1.15x
  .circleci/config.yml
Labels: P1

#298 fix(universal): Fixes failing universal tests suite due to old icon i…
  angular.json
  apps/universal/src/app/kitchen-sink/kitchen-sink.ts
Labels: P1, bug

#280 Barista/improve toc
  apps/barista/src/layout/toc/toc.html
  apps/barista/src/layout/toc/toc.scss
  apps/barista/src/layout/toc/toc.ts
  apps/barista/src/pages/page-content.ts
  apps/barista/src/pages/page-outlet.ts
  apps/barista/src/pages/single-page/single-page.html
  apps/barista/src/shared/location.service.ts
  apps/barista/src/shared/page.service.ts
  apps/barista/src/shared/toc.service.ts
Labels: design-system, pr: lgtm, pr: merge-ready

#290 chore(dev-app): Set dtTheme on main container to make the theme selec…
  apps/dev/src/devapp.component.html
Labels: pr: lgtm, pr: merge-ready

#306 build(components): Fixes issue where missing angular compiler options…
  components/tsconfig.json
Labels: pr: lgtm, pr: merge-ready

#256 fix(context-dialog): Fixes positioning issues by removing the closing…
  CHANGELOG.md
  apps/components-e2e/src/components/context-dialog/context-dialog.e2e.ts
  apps/components-e2e/src/components/context-dialog/context-dialog.po.ts
  components/context-dialog/README.md
  components/context-dialog/src/context-dialog.html
  components/context-dialog/src/context-dialog.scss
  components/context-dialog/src/context-dialog.spec.ts
  components/context-dialog/src/context-dialog.ts
  libs/examples/src/context-dialog/context-dialog-custom-icon-example/context-dialog-custom-icon-example.html
  libs/examples/src/context-dialog/context-dialog-header-example/context-dialog-header-example.html
Labels: bug, pr: lgtm, pr: merge-ready

#311 ci: Use the unix epoch to have always a unique cache key
  .circleci/config.yml
Labels: P1

#291 barista: Add/fix theming of categories.
  apps/barista/src/app.html
  apps/barista/src/app.module.ts
  apps/barista/src/app.scss
  apps/barista/src/app.ts
  apps/barista/src/layout/footer/footer.html
  apps/barista/src/layout/smalltile/smalltile.html
  apps/barista/src/layout/smalltile/smalltile.scss
  apps/barista/src/layout/smalltile/smalltile.ts
  apps/barista/src/layout/tile/tile.scss
  apps/barista/src/pages/index-page/index-page.scss
  apps/barista/src/styles/global/_base.scss
  apps/barista/src/styles/global/_global-dir.scss
  apps/barista/src/styles/global/_theme.scss
  apps/barista/src/styles/items/_button.scss
  apps/barista/src/styles/items/_list.scss
Labels: pr: lgtm, pr: merge-ready

#264 barista(sidenav): generate sidenav json output
  apps/barista/src/layout/sidenav/sidenav.html
  apps/barista/src/layout/tile/tile.ts
  apps/barista/src/pages/icon-overview-page/icon-overview-page.html
  apps/barista/src/pages/overview-page/overview-page.ts
  apps/barista/src/pages/single-page/single-page.html
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/src/generators/category-navigation.ts
  tools/barista/src/main.ts
Labels: pr: lgtm, pr: merge-ready

#319 barista: Hide sidenav on small screens and fix line-height.
  apps/barista/src/layout/sidenav/sidenav.scss
Labels: pr: lgtm, pr: merge-ready

#314 fix(filter-field): Fixes an issue where the range was cut off.
  components/filter-field/src/filter-field-range/filter-field-range-trigger.ts
Labels: pr: lgtm, pr: merge-ready

#321 barista: Call overview page builder in build pages main function.
  tools/barista/src/main.ts
Labels: pr: lgtm, pr: merge-ready

#324 barista: Fixes broken Barista build script.
  package.json
  tools/barista/src/generators/category-navigation.ts
  tools/barista/src/main.ts
Labels: design-system

#320 Barista/test headline id transformer
  tools/barista/src/transform.spec.ts
  tools/barista/src/transform.ts
Labels: pr: lgtm, pr: merge-ready

#328 ci: Switch to restricted context
  .circleci/config.yml
Labels: P1

#313 barista: Improve iconfilter.
  apps/barista/src/components/lazy-icon/lazy-icon.html
  apps/barista/src/components/lazy-icon/lazy-icon.scss
  apps/barista/src/pages/icon-overview-page/icon-overview-page.html
  apps/barista/src/pages/icon-overview-page/icon-overview-page.scss
  apps/barista/src/pages/icon-overview-page/icon-overview-page.ts
Labels: pr: lgtm, pr: merge-ready

#337 fix(event-chart): Fixes an issue with universal rendering.
  apps/universal/src/app/kitchen-sink/kitchen-sink.html
  components/event-chart/src/event-chart.ts
Labels: bug, pr: lgtm, pr: merge-ready

#334 chore(commitlint): Removed references-empty rule so issue references are possible in commit message bodies.
  commitlint.config.js
Labels: pr: lgtm, pr: merge-ready

#312 barista(nav): Generate nav json.
  apps/barista/src/app.ts
  apps/barista/src/environments/environment.prod.ts
  apps/barista/src/environments/environment.ts
  apps/barista/src/layout/nav/nav.html
  apps/barista/src/layout/nav/nav.scss
  apps/barista/src/layout/nav/nav.ts
  apps/barista/src/shared/page.service.ts
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/src/generators/category-navigation.ts
Labels: pr: lgtm, pr: merge-ready

#316 barista(recently-ordered): Remove Icon pages from recently ordered ti…
  apps/barista/src/pages/icon-overview-page/icon-overview-page.ts
  apps/barista/src/pages/single-page/single-page.ts
  apps/barista/src/shared/recently-ordered.service.ts
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/src/builder/components.ts
  tools/barista/src/builder/icons.ts
  tools/barista/src/builder/strapi.ts
Labels: pr: lgtm, pr: merge-ready

#338 barista: Update dockerfile to be able to build examples and tools.
  tools/barista/Dockerfile
Labels: pr: lgtm, pr: merge-ready

#309 barista: Handle public and draft flag when fetching content from Strapi.
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/src/builder/homepage.ts
  tools/barista/src/builder/strapi.ts
  tools/barista/src/utils/fetch-strapi-content.ts
Labels: pr: lgtm, pr: merge-ready

#297 Barista/list styling
  apps/barista/src/styles/global/_base.scss
Labels: pr: lgtm, pr: merge-ready

#288 barista(overview-pages): Order tiles on overview pages by title.
  tools/barista/src/generators/category-navigation.ts
Labels: pr: lgtm, pr: merge-ready

#310 barista: Refactored util function to fit coding standards and added d…
  apps/barista/src/pages/single-page/single-page.ts
  apps/barista/src/utils/apply-table-definition-headings.ts
  tools/barista/src/builder/homepage.ts
  tools/barista/src/builder/icons.ts
  tools/barista/src/builder/strapi.ts
  tools/barista/src/main.ts
  tools/barista/src/utils/is-public-build.ts
Labels: pr: lgtm, pr: merge-ready

#249 chore(tools): Added an action to target label pull requests.
  .github/workflows/pull-request-labeler.yml
  tools/pull-request-labeler/.dockerignore
  tools/pull-request-labeler/.gitignore
  tools/pull-request-labeler/Dockerfile
  tools/pull-request-labeler/entrypoint.sh
  tools/pull-request-labeler/package-lock.json
  tools/pull-request-labeler/package.json
  tools/pull-request-labeler/src/interfaces/commit-message.ts
  tools/pull-request-labeler/src/main.ts
  tools/pull-request-labeler/src/utils/add-rebase-label.ts
  tools/pull-request-labeler/src/utils/get-commit-messages-in-pull-request.ts
  tools/pull-request-labeler/src/utils/get-pull-request-details.ts
  tools/pull-request-labeler/src/utils/has-lgtm-label.ts
  tools/pull-request-labeler/src/utils/is-master-target.ts
  tools/pull-request-labeler/src/utils/process-commit-messages.ts
  tools/pull-request-labeler/src/utils/split-message-into-components.ts
  tools/pull-request-labeler/src/utils/update-target-labels.ts
  tools/pull-request-labeler/tsconfig.json
  tools/pull-request-labeler/tslint.json
Labels: pr: lgtm, pr: merge-ready

#333 fix(filter-field): Fixes and issue where filters are not immediately removed when clicking the clear all button
  apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
  apps/components-e2e/src/components/filter-field/filter-field.html
  apps/components-e2e/src/components/filter-field/filter-field.po.ts
  apps/components-e2e/src/components/filter-field/filter-field.ts
  components/filter-field/src/filter-field.html
  components/filter-field/src/filter-field.ts
Labels: bug, pr: lgtm, pr: merge-ready, target: minor

#344 Fix build on Windows by adding explicit type annotations
  components/core/src/animations/error-animations.ts
  components/expandable-panel/src/expandable-panel.ts
  components/expandable-text/src/expandable-text.ts
  components/secondary-nav/src/section/secondary-nav-section.ts
  components/table/src/expandable/expandable-row.ts
Labels: pr: lgtm, pr: merge-ready

#350 ci(pull-request-labeler): Fixes incorrect applied labels for non fix/feat commits.
  tools/pull-request-labeler/src/utils/process-commit-messages.ts
Labels: pr: lgtm, pr: merge-ready

#351 barista(nav): Make the nav responsive.
  apps/barista/src/layout/nav/nav.html
  apps/barista/src/layout/nav/nav.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#348 barista: Added axios to npm dependencies in Dockerfile.
  tools/barista/Dockerfile
Labels: pr: lgtm, pr: merge-ready, target: minor

#349 feat(filter-field): Added new methods to abstract data-source class for more flexibility.
  components/filter-field/src/filter-field-data-source.ts
  components/filter-field/src/filter-field-default-data-source.ts
  components/filter-field/src/filter-field-util.ts
  components/filter-field/src/index.ts
Labels: pr: lgtm, pr: merge-ready, target: major

#354 barista: Align brand logo and breadcrumbs.
  apps/barista/src/layout/nav/nav.scss
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#352 barista: Transform documentation file names to lower case.
  tools/barista/src/builder/components.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#358 barista(index-page): Remove search from index page.
  apps/barista/src/pages/index-page/index-page.html
Labels: pr: lgtm, pr: merge-ready

#359 barista(overview-page): Fix button margin in safari.
  apps/barista/src/pages/overview-page/overview-page.scss
Labels: pr: lgtm, pr: merge-ready

#345 chore: Updated contributing to new commit guideline
  CONTRIBUTING.md
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#335 feat(chart-range): Add possibility to close chart-range programmatically.
  components/chart/README.md
  components/chart/src/range/range.spec.ts
  components/chart/src/range/range.ts
  package-lock.json
Labels: feature, pr: lgtm, pr: merge-ready

#318 feat(formatters): Added maxPrecision parameter to number and percent …
  apps/dev/src/formatters/formatters-demo.component.html
  components/formatters/src/number-formatter.spec.ts
  components/formatters/src/number-formatter.ts
  components/formatters/src/percent/percent-formatter.ts
  components/formatters/src/percent/percent.ts
Labels: pr: lgtm, pr: merge-ready

#356 fix(overlay): Fixes an issue with overlay placement in firefox.
  components/overlay/src/overlay-trigger.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#346 barista: Make src and dest paths for barista- and examples-tools conf…
  angular.json
  tools/barista/README.md
  tools/barista/src/builder/components.ts
  tools/barista/src/builder/homepage.ts
  tools/barista/src/builder/icons.ts
  tools/barista/src/builder/strapi.ts
  tools/barista/src/generators/category-navigation.ts
  tools/barista/src/main.ts
  tools/environments/barista-environment.prod.ts
  tools/environments/barista-environment.ts
  tools/examples/README.md
  tools/examples/src/build-config.ts
  tools/examples/src/generate-examples-lib-metadata.ts
  tools/examples/src/generate-examples-lib-module.ts
  tools/examples/src/main.ts
  tools/examples/src/util.ts
  tools/util/is-public-build.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#341 barista(scroll-top-button): Added scroll to top button.
  apps/barista/src/app.html
  apps/barista/src/app.module.ts
  apps/barista/src/layout/scroll-to-top/scroll-to-top.html
  apps/barista/src/layout/scroll-to-top/scroll-to-top.scss
  apps/barista/src/layout/scroll-to-top/scroll-to-top.ts
  apps/barista/src/pages/single-page/single-page.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch
