Repository dynatrace-oss/barista, pull requests merged in 2019-11, with the labels that each got.

#191 docs: Improve bug issue template.
  .github/ISSUE_TEMPLATE/bug.md
Labels: documentation, pr: lgtm, pr: merge-ready

#184 chore(barsita-fonts): Fixed imports and variables to use barista-font.
  angular.json
  apps/dev/src/main.scss
  components/core/src/style/_variables.scss
  components/package.json
  components/style/_typography.scss
  components/style/index.scss
  package-lock.json
  package.json
Labels: pr: lgtm, pr: merge-ready

#193 Improve the feature issue template.
  .github/ISSUE_TEMPLATE/feature.md
Labels: documentation, pr: lgtm, pr: merge-ready

#187 Create own stylelint builder
  angular.json
  package-lock.json
  package.json
  tools/builders/builders.json
  tools/builders/index.ts
  tools/builders/package.json
  tools/builders/stylelint/index.ts
  tools/builders/stylelint/junit-formatter/existing-result.interface.ts
  tools/builders/stylelint/junit-formatter/index.ts
  tools/builders/stylelint/junit-formatter/junit-formatter.ts
  tools/builders/stylelint/junit-formatter/parse-exisiting-suite.ts
  tools/builders/stylelint/junit-formatter/parse-suite.ts
  tools/builders/stylelint/junit-formatter/parsed-suite.interface.ts
  tools/builders/stylelint/read-files.ts
  tools/builders/stylelint/schema.json
  tools/builders/stylelint/stylelint-builder-options.ts
  tools/builders/tsconfig.json
Labels: P1, pr: lgtm, pr: merge-ready

#208 chore: Add browserstack to the README
  README.md
Labels: documentation

#213 Fixes missing export for using chart-tooltips in micro charts
  components/micro-chart/src/micro-chart-module.ts
Labels: bug, pr: lgtm, pr: merge-ready

#212 Change the organization to the dynatrace-oss.
  CONTRIBUTING.md
  README.md
  RELEASE.md
  components/package.json
  tools/builders/package.json
Labels: documentation, pr: lgtm, pr: merge-ready

#206 barista: Replaced link-to-id helper with URLs
  components/alert/README.md
  components/button-group/README.md
  components/button/README.md
  components/card/README.md
  components/chart/README.md
  components/context-dialog/README.md
  components/copy-to-clipboard/README.md
  components/empty-state/README.md
  components/expandable-section/README.md
  components/filter-field/README.md
  components/form-field/README.md
  components/formatters/README.md
  components/icon/README.md
  components/info-group/README.md
  components/input/README.md
  components/loading-distractor/README.md
  components/menu/README.md
  components/micro-chart/README.md
  components/overlay/README.md
  components/pagination/README.md
  components/progress-bar/README.md
  components/show-more/README.md
  components/table/README.md
Labels: pr: lgtm, pr: merge-ready

#225 ci: Add sonar cloud to circle ci
  .circleci/config.yml
  sonar-project.properties
Labels: pr: lgtm, pr: merge-ready

#228 ci: Add snyk integration
  .circleci/config.yml
Labels: P2

#216 barista(fonts): Added fonts to Barista styles.
  angular.json
  apps/barista/src/main.scss
  apps/barista/src/styles/global/_fonts.scss
Labels: pr: lgtm, pr: merge-ready

#199 Barista/generate strapicms pages
  .dockerignore
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/Dockerfile
  tools/barista/README.md
  tools/barista/src/builder/strapi.ts
  tools/barista/src/main.ts
  tools/barista/src/utils/fetch-strapi-content.ts
Labels: pr: lgtm, pr: merge-ready

#217 barista(toc): Update url when clicking on toc items.
  apps/barista/src/layout/toc/toc.ts
  apps/barista/src/pages/single-page/single-page.ts
Labels: pr: lgtm, pr: merge-ready

#226 chore(barista): Added the possibility to define a data-hosturl for ba…
  apps/barista/src/environments/environment.prod.ts
  apps/barista/src/environments/environment.ts
  apps/barista/src/pages/single-page/single-page.html
  apps/barista/src/shared/page.service.ts
Labels: design-system, pr: lgtm, pr: merge-ready

#211 Removes the circular dependency of the chart heatfield.
  apps/dev/src/chart/chart-demo.component.html
  components/chart/src/chart.spec.ts
  components/chart/src/chart.ts
  components/chart/src/heatfield/chart-heatfield.html
  components/chart/src/heatfield/chart-heatfield.spec.ts
  components/chart/src/heatfield/chart-heatfield.ts
  components/chart/src/tooltip/chart-tooltip.ts
  components/chart/src/utils.ts
Labels: P1, pr: lgtm, pr: merge-ready

#201 barista(page-footer): Change page footer tags to make them non-clicka…
  apps/barista/src/layout/page-footer/page-footer.html
  apps/barista/src/layout/page-footer/page-footer.scss
Labels: design-system, pr: lgtm, pr: merge-ready

#192 barista(styling): render table correctly
  apps/barista/src/pages/single-page/single-page.ts
  apps/barista/src/styles/global/_base.scss
  apps/barista/src/styles/global/_variables.scss
  apps/barista/src/utils/fillTableData.ts
Labels: pr: lgtm, pr: merge-ready

#223 fix(confirmation-dialog): Set activeDialog to null if dialog dismissed.
  components/confirmation-dialog/src/confirmation-dialog.spec.ts
  components/confirmation-dialog/src/confirmation-dialog.ts
Labels: bug, pr: lgtm, pr: merge-ready

#240 ci: Remove sonar context.
  .circleci/config.yml
Labels: pr: lgtm, pr: merge-ready

#218 fix: Added barista-fonts import in dev-app.
  angular.json
Labels: bug, pr: lgtm, pr: merge-ready

#241 fix(form-field): Fixes an issue with the label color in a dark theme.
  apps/dev/src/form-field/form-field-demo.component.html
  components/form-field/src/_form-field-theme.scss
  components/form-field/src/form-field.scss
Labels: bug, pr: lgtm, pr: merge-ready

#245 Add stylint to our CI
  .circleci/config.yml
  angular.json
  apps/barista/src/styles/global/_base.scss
  libs/examples/src/context-dialog/context-dialog-header-example/context-dialog-header-example.scss
  libs/examples/src/menu/menu-default-example/menu-default-example.html
  libs/examples/src/menu/menu-default-example/menu-default-example.scss
  libs/examples/src/menu/menu-within-drawer-example/menu-within-drawer-example.html
  libs/examples/src/menu/menu-within-drawer-example/menu-within-drawer-example.scss
  libs/examples/src/overlay/overlay-complex-content-example/overlay-complex-content-example.html
  libs/examples/src/overlay/overlay-complex-content-example/overlay-complex-content-example.scss
  libs/examples/src/overlay/overlay-tile-example/overlay-tile-example.html
  libs/examples/src/overlay/overlay-tile-example/overlay-tile-example.scss
  libs/examples/src/secondary-nav/secondary-nav-active-example/secondary-nav-active-example.html
  libs/examples/src/secondary-nav/secondary-nav-active-example/secondary-nav-active-example.scss
  libs/examples/src/secondary-nav/secondary-nav-title-example/secondary-nav-title-example.html
  libs/examples/src/secondary-nav/secondary-nav-title-example/secondary-nav-title-example.scss
  libs/examples/src/select/select-with-icons-example/select-with-icons-example.html
  libs/examples/src/select/select-with-icons-example/select-with-icons-example.scss
  libs/examples/src/table/table-empty-state-example/table-empty-state-example.html
  libs/examples/src/table/table-empty-state-example/table-empty-state-example.scss
  libs/examples/src/table/table-expandable-rows-example/table-expandable-rows-example.html
  libs/examples/src/table/table-expandable-rows-example/table-expandable-rows-example.scss
  libs/examples/src/table/table-loading-example/table-loading-example.html
  libs/examples/src/table/table-loading-example/table-loading-example.scss
  libs/examples/src/table/table-observable-example/table-observable-example.html
  libs/examples/src/table/table-observable-example/table-observable-example.scss
  libs/examples/src/table/table-problem-example/table-problem-example.html
  libs/examples/src/table/table-problem-example/table-problem-example.scss
  libs/examples/src/table/table-sorting-example/table-sorting-example.html
  libs/examples/src/table/table-sorting-example/table-sorting-example.scss
  libs/examples/src/toggle-button-group/toggle-button-group-in-use-example/toggle-button-group-in-use-example.html
  libs/examples/src/toggle-button-group/toggle-button-group-in-use-example/toggle-button-group-in-use-example.scss
  libs/examples/src/toggle-button-group/toggle-button-group-show-more-example/toggle-button-group-show-more-example.html
  libs/examples/src/toggle-button-group/toggle-button-group-show-more-example/toggle-button-group-show-more-example.scss
  libs/examples/src/tree-table/tree-table-default-example/tree-table-default-example.html
  libs/examples/src/tree-table/tree-table-default-example/tree-table-default-example.scss
Labels: P1

#239 chore: Remove shinnn.stylelint from recommendations.
  .vscode/extensions.json
Labels: P4, pr: lgtm, pr: merge-ready
