Repository dynatrace-oss/barista, pull requests merged in 2020-08, with the labels that each got.

#1409 chore: Shareable examples win compatibility.
  libs/tools/shareable-examples/src/utils/get-boilerplate-files.ts
Labels: pr: merge-ready, target: minor, target: patch

#1298 ds(sidenav): Added sidenav.
  apps/next/src/app/app.component.scss
  apps/next/src/app/components/sidenav/sidenav.html
  apps/next/src/app/components/sidenav/sidenav.module.ts
  apps/next/src/app/components/sidenav/sidenav.scss
  apps/next/src/app/components/sidenav/sidenav.ts
  apps/next/src/app/pages/single-page/components/sidenav/sidenav.html
  apps/next/src/app/pages/single-page/components/sidenav/sidenav.scss
  apps/next/src/app/pages/single-page/components/sidenav/sidenav.ts
  apps/next/src/app/pages/single-page/single-page.html
  apps/next/src/app/pages/single-page/single-page.module.ts
  apps/next/src/app/pages/single-page/single-page.scss
  apps/next/src/app/styles/_page.scss
  apps/next/src/styles.scss
  libs/tools/barista/src/builder/strapi.ts
  libs/tools/barista/src/generators/ds-navigation.ts
  libs/tools/barista/src/generators/index.ts
  libs/tools/barista/src/main.ts
  libs/tools/barista/src/types.ts
Labels: pr: merge-ready, target: minor, target: patch

#1363 fix(schematics): Make example schematics compatible
  apps/demos/src/app-routing.module.ts
  apps/demos/src/nav-items.ts
  libs/examples/src/combobox/combobox-examples.module.ts
  libs/examples/src/stacked-series-chart/stacked-series-chart-examples.module.ts
  libs/workspace/src/schematics/dt-component-example/__snapshots__/index.spec.ts.snap
  libs/workspace/src/schematics/dt-component-example/example-tools.utils.ts
  libs/workspace/src/schematics/dt-component-example/fixtures/faulty.fixture
  libs/workspace/src/schematics/dt-component-example/fixtures/test-test-example.fixture
  libs/workspace/src/schematics/dt-component-example/index.spec.ts
  libs/workspace/src/schematics/dt-component-example/index.ts
  tools/schematics/README.md
  tools/schematics/collection.json
  tools/schematics/dt-component/README.md
  tools/schematics/dt-component/files/barista-examples/__name@dasherize__/__name@dasherize__-default-example.ts
  tools/schematics/dt-component/files/dev-app/__name__/__name@dasherize__-demo.component.html
  tools/schematics/dt-component/files/dev-app/__name__/__name@dasherize__-demo.component.scss
  tools/schematics/dt-component/files/dev-app/__name__/__name@dasherize__-demo.component.ts
  tools/schematics/dt-component/files/lib/__name__/README.md
  tools/schematics/dt-component/files/lib/__name__/__name@dasherize__-module.ts
  tools/schematics/dt-component/files/lib/__name__/__name@dasherize__.html
  tools/schematics/dt-component/files/lib/__name__/__name@dasherize__.scss
  tools/schematics/dt-component/files/lib/__name__/__name@dasherize__.spec.ts
  tools/schematics/dt-component/files/lib/__name__/__name@dasherize__.ts
  tools/schematics/dt-component/files/lib/__name__/index.ts
  tools/schematics/dt-component/files/lib/__name__/package.json
  tools/schematics/dt-component/files/ui-test-app/__name__/__name@dasherize__-ui.html
  tools/schematics/dt-component/files/ui-test-app/__name__/__name@dasherize__-ui.ts
  tools/schematics/dt-component/files/ui-tests/__name@dasherize__-ui.spec.ts
  tools/schematics/dt-component/index.ts
  tools/schematics/dt-component/schema.json
  tools/schematics/dt-component/schema.ts
  tools/schematics/dt-demo/README.md
  tools/schematics/dt-demo/files/dev-app/__name__/__name@dasherize__-demo.component.html
  tools/schematics/dt-demo/files/dev-app/__name__/__name@dasherize__-demo.component.scss
  tools/schematics/dt-demo/files/dev-app/__name__/__name@dasherize__-demo.component.ts
  tools/schematics/dt-demo/index.ts
  tools/schematics/dt-demo/schema.json
  tools/schematics/dt-demo/schema.ts
  tools/schematics/dt-example/README.md
  tools/schematics/dt-example/files/barista-examples/__component__/__component@dasherize__-__name@dasherize__-example.ts
  tools/schematics/dt-example/index.ts
  tools/schematics/dt-example/schema.json
  tools/schematics/dt-example/schema.ts
  tools/schematics/dt-linting-rule/README.md
  tools/schematics/dt-linting-rule/files/linting/rules/__name@camelize__AltTextRule.ts
  tools/schematics/dt-linting-rule/files/linting/rules/__name@camelize__Rule.ts
  tools/schematics/dt-linting-rule/files/linting/test/rules/__name@dasherize__-rule/alt-text-test.ts.lint
  tools/schematics/dt-linting-rule/files/linting/test/rules/__name@dasherize__-rule/test.ts.lint
  tools/schematics/dt-linting-rule/files/linting/test/rules/__name@dasherize__-rule/tslint.json
  tools/schematics/dt-linting-rule/index.ts
  tools/schematics/dt-linting-rule/schema.json
  tools/schematics/dt-linting-rule/schema.ts
  tools/schematics/package.json
  tools/schematics/tsconfig.json
  tools/schematics/utils/ast-utils.ts
  tools/schematics/utils/index.ts
  tools/schematics/utils/nav-items.ts
Labels: pr: merge-ready, target: minor, target: patch

#1418 chore: Fix scss import paths in next app temporarily.
  apps/next/src/app/pages/single-page/components/sidenav/sidenav.scss
  apps/next/src/app/styles/_page.scss
Labels: pr: merge-ready, target: minor, target: patch

#1417 chore: This is a preparation commit for v10.
  tsconfig.base.json
Labels: pr: merge-ready, target: minor, target: patch

#1419 ds: Change to correct githubuser key in json
  libs/barista-components/experimental/combobox/barista.json
Labels: pr: merge-ready, target: minor, target: patch

#1442 fix(filter-field): Fixes an issue where long free-text values exceed the border of the overlay.
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.scss
Labels: pr: merge-ready, target: minor, target: patch

#1416 fix(chart): Fixes an issue where series visibility was not retained over new data set.
  libs/barista-components/chart/src/chart.spec.ts
  libs/barista-components/chart/src/chart.ts
  libs/barista-components/chart/src/utils.ts
Labels: pr: merge-ready, target: minor, target: patch

#1276 feat(filter-field): Added config for user defined tag parser function
  libs/barista-components/filter-field/README.md
  libs/barista-components/filter-field/index.ts
  libs/barista-components/filter-field/src/filter-field-config.ts
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.spec.ts
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.ts
  libs/barista-components/filter-field/src/filter-field-util.spec.ts
  libs/barista-components/filter-field/src/filter-field-util.ts
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
  libs/barista-components/filter-field/src/types.ts
  libs/examples/src/filter-field/filter-field-custom-parser-example/filter-field-custom-parser-example.html
  libs/examples/src/filter-field/filter-field-custom-parser-example/filter-field-custom-parser-example.ts
  libs/examples/src/filter-field/filter-field-examples.module.ts
  libs/examples/src/filter-field/index.ts
  libs/examples/src/index.ts
Labels: pr: needs-cherry-pick, target: minor

#1437 build(radio): Bazelified radio.
  angular.json
  libs/barista-components/radio/BUILD.bazel
  libs/barista-components/radio/jest.config.js
  libs/barista-components/radio/jest.config.json
  libs/barista-components/radio/src/radio.ts
  libs/barista-components/radio/tsconfig.json
  libs/barista-components/radio/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1450 chore: Fixes an issue where the package version was not propagated to the package.
  .deployment/publish-next-packages/Jenkinsfile
  libs/workspace/src/builders/elements/package-all-elements/build.ts
  libs/workspace/src/builders/elements/package/build.ts
Labels: pr: merge-ready, target: minor, target: patch

#1454 fix(decision-graph): Fixes a test expecting an error.
  apps/barista-design-system/src/pages/decision-graph-page/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node.spec.ts
  apps/barista-design-system/src/pages/decision-graph-page/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node.ts
Labels: pr: merge-ready, target: minor, target: patch

#1459 build(switch): Bazelify switch component
  angular.json
  libs/barista-components/switch/BUILD.bazel
  libs/barista-components/switch/jest.config.js
  libs/barista-components/switch/jest.config.json
  libs/barista-components/switch/tsconfig.json
Labels: bazel

#1473 chore(bazel): Bazelify Expandable-text Component
  angular.json
  libs/barista-components/expandable-text/BUILD.bazel
  libs/barista-components/expandable-text/jest.config.js
  libs/barista-components/expandable-text/jest.config.json
  libs/barista-components/expandable-text/tsconfig.json
  libs/barista-components/expandable-text/tsconfig.lib.json
Labels: bazel

#1479 chore(bazel): Bazelify checkbox component
  angular.json
  libs/barista-components/checkbox/BUILD.bazel
  libs/barista-components/checkbox/jest.config.js
  libs/barista-components/checkbox/jest.config.json
  libs/barista-components/checkbox/tsconfig.json
  libs/barista-components/checkbox/tsconfig.lib.json
Labels: bazel, feature

#1481 build(expandable-text): Fix missing bazel dependencies on compile.
  libs/barista-components/expandable-text/BUILD.bazel
  package-lock.json
Labels: bazel

#1371 fix(tab): Focus bug fixes
  apps/fluid-dev/src/pages/tab/tab-page.component.html
  apps/fluid-dev/src/pages/tab/tab-page.component.ts
  libs/fluid-elements/tab-group/src/lib/tab-events.ts
  libs/fluid-elements/tab-group/src/lib/tab-group/tab-group.spec.ts
  libs/fluid-elements/tab-group/src/lib/tab-group/tab-group.ts
  libs/fluid-elements/tab-group/src/lib/tab/tab.spec.ts
  libs/fluid-elements/tab-group/src/lib/tab/tab.ts
Labels: bug, pr: needs-rebase

#1521 build(fluid-button): Bazelify fluid button.
  WORKSPACE
  libs/fluid-elements/BUILD.bazel
  libs/fluid-elements/button/BUILD.bazel
  libs/shared/design-tokens/BUILD.bazel
  libs/shared/design-tokens/src/index.ts
  patches/@bazel+typescript+2.0.3.patch
Labels: bazel

#1525 chore: Bump @bazel/typescript to the matching version of the workspace.
  package-lock.json
  package.json
Labels: bazel, dependencies

#1530 feat(select): Remove deprecated function in select component
  libs/barista-components/experimental/combobox/src/combobox.ts
  libs/barista-components/select/src/select.spec.ts
  libs/barista-components/select/src/select.ts
Labels: pr: needs-changes, pr: needs-rebase
