Repository dynatrace-oss/barista, pull requests merged in 2020-11, with the labels that each got.

#1782 barista: Fix internal links not properly removed.
  .deployment/barista/public/Jenkinsfile
  libs/tools/barista/src/main.ts
Labels: pr: merge-ready, target: minor, target: patch

#1781 ci: Skip build-docker-images as it fails for months now and does not …
  .circleci/config.yml
Labels: pr: merge-ready, target: minor, target: patch

#1783 ci: Do not fail immediately (if bazel build fails) to be able to shut…
  .buildkite/baristaPipeline.yml
  .buildkite/baristacli.py
Labels: pr: merge-ready, target: minor, target: patch

#1785 chore(tag): Make tag interactive example more understandable.
  libs/examples/src/tag/tag-interactive-example/tag-interactive-example.html
  libs/examples/src/tag/tag-interactive-example/tag-interactive-example.scss
  libs/examples/src/tag/tag-interactive-example/tag-interactive-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#1583 chore(figma-plugin): Integrate the design tokens Figma plugin into the monorepo.
  .nxignore
  WORKSPACE
  angular.json
  apps/figma-design-tokens/BUILD.bazel
  apps/figma-design-tokens/README.md
  apps/figma-design-tokens/manifest.json
  apps/figma-design-tokens/rollup.config.js
  apps/figma-design-tokens/src/code.ts
  apps/figma-design-tokens/src/command-dispatcher.ts
  apps/figma-design-tokens/src/command-handlers/dev/clear-cache.ts
  apps/figma-design-tokens/src/command-handlers/dev/delete-color-tokens.ts
  apps/figma-design-tokens/src/command-handlers/migrate.ts
  apps/figma-design-tokens/src/command-handlers/publish.ts
  apps/figma-design-tokens/src/command-handlers/set-theme.ts
  apps/figma-design-tokens/src/command-handlers/sync.ts
  apps/figma-design-tokens/src/components/loading-spinner.ts
  apps/figma-design-tokens/src/components/metadata-upload-confirm.ts
  apps/figma-design-tokens/src/environment.ts
  apps/figma-design-tokens/src/shared/conversion.ts
  apps/figma-design-tokens/src/shared/figma-util.ts
  apps/figma-design-tokens/src/shared/ipc.ts
  apps/figma-design-tokens/src/shared/storage.ts
  apps/figma-design-tokens/src/shared/types.d.ts
  apps/figma-design-tokens/src/styles.scss
  apps/figma-design-tokens/src/test.css
  apps/figma-design-tokens/src/ui.ts
  apps/figma-design-tokens/src/worker.ts
  apps/figma-design-tokens/tsconfig.json
  libs/barista-components/schematics/src/ng-add/__snapshots__/ng-add.spec.ts.snap
  libs/fluid-elements/button/BUILD.bazel
  libs/fluid-elements/checkbox/BUILD.bazel
  package-lock.json
  package.json
  rules_nodejs-launcher+2.2.1.patch
  rules_nodejs-npm-install+2.2.1.patch
  tools/bazel_rules/figma_bundle/BUILD.bazel
  tools/bazel_rules/figma_bundle/create-figma-bundle.js
  tools/bazel_rules/figma_bundle/figma_bundle_macro.bzl
  tools/bazel_rules/figma_plugin/BUILD.bazel
  tools/bazel_rules/figma_plugin/copy-plugin-files.js
  tools/bazel_rules/figma_plugin/figma_plugin_macro.bzl
  tools/bazel_rules/index.bzl
Labels: next, pr: merge-ready, target: minor, target: patch

#1740 build(design-tokens-ui): Fix design tokens UI reporting failing.
  .deployment/design-tokens-ui/vercel.json
  .github/workflows/design-tokens-ui.yml
Labels: pr: merge-ready, target: minor, target: patch

#1784 chore: Trigger examples build step after publishing.
  Jenkinsfile
Labels: pr: merge-ready, target: minor, target: patch

#1760 chore(filter-field): Refactor unit tests into multiple files
  libs/barista-components/filter-field/BUILD.bazel
  libs/barista-components/filter-field/src/filter-field-edit-mode.spec.ts
  libs/barista-components/filter-field/src/filter-field-with-range.spec.ts
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/testing/filter-field-test-data.ts
  libs/barista-components/filter-field/src/testing/filter-field-test-helpers.ts
Labels: pr: merge-ready, target: minor, target: patch

#1789 chore: Fix stepper example css.
  libs/examples/src/stepper/stepper-default-example/stepper-default-example.scss
  libs/examples/src/stepper/stepper-default-example/stepper-default-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#1788 fix(quick-filter): Fixes an issue where free-text could not be set in a quick-filter environment.
  apps/components-e2e/src/components/filter-field/filter-field.po.ts
  apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
  apps/components-e2e/src/components/quick-filter/quick-filter.po.ts
  libs/barista-components/quick-filter/src/quick-filter.ts
  libs/barista-components/quick-filter/src/state/reducer.ts
Labels: pr: merge-ready, target: minor, target: patch

#1787 Icon and infogroup: Switch to custom properties
  apps/dev/src/devapp.component.scss
  apps/dev/src/icon/icon-demo.component.html
  libs/barista-components/icon/BUILD.bazel
  libs/barista-components/icon/src/_icon-theme.scss
  libs/barista-components/icon/src/icon.scss
  libs/barista-components/info-group/BUILD.bazel
  libs/barista-components/info-group/src/_info-group-theme.scss
  libs/barista-components/info-group/src/info-group.scss
Labels: pr: merge-ready, target: minor

#1794 fix(table): Fixes an issue with typescript 4 compatibility.
  libs/barista-components/table/src/cell.ts
Labels: pr: merge-ready, target: minor, target: patch

#1793 fix(formatters): Fixes an issue with 0 edge-case in number format mode.
  libs/barista-components/formatters/src/duration/duration-formatter-utils/transform-result.ts
  libs/barista-components/formatters/src/duration/duration.spec.ts
  libs/examples/src/formatters/formatters-duration-example/formatters-duration-example.html
Labels: pr: merge-ready, target: minor, target: patch

#1802 chore: Move to prod build for on demand.
  .deployment/barista/public/Jenkinsfile
Labels: pr: merge-ready, target: minor, target: patch

#1791 fix(drawer): Fixes an issue of width-drift when closing the drawer.
  apps/components-e2e/src/components/quick-filter/quick-filter/quick-filter.html
  libs/barista-components/drawer/src/drawer.html
  libs/barista-components/drawer/src/drawer.ts
Labels: pr: merge-ready, target: minor, target: patch

#1792 docs(filter-field): Adds docs explaining nesting nodes
  apps/demos/src/app-routing.module.ts
  apps/demos/src/barista-examples.a11y.ts
  apps/demos/src/nav-items.ts
  libs/barista-components/filter-field/README.md
  libs/examples/src/filter-field/filter-field-examples.module.ts
  libs/examples/src/filter-field/filter-field-infinite-data-depth-example/filter-field-infinite-data-depth-example.html
  libs/examples/src/filter-field/filter-field-infinite-data-depth-example/filter-field-infinite-data-depth-example.ts
  libs/examples/src/filter-field/index.ts
  libs/examples/src/index.ts
Labels: pr: merge-ready, target: minor, target: patch

#1800 fix(filter-field): Fixes a bug in the async example where the async d…
  libs/examples/src/filter-field/filter-field-async-example/filter-field-async-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#1803 fix(quick-filter): Fixes an issue where a range could not be set.
  apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
  libs/barista-components/quick-filter/src/quick-filter.ts
  libs/testing/fixtures/src/lib/filter-field/test-data.ts
Labels: pr: merge-ready, target: minor, target: patch

#1806 feat(context-dialog): Simplifies overriding the maxWidth of the overlay.
  libs/barista-components/context-dialog/README.md
  libs/barista-components/context-dialog/src/context-dialog.scss
  libs/barista-components/context-dialog/src/context-dialog.ts
Labels: pr: merge-ready, target: minor

#1805 feat(table): Don't show empty state while loading.
  apps/components-e2e/src/components/table/BUILD.bazel
  apps/components-e2e/src/components/table/table-simple/table-simple.html
  apps/components-e2e/src/components/table/table-simple/table-simple.ts
  apps/components-e2e/src/components/table/table.e2e.ts
  apps/components-e2e/src/components/table/table.module.ts
  apps/components-e2e/src/components/table/table.po.ts
  apps/dev/src/table/table-demo.component.html
  apps/dev/src/table/table-demo.component.ts
  libs/barista-components/table/src/table.html
Labels: pr: needs-cherry-pick, target: minor

#1808 chore: Internal link check in jenkins pipeline
  .deployment/barista/public/Jenkinsfile
  tools/scripts/internal-link-checker.js
Labels: pr: merge-ready, target: minor, target: patch

#1811 barista: Allow subpages to be created in strapi without breaking the navigation.
  libs/tools/barista/src/generators/category-navigation.ts
Labels: pr: merge-ready, target: minor, target: patch

#1804 fix(combobox): Fixes an issue with the combobox where the initial value caused a change detection error.
  apps/components-e2e/src/components/combobox/BUILD.bazel
  apps/components-e2e/src/components/combobox/combobox.e2e.ts
  apps/components-e2e/src/components/combobox/combobox.html
  apps/components-e2e/src/components/combobox/combobox.po.ts
  apps/components-e2e/src/components/combobox/combobox.ts
  apps/demos/src/barista-examples.a11y.ts
  libs/barista-components/experimental/combobox/src/combobox.ts
Labels: pr: merge-ready, target: minor, target: patch

#1809 fix(filter-field): Fixes an issue with async data and programmatically set filters.
  apps/components-e2e/src/components/filter-field/filter-field.po.ts
  apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
  libs/barista-components/filter-field/src/filter-field-util.ts
Labels: pr: merge-ready, target: minor, target: patch

#1725 chore(schematics): Nx workspace dt-component schematics.
  DEVELOPMENT.md
  patches/@angular-devkit+schematics+10.0.4.patch
  tools/schematics/dt-component-example/README.md
  tools/schematics/dt-component/README.md
  tools/schematics/dt-component/files/libs/barista-components/__name@dasherize__/barista.json
  tools/schematics/dt-component/files/libs/barista-components/__name@dasherize__/index.ts
  tools/schematics/dt-component/files/libs/barista-components/__name@dasherize__/package.json
  tools/schematics/dt-component/files/libs/barista-components/__name@dasherize__/src/__name@dasherize__-module.ts
  tools/schematics/dt-component/files/libs/barista-components/__name@dasherize__/src/__name@dasherize__.html
  tools/schematics/dt-component/files/libs/barista-components/__name@dasherize__/src/__name@dasherize__.scss
  tools/schematics/dt-component/files/libs/barista-components/__name@dasherize__/src/__name@dasherize__.spec.ts
  tools/schematics/dt-component/files/libs/barista-components/__name@dasherize__/src/__name@dasherize__.ts
  tools/schematics/dt-component/index.ts
  tools/schematics/dt-component/schema.json
Labels: pr: merge-ready, target: minor, target: patch

#1812 test(combobox): Skip flaky test in the combobox.
  apps/components-e2e/src/components/combobox/combobox.ts
Labels: pr: merge-ready, target: minor, target: patch

#1820 chore: Add snyk exception until upgrade to angular@^11
  .snyk
Labels: pr: merge-ready, target: minor, target: patch

#1822 barista: Fixes preview builds for branches.
  .github/workflows/barista-preview.yml
Labels: pr: merge-ready, target: minor, target: patch

#1810 feat(indicator): add indicator theme 'recovered' (green indicator)
  apps/dev/src/indicator/indicator-demo.component.ts
  libs/barista-components/indicator/README.md
  libs/barista-components/indicator/src/indicator.scss
  libs/barista-components/indicator/src/indicator.spec.ts
  libs/barista-components/indicator/src/indicator.ts
  libs/barista-components/table/src/_row-theme.scss
  libs/barista-components/table/src/cell.ts
  libs/barista-components/table/src/row.ts
  libs/barista-components/tree-table/src/_tree-table-row-theme.scss
  libs/examples/src/indicator/indicator-default-example/indicator-default-example.html
  libs/examples/src/indicator/indicator-default-example/indicator-default-example.ts
  libs/examples/src/table/table-problem-example/table-problem-example.ts
Labels: pr: needs-cherry-pick

#1821 fix(filter-field): Fixes an issue where the filterChanges event was not triggered.
  libs/barista-components/filter-field/src/filter-field-edit-mode.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#1823 refactor(switch): Custom properties.
  concepts/design-tokens/README.md
  libs/barista-components/switch/BUILD.bazel
  libs/barista-components/switch/src/_switch-theme.scss
  libs/barista-components/switch/src/switch.scss
Labels: pr: merge-ready, target: minor, target: patch

#1825 fix(combobox): Fixes an issue where the combobox flap did not close.
  libs/barista-components/experimental/combobox/src/combobox.ts
Labels: pr: merge-ready, target: minor, target: patch

#1826 fix(filter-field): Fixes an issue with confusing disabled styles.
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.html
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.scss
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.ts
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/examples/src/filter-field/filter-field-readonly-non-editable-tags-example/filter-field-readonly-non-editable-tags-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#1832 feat(tooltip): support for custom positioner
  libs/barista-components/chart/README.md
  libs/barista-components/chart/index.ts
  libs/barista-components/chart/src/tooltip/chart-tooltip-position.ts
  libs/barista-components/chart/src/tooltip/chart-tooltip.ts
  libs/examples/src/chart/chart-bar-example/chart-bar-example.html
  libs/examples/src/chart/chart-bar-example/chart-bar-example.ts
Labels: pr: needs-cherry-pick

#1835 barista: Fix barista public publish.
  .deployment/barista/public/Jenkinsfile
  libs/examples/src/event-chart/event-chart-overlapping-load-example/event-chart-overlapping-load-example.ts
  libs/examples/src/event-chart/event-chart-session-replay-example/event-chart-session-replay-example.ts
  tools/scripts/internal-link-checker.js
Labels: pr: merge-ready, target: minor, target: patch

#1837 fix(quick-filter): Fixes an issue with varying width of the quick-filter sidebar.
  libs/barista-components/drawer/src/drawer-container.scss
  libs/barista-components/quick-filter/src/quick-filter.scss
Labels: pr: merge-ready, target: minor, target: patch

#1839 barista: Remove code owners from barista pages.
  apps/barista-design-system/src/pages/single-page/components/contributors/contributors.html
  apps/barista-design-system/src/pages/single-page/components/contributors/contributors.scss
  apps/barista-design-system/src/pages/single-page/components/contributors/contributors.ts
  apps/barista-design-system/src/pages/single-page/components/contributors/index.ts
  apps/barista-design-system/src/pages/single-page/components/page-header/page-header.html
  apps/barista-design-system/src/pages/single-page/components/page-header/page-header.ts
  apps/barista-design-system/src/pages/single-page/single-page.module.ts
Labels: pr: merge-ready, target: minor, target: patch

#1843 fix(table): Fixes an issue with the empty state not showing up without change detection.
  libs/barista-components/table/src/table.ts
Labels: pr: merge-ready, target: minor, target: patch

#1841 fix(chart): Fixes an issue with the heatfield when resizing the chart.
  apps/components-e2e/src/components/chart/heatfield/heatfield.e2e.ts
  libs/barista-components/chart/src/chart.ts
Labels: pr: merge-ready, target: minor, target: patch
