Repository dynatrace-oss/barista, pull requests merged in 2020-01, with the labels that each got.

#384 ci: Store build artefacts for components.
  .circleci/config.yml
Labels: P1

#378 barista: Fix duplicate headline ids and wrong headlines in TOC.
  apps/barista/src/layout/toc/toc.ts
  apps/barista/src/shared/toc.service.ts
  tools/barista/src/transform.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#381 fix(sidenav): Fixes scrolling behavior of the sidenav component
  components/drawer/src/sidenav.scss
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#374 barista: Added document title to each page.
  apps/barista/src/app.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#371 docs(pagination): Remove page output from the documentation.
  components/pagination/README.md
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#382 feat(chart-timestamp): Add possibility to close chart-timestamp programmatically
  components/chart/README.md
  components/chart/src/timestamp/timestamp.spec.ts
  components/chart/src/timestamp/timestamp.ts
Labels: pr: lgtm

#387 build: Fix not running components build.
  angular.json
Labels: P0

#373 chore(build): Remove root package
  components/index.ts
  components/package.json
  documentation/getting-started.md
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#386 ci: Use xlarge resource classes.
  .circleci/config.yml
Labels: P2

#395 barista: Fixed issue where change detection was triggered too often w…
  apps/barista/src/layout/scroll-to-top/scroll-to-top.ts
  apps/barista/src/layout/toc/toc.ts
  apps/barista/src/shared/toc.service.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#296 feat(show-more): Changed the selector to button[dt-show-more], remove…
  apps/components-e2e/src/components/show-more/show-more.e2e.ts
  apps/components-e2e/src/components/show-more/show-more.html
  apps/dev/src/show-more/show-more-demo.component.html
  apps/dev/src/show-more/show-more-demo.component.ts
  apps/universal/src/app/kitchen-sink/kitchen-sink.html
  components/show-more/README.md
  components/show-more/barista.json
  components/show-more/src/_show-more-theme.scss
  components/show-more/src/show-more-module.ts
  components/show-more/src/show-more.html
  components/show-more/src/show-more.scss
  components/show-more/src/show-more.spec.ts
  components/show-more/src/show-more.ts
  libs/examples/src/show-more/show-more-dark-example/show-more-dark-example.html
  libs/examples/src/show-more/show-more-default-example/show-more-default-example.html
  libs/examples/src/show-more/show-more-default-example/show-more-default-example.ts
  libs/examples/src/show-more/show-more-disabled-example/show-more-disabled-example.html
  libs/examples/src/show-more/show-more-examples.module.ts
  libs/examples/src/show-more/show-more-interactive-example/show-more-interactive-example.html
  libs/examples/src/show-more/show-more-notext-example/show-more-notext-example.html
  libs/examples/src/show-more/show-more-notext-example/show-more-notext-example.ts
  libs/examples/src/show-more/show-more-toggle-example/show-more-toggle-example.html
  libs/examples/src/show-more/show-more-toggle-example/show-more-toggle-example.ts
  libs/examples/src/table/table-show-more-example/table-show-more-example.html
  tools/linting/src/rules/dtShowMoreNoEmptyRule.ts
  tools/linting/src/test/rules/dt-show-more-no-empty-rule/test.ts.lint
Labels: pr: lgtm, pr: merge-ready, target: major

#391 build: Added syncing the barista-component version to the artifacts package.json
  angular.json
  components/package.json
  tools/builders/packager/build.ts
  tools/builders/packager/schema.json
  tools/builders/packager/schema.ts
  tools/builders/packager/sync-version.ts
  tools/builders/util/json-utils.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#370 Feat/table favorite column
  components/table/README.md
  components/table/src/simple-columns/favorite-column.html
  components/table/src/simple-columns/favorite-column.scss
  components/table/src/simple-columns/favorite-column.ts
  components/table/src/simple-columns/index.ts
  components/table/src/simple-columns/simple-column.spec.ts
  components/table/src/table-module.ts
  libs/examples/src/table/table-examples.module.ts
  libs/examples/src/table/table-favorite-column-example/table-favorite-column-example.html
  libs/examples/src/table/table-favorite-column-example/table-favorite-column-example.ts
  libs/examples/src/table/table-favorite-column-no-header-example/table-favorite-column-no-header-example.html
  libs/examples/src/table/table-favorite-column-no-header-example/table-favorite-column-no-header-example.ts
Labels: feature, pr: lgtm, pr: merge-ready, target: minor

#368 barista(copy-headlines): Copy the headlines to clipboard.
  apps/barista/src/app.module.ts
  apps/barista/src/components/components.module.ts
  apps/barista/src/components/headline-link/headline-link.html
  apps/barista/src/components/headline-link/headline-link.ts
  apps/barista/src/styles/items/_headlines.scss
  apps/barista/src/styles/items/_items-dir.scss
  tools/barista/src/builder/components.ts
  tools/barista/src/builder/strapi.ts
  tools/barista/src/transform.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#399 Store build artifacts as tar.gz file
  .circleci/config.yml
Labels: P1

#407 fix(filter-field): Fixes an issue where the filtering of groups did not work properly because of a wrong param ordering.
  components/filter-field/src/filter-field-util.spec.ts
  components/filter-field/src/filter-field-util.ts
Labels: P1, bug, pr: lgtm, pr: merge-ready, target: minor, target: patch

#413 chore(demos): Add DtInputModule to AppModule to fix directive being a…
  apps/demos/src/app.module.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#406 barista: Generate IDs for headlines on icon-related pages.
  tools/barista/src/builder/icons.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#410 fix(chart): Fixes an issue with not appearing tooltips.
  components/chart/src/chart.ts
  components/chart/src/tooltip/chart-tooltip.spec.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#398 barista: Fix chart behavior switch example.
  libs/examples/src/chart/chart-behavior-switch-example/chart-behavior-switch-example.html
  libs/examples/src/chart/chart-behavior-switch-example/chart-behavior-switch-example.ts
Labels: target: minor, target: patch

#401 fix: Overlay scroll strategy not working with the sidenav component
  apps/components-e2e/src/components/drawer/drawer.e2e.ts
  apps/components-e2e/src/components/drawer/drawer.html
  apps/components-e2e/src/components/drawer/drawer.module.ts
  apps/components-e2e/src/components/drawer/drawer.ts
  components/drawer/src/drawer-container.html
  components/drawer/src/drawer-module.ts
  components/drawer/src/sidenav-container.html
Labels: pr: lgtm

#412 chore(chart): Fixed an configuration issue with the min/max example.
  libs/examples/src/chart/chart-min-max-example/chart-min-max-example.ts
Labels: pr: lgtm, target: minor, target: patch

#394 feat(event-chart): Added programmatic event selection capabilities to…
  apps/components-e2e/src/app/app.routing.module.ts
  apps/components-e2e/src/components/event-chart/event-chart.e2e.ts
  apps/components-e2e/src/components/event-chart/event-chart.html
  apps/components-e2e/src/components/event-chart/event-chart.module.ts
  apps/components-e2e/src/components/event-chart/event-chart.po.ts
  apps/components-e2e/src/components/event-chart/event-chart.ts
  components/event-chart/README.md
  components/event-chart/src/event-chart.html
  components/event-chart/src/event-chart.spec.ts
  components/event-chart/src/event-chart.ts
  libs/examples/src/event-chart/event-chart-complex-selection-example/event-chart-complex-selection-example.html
  libs/examples/src/event-chart/event-chart-complex-selection-example/event-chart-complex-selection-example.ts
  libs/examples/src/event-chart/event-chart-examples.module.ts
Labels: pr: lgtm, target: minor, target: patch

#426 chore: Bump version to 5.0.0-rc.0 w/ changelog
  CHANGELOG.md
  package.json
Labels: pr: lgtm, target: minor, target: patch

#436 Create .npmrc files in the publish step
  tools/release/src/circle-ci-api/circle-ci-api.spec.ts
  tools/release/src/circle-ci-api/circle-ci-api.ts
  tools/release/src/publish-release/publish-release.spec.ts
  tools/release/src/publish-release/publish-release.ts
  tools/release/src/utils/publish-package.spec.ts
  tools/release/src/utils/publish-package.ts
  tools/release/src/utils/release-errors.ts
Labels: P1

#443 ci: Check if components folder exists befor trying to tar it
  .circleci/config.yml
Labels: P1, bug

#421 chore: Lock remote edge e2e test version to 18 on windows.
  angular.json
  apps/components-e2e/src/components/key-value-list/key-value-list.e2e.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#448 ci: Add Jenkinsfile for internal release pipeline
  Jenkinsfile
  tools/release/src/publish-release/publish-release.spec.ts
  tools/release/src/publish-release/publish-release.ts
  tools/release/src/tagging.ts
  tools/release/src/utils/create-release-tag.spec.ts
  tools/release/src/utils/create-release-tag.ts
  tools/release/src/utils/index.ts
Labels: P1

#305 chore(tools): Add the auto cherry-picker back to the repository
  .github/workflows/cherry-picker.yml
  tools/cherry-picker/.dockerignore
  tools/cherry-picker/.gitignore
  tools/cherry-picker/Dockerfile
  tools/cherry-picker/entrypoint.sh
  tools/cherry-picker/package-lock.json
  tools/cherry-picker/package.json
  tools/cherry-picker/src/main.ts
  tools/cherry-picker/src/utils/find-merged-commits-on-master.ts
  tools/cherry-picker/src/utils/get-current-minor-and-patch-branches.ts
  tools/cherry-picker/src/utils/get-pull-request-details.ts
  tools/cherry-picker/src/utils/is-master-target.ts
  tools/cherry-picker/src/utils/pull-request-add-comment.ts
  tools/cherry-picker/src/utils/pull-request-has-label.ts
  tools/cherry-picker/tsconfig.json
  tools/cherry-picker/tslint.json
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#425 fix(tag-add): Improved styling of button textcontent
  components/tag/src/tag-add/tag-add.html
  components/tag/src/tag-add/tag-add.scss
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#423 fix(tag-list): Fixes rendering of Tag-List when loading a page
  components/tag/src/tag-list/tag-list.scss
  components/tag/src/tag-list/tag-list.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#471 chore: Updated caniuse-lite browserlist
  package-lock.json
Labels: pr: lgtm, target: minor, target: patch

#455 feat(ng-update): Added test for .spec file
  components/schematics/src/ng-update/tests/__snapshots__/root-imports.spec.ts.snap
  components/schematics/src/ng-update/tests/root-imports.spec.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#474 Fixes flaky chart selection area e2e tests.
  .circleci/config.yml
  angular.json
  apps/components-e2e/src/components/chart/selection-area/selection-area.e2e.ts
  apps/components-e2e/src/components/chart/selection-area/selection-area.po.ts
  apps/components-e2e/src/components/drawer/drawer.e2e.ts
Labels: P2, pr: lgtm, target: minor, target: patch

#372 Fix/radial charts tooltip issue
  apps/components-e2e/src/components/chart/chart.module.ts
  apps/components-e2e/src/components/chart/chart/chart.e2e.ts
  apps/components-e2e/src/components/chart/chart/chart.html
  apps/components-e2e/src/components/chart/pie-chart/pie-chart.e2e.ts
  apps/components-e2e/src/components/chart/pie-chart/pie-chart.html
  apps/components-e2e/src/components/chart/pie-chart/pie-chart.ts
  components/chart/src/chart.ts
  components/chart/src/highcharts/highcharts-tooltip-extensions.ts
  components/chart/src/highcharts/highcharts-tooltip-types.ts
  components/chart/src/tooltip/chart-tooltip.ts
Labels: P1, bug, pr: lgtm, target: minor, target: patch

#477 ci: Ignore temporary cherrypick branches.
  .circleci/config.yml
Labels: P2, pr: lgtm, target: minor, target: patch

#481 Only run 4 e2e tests in parallel to leave space in the queue.
  angular.json
Labels: P1, pr: lgtm, target: minor, target: patch

#480 ci: Fixes an issue with the autolabeler applying wrong labels.
  .github/CODEOWNERS
  angular.json
  nx.json
  tools/pull-request-labeler/jest.config.js
  tools/pull-request-labeler/src/main.ts
  tools/pull-request-labeler/src/test-setup.ts
  tools/pull-request-labeler/src/utils/process-commit-messages.spec.ts
  tools/pull-request-labeler/src/utils/process-commit-messages.ts
  tools/pull-request-labeler/src/utils/split-message-into-components.spec.ts
  tools/pull-request-labeler/src/utils/split-message-into-components.ts
  tools/pull-request-labeler/tsconfig.spec.json
Labels: pr: lgtm, target: minor, target: patch

#482 test(drawer): Fixes flaky drawer e2e tests.
  apps/components-e2e/src/components/drawer/drawer.e2e.ts
  apps/components-e2e/src/utils/wait-for-angular.ts
Labels: P2, pr: lgtm, pr: merge-ready, target: minor, target: patch

#419 barista(examples): Examples cleanup and adding gray background to Car…
  apps/barista/src/app.module.ts
  apps/barista/src/components/live-example/live-example.html
  apps/barista/src/components/live-example/live-example.scss
  apps/barista/src/components/live-example/live-example.ts
  components/alert/README.md
  components/bar-indicator/README.md
  components/breadcrumbs/README.md
  components/button-group/README.md
  components/button/README.md
  components/card/README.md
  components/chart/README.md
  components/checkbox/README.md
  components/context-dialog/README.md
  components/copy-to-clipboard/README.md
  components/core/src/indicator/README.md
  components/empty-state/README.md
  components/event-chart/README.md
  components/expandable-section/README.md
  components/filter-field/README.md
  components/icon/README.md
  components/info-group/README.md
  components/input/README.md
  components/key-value-list/README.md
  components/menu/README.md
  components/micro-chart/README.md
  components/progress-bar/README.md
  components/radio/README.md
  components/show-more/README.md
  components/stepper/README.md
  components/style/README.md
  components/switch/README.md
  components/table/README.md
  components/tile/README.md
  components/toast/README.md
  components/tree-table/README.md
  libs/examples/src/context-dialog/context-dialog-actions-example/context-dialog-actions-example.html
  libs/examples/src/context-dialog/context-dialog-examples.module.ts
  libs/examples/src/menu/menu-examples.module.ts
  libs/examples/src/secondary-nav/secondary-nav-examples.module.ts
  libs/examples/src/tabs/tabs-dynamic-example/tabs-dynamic-example.html
  libs/examples/src/toggle-button-group/toggle-button-group-examples.module.ts
  libs/examples/src/toggle-button-group/toggle-button-group-in-use-example/toggle-button-group-in-use-example.html
  libs/examples/src/toggle-button-group/toggle-button-group-in-use-example/toggle-button-group-in-use-example.scss
  libs/examples/src/toggle-button-group/toggle-button-group-in-use-example/toggle-button-group-in-use-example.ts
Labels: design-system, pr: lgtm, target: minor, target: patch

#485 chore(drawer): Removes only
  apps/components-e2e/src/components/drawer/drawer.e2e.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#487 chore(filter-field): Fixes invalid example data.
  libs/examples/src/filter-field/filter-field-async-example/filter-field-async-example.ts
  libs/examples/src/filter-field/filter-field-clearall-example/filter-field-clearall-example.ts
  libs/examples/src/filter-field/filter-field-default-example/filter-field-default-example.ts
  libs/examples/src/filter-field/filter-field-distinct-example/filter-field-distinct-example.ts
  libs/examples/src/filter-field/filter-field-programmatic-filters-example/filter-field-programmatic-filters-example.ts
  libs/examples/src/filter-field/filter-field-readonly-non-editable-tags-example/filter-field-readonly-non-editable-tags-example.ts
Labels: P1, pr: lgtm, pr: merge-ready, target: minor, target: patch

#484 baritsa(live-examples): Added SCSS to live examples.
  apps/barista/src/components/live-example/live-example.html
  apps/barista/src/components/live-example/live-example.ts
  libs/shared/barista-definitions/src/lib/example-definitions.ts
  tools/barista/src/transform.ts
  tools/examples/src/generate-examples-lib-metadata.ts
  tools/examples/src/metadata.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#475 test: Added e2e tests for confirmation-dialog and highlight
  apps/components-e2e/src/app/app.routing.module.ts
  apps/components-e2e/src/components/chart/selection-area/selection-area.ts
  apps/components-e2e/src/components/confirmation-dialog/confirmation-dialog.e2e.ts
  apps/components-e2e/src/components/confirmation-dialog/confirmation-dialog.html
  apps/components-e2e/src/components/confirmation-dialog/confirmation-dialog.module.ts
  apps/components-e2e/src/components/confirmation-dialog/confirmation-dialog.po.ts
  apps/components-e2e/src/components/confirmation-dialog/confirmation-dialog.ts
  apps/components-e2e/src/components/drawer/drawer.ts
  apps/components-e2e/src/components/highlight/highlight.e2e.ts
  apps/components-e2e/src/components/highlight/highlight.html
  apps/components-e2e/src/components/highlight/highlight.module.ts
  apps/components-e2e/src/components/highlight/highlight.po.ts
  apps/components-e2e/src/components/highlight/highlight.ts
Labels: pr: lgtm, pr: merge-ready, target: major, target: minor, target: patch

#404 fix(filter-field): Fixes an issue with instant submission of free-text.
  apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
  apps/components-e2e/src/components/filter-field/filter-field.po.ts
  apps/components-e2e/src/components/filter-field/filter-field.ts
  components/filter-field/src/filter-field.html
  components/filter-field/src/filter-field.spec.ts
  components/filter-field/src/filter-field.ts
Labels: bug

#340 barista(error-pages): Add error pages to barista, wip
  apps/barista/src/app.html
  apps/barista/src/app.module.ts
  apps/barista/src/app.ts
  apps/barista/src/pages/error-page/error-page.html
  apps/barista/src/pages/error-page/error-page.scss
  apps/barista/src/pages/error-page/error-page.ts
  apps/barista/src/pages/index-page/index-page.scss
  apps/barista/src/pages/overview-page/overview-page.scss
  apps/barista/src/pages/page-outlet.scss
  apps/barista/src/pages/page-outlet.ts
  apps/barista/src/pages/single-page/single-page.scss
  apps/barista/src/pages/single-page/single-page.ts
  apps/barista/src/shared/page.service.ts
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/src/builder/homepage.ts
  tools/barista/src/generators/category-navigation.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#490 fix(filter-field): Fixes an issue with button alignments in the filter field.
  components/button/src/button.scss
  components/filter-field/src/filter-field.scss
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#502 barista: Add router config to not interfere with the location service.
  apps/barista/src/app.module.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#492 chore: Updated codeowners to better fit the team structure and roles.
  .github/CODEOWNERS
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#500 feat(tree-table): Added events for expansion state changes
  apps/components-e2e/src/app/app.routing.module.ts
  apps/components-e2e/src/components/chart/selection-area/selection-area.ts
  apps/components-e2e/src/components/drawer/drawer.ts
  apps/components-e2e/src/components/tree-table/tree-table.e2e.ts
  apps/components-e2e/src/components/tree-table/tree-table.html
  apps/components-e2e/src/components/tree-table/tree-table.module.ts
  apps/components-e2e/src/components/tree-table/tree-table.po.ts
  apps/components-e2e/src/components/tree-table/tree-table.ts
  components/tree-table/README.md
  components/tree-table/src/tree-table-toggle-cell.html
  components/tree-table/src/tree-table-toggle-cell.ts
  components/tree-table/src/tree-table.spec.ts
Labels: feature, pr: lgtm, target: minor

#501 ci: Change labeler to run on merge-ready instead of lgtm.
  tools/pull-request-labeler/src/main.ts
  tools/pull-request-labeler/src/utils/has-merge-ready-label.ts
Labels: pr: lgtm, pr: merge-ready, target: minor, target: patch

#493 barista: Get UX snippet content from Strapi.
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/src/builder/components.ts
  tools/barista/src/transform.ts
  tools/barista/src/utils/fetch-strapi-content.ts
Labels: pr: merge-ready, target: minor, target: patch

#498 barista: Create missing snippets in Strapi when component pages are b…
  tools/barista/src/builder/components.ts
Labels: pr: merge-ready, target: minor, target: patch

#483 ci: Run the labeler on labeled step only.
  .github/workflows/pull-request-labeler.yml
Labels: pr: merge-ready, target: minor, target: patch

#489 test(drawer): Slow down e2e test to make it more stable.
  apps/components-e2e/src/components/drawer/drawer.e2e.ts
Labels: pr: merge-ready, target: minor, target: patch

#486 test(release): Fixes testing issues on windows with wrong root path expectations
  tools/release/src/publish-release/publish-release.spec.ts
  tools/release/src/utils/publish-package.spec.ts
Labels: pr: merge-ready, target: minor, target: patch

#510 barista: Update Strapi endpoint.
  tools/barista/src/builder/components.ts
  tools/barista/src/utils/fetch-strapi-content.ts
Labels: pr: merge-ready, target: minor, target: patch

#506 barista: Added transformer that removes content marked as internal fr…
  tools/barista/src/main.ts
  tools/barista/src/transform.ts
Labels: pr: merge-ready, target: minor, target: patch

#499 feat(table): Expose currently rendered data from the datasource.
  components/table/src/table-data-source.ts
Labels: pr: merge-ready, target: minor

#512 fix(timeline-chart): Fixes an issue where the label of a key timing marker was cut off.
  components/timeline-chart/src/timeline-chart.html
  components/timeline-chart/src/timeline-chart.scss
Labels: pr: merge-ready, target: minor, target: patch

#511 feat(copy-to-clipboard): Added `variant` input to control embedded button variant.
  components/copy-to-clipboard/README.md
  components/copy-to-clipboard/src/copy-to-clipboard.html
  components/copy-to-clipboard/src/copy-to-clipboard.ts
  libs/examples/src/copy-to-clipboard/copy-to-clipboard-examples.module.ts
  libs/examples/src/copy-to-clipboard/copy-to-clipboard-secondary-button-example/copy-to-clipboard-secondary-button-example.html
  libs/examples/src/copy-to-clipboard/copy-to-clipboard-secondary-button-example/copy-to-clipboard-secondary-button-example.ts
Labels: feature, pr: merge-ready, target: minor
