Repository dynatrace-oss/barista, pull requests merged in 2020-03, with the labels that each got.

#685 barista: Update exit code when page builder is failing somewhere.
  libs/tools/barista/src/main.ts
Labels: pr: merge-ready, target: minor, target: patch

#687 chore: Update Nx and Angular dependencies to get the latest fixes.
  libs/barista-components/schematics/src/ng-add/__snapshots__/ng-add.spec.ts.snap
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#681 barista: Fix issue where internal content could not be replaced corre…
  libs/tools/barista/src/transform.ts
Labels: pr: merge-ready, target: minor, target: patch

#689 chore: Remove unused nest dependencies.
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#688 feat(colors): Add flat white to colors list
  libs/barista-components/core/src/style/_colors.scss
  libs/barista-components/theming/src/colors.ts
Labels: pr: merge-ready, pr: needs-cherry-pick

#686 Improve stackblitz button and remove hide source to reduce noise
  apps/barista-design-system/src/components/live-example/live-example.html
  apps/barista-design-system/src/components/live-example/live-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#682 chore: Fix path to shareable examples lib
  environments/barista-environment.prod.ts
  environments/barista-environment.ts
Labels: pr: merge-ready, target: minor, target: patch

#660 fix(filter-field): Fixes same character filtering issue
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#654 feat(empty-state): Progressive enhancements for relayout based on ResizeObserver
  apps/components-e2e/src/app/app.routing.module.ts
  apps/components-e2e/src/components/empty-state/empty-state.e2e.ts
  apps/components-e2e/src/components/empty-state/empty-state.html
  apps/components-e2e/src/components/empty-state/empty-state.module.ts
  apps/components-e2e/src/components/empty-state/empty-state.po.ts
  apps/components-e2e/src/components/empty-state/empty-state.ts
  libs/barista-components/empty-state/src/empty-state.ts
  libs/barista-components/table/src/table.ts
  typings.d.ts
Labels: pr: merge-ready, target: minor

#642 fix(tag): Fixed an issue with the tag-add button being influenced by UA styles.
  libs/barista-components/tag/src/tag-add/tag-add.scss
Labels: pr: merge-ready, target: minor, target: patch

#691 fix(key-value-list): Change CSS to fix overflow issues fixes #690
  libs/barista-components/key-value-list/src/key-value-list-item.scss
Labels: pr: needs-cherry-pick

#693 docs: added ux snippet for select intro
  libs/barista-components/select/README.md
Labels: pr: needs-cherry-pick

#698 barista: Fix the match selector.
  libs/tools/barista/src/transform.ts
Labels: design-system, pr: merge-ready, target: minor, target: patch

#700 build(windows): Fix Windows Build & Test issues
  libs/barista-components/schematics/jest.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: pr: needs-cherry-pick

#697 fix(chart-heatfield): Chart HeatField is shown when start and end are…
  libs/barista-components/chart/src/heatfield/chart-heatfield.html
  libs/barista-components/chart/src/heatfield/chart-heatfield.spec.ts
Labels: bug, pr: needs-cherry-pick

#702 fix(radio, checkbox, switch): Disabled labels have have a higher contrast color now
  libs/barista-components/checkbox/src/_checkbox-theme.scss
  libs/barista-components/checkbox/src/checkbox.scss
  libs/barista-components/radio/src/_radio-theme.scss
  libs/barista-components/radio/src/radio.scss
  libs/barista-components/switch/src/_switch-theme.scss
  libs/barista-components/switch/src/switch.scss
Labels: pr: merge-ready, target: minor, target: patch

#703 chore(e2e): Fixes a flaky e2e test for the filter field.
  apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
Labels: pr: merge-ready, target: minor, target: patch

#714 chore(stylelint): Remove selector class matching in examples
  angular.json
  libs/examples/.stylelintrc
Labels: pr: merge-ready, target: minor, target: patch

#713 docs(form-field): Added server side form field validation example.
  libs/examples/src/form-field/form-field-examples.module.ts
  libs/examples/src/form-field/form-field-server-validation/form-field-server-validation-example.html
  libs/examples/src/form-field/form-field-server-validation/form-field-server-validation-example.scss
  libs/examples/src/form-field/form-field-server-validation/form-field-server-validation-example.ts
  libs/examples/src/index.ts
Labels: pr: merge-ready, pr: needs-cherry-pick

#719 Add barrel files for examples as pre step for lazy loading them
  libs/examples/src/alert/index.ts
  libs/examples/src/autocomplete/index.ts
  libs/examples/src/bar-indicator/index.ts
  libs/examples/src/breadcrumbs/index.ts
  libs/examples/src/button-group/index.ts
  libs/examples/src/button/index.ts
  libs/examples/src/card/index.ts
  libs/examples/src/chart/index.ts
  libs/examples/src/checkbox/index.ts
  libs/examples/src/confirmation-dialog/index.ts
  libs/examples/src/consumption/index.ts
  libs/examples/src/container-breakpoint-observer/index.ts
  libs/examples/src/context-dialog/index.ts
  libs/examples/src/copy-to-clipboard/index.ts
  libs/examples/src/cta-card/index.ts
  libs/examples/src/drawer/index.ts
  libs/examples/src/empty-state/index.ts
  libs/examples/src/event-chart/index.ts
  libs/examples/src/expandable-panel/index.ts
  libs/examples/src/expandable-section/index.ts
  libs/examples/src/expandable-text/index.ts
  libs/examples/src/filter-field/index.ts
  libs/examples/src/form-field/index.ts
  libs/examples/src/formatters/index.ts
  libs/examples/src/highlight/index.ts
  libs/examples/src/icon/index.ts
  libs/examples/src/info-group/index.ts
  libs/examples/src/inline-editor/index.ts
  libs/examples/src/input/index.ts
  libs/examples/src/key-value-list/index.ts
  libs/examples/src/legend/index.ts
  libs/examples/src/link/index.ts
  libs/examples/src/loading-distractor/index.ts
  libs/examples/src/menu/index.ts
  libs/examples/src/micro-chart/index.ts
  libs/examples/src/overlay/index.ts
  libs/examples/src/pagination/index.ts
  libs/examples/src/progress-bar/index.ts
  libs/examples/src/progress-circle/index.ts
  libs/examples/src/radial-chart/index.ts
  libs/examples/src/radio/index.ts
  libs/examples/src/secondary-nav/index.ts
  libs/examples/src/select/index.ts
  libs/examples/src/show-more/index.ts
  libs/examples/src/sidenav/index.ts
  libs/examples/src/stepper/index.ts
  libs/examples/src/switch/index.ts
  libs/examples/src/table/index.ts
  libs/examples/src/tabs/index.ts
  libs/examples/src/tag/index.ts
  libs/examples/src/tile/index.ts
  libs/examples/src/timeline-chart/index.ts
  libs/examples/src/toast/index.ts
  libs/examples/src/toggle-button-group/index.ts
  libs/examples/src/top-bar-navigation/index.ts
  libs/examples/src/tree-table/index.ts
Labels: design-system, pr: merge-ready, target: minor, target: patch

#701 chore: Fixes the generation of stackblitz examples after the angular 9 upgrade
  libs/examples/src/cta-card/cta-card-closable-example/cta-card-closable-example.html
  libs/examples/src/cta-card/cta-card-default-example/cta-card-default-example.html
  libs/examples/src/empty-state/empty-state-default-example/empty-state-default-example.html
  libs/examples/src/empty-state/empty-state-in-card-example/empty-state-in-card-example.html
  libs/examples/src/empty-state/empty-state-multiple-items-example/empty-state-multiple-items-example.html
  libs/examples/src/empty-state/empty-state-multiple-items-in-card-example/empty-state-multiple-items-in-card-example.html
  libs/examples/src/icon/async-icon.ts
  libs/examples/src/icon/icon-all-example/async-icon.html
  libs/examples/src/icon/icon-all-example/async-icon.scss
  libs/examples/src/icon/icon-examples.module.ts
  libs/tools/shareable-examples/jest.config.js
  libs/tools/shareable-examples/src/generate-project.ts
  libs/tools/shareable-examples/src/templates/package-shareable-example.json.template
  libs/tools/shareable-examples/src/utils/get-relative-imports-from-source-file.ts
Labels: pr: merge-ready, target: minor, target: patch

#721 ci: Added a release promotion reminder
  .github/workflows/slack-barista-production-promotion.yml
Labels: pr: merge-ready, target: minor, target: patch

#716 barista: Modifying overlay rule for avoiding conflicts with CDK's.
  libs/barista-components/event-chart/src/event-chart.scss
Labels: pr: needs-cherry-pick

#704 fix(sidenav): Fixes wrong exportAs property for the sidenav-header
  libs/barista-components/drawer/src/sidenav.ts
Labels: pr: merge-ready, target: major

#724 barista: Remove flat white from the icon color wheel.
  apps/barista-design-system/src/components/icon-color-wheel/icon-color-wheel.ts
  libs/barista-components/core/src/style/_colors.scss
  libs/barista-components/theming/src/colors.ts
Labels: pr: merge-ready, target: minor, target: patch

#735 Fixes SideNav height bug when its content is smaller than view
  libs/barista-components/drawer/src/sidenav.scss
Labels: bug, pr: merge-ready, target: minor, target: patch

#711 barista: Insert internal content when not wrapped in tags and add tests.
  libs/tools/barista/src/transform.spec.ts
  libs/tools/barista/src/transform.ts
Labels: pr: merge-ready, target: minor, target: patch

#460 feat(duration-formatter): Adds dtDuration pipe to format time durations
  apps/dev/src/formatters/formatters-demo.component.html
  libs/barista-components/formatters/README.md
  libs/barista-components/formatters/index.ts
  libs/barista-components/formatters/src/duration/duration-formatter-constants.ts
  libs/barista-components/formatters/src/duration/duration-formatter-utils/convert-to-milliseconds.ts
  libs/barista-components/formatters/src/duration/duration-formatter-utils/index.ts
  libs/barista-components/formatters/src/duration/duration-formatter-utils/transform-result-precise.ts
  libs/barista-components/formatters/src/duration/duration-formatter-utils/transform-result.ts
  libs/barista-components/formatters/src/duration/duration-formatter.ts
  libs/barista-components/formatters/src/duration/duration-functions-tests/convert-to-milliseconds.spec.ts
  libs/barista-components/formatters/src/duration/duration-functions-tests/transform-result-precise.spec.ts
  libs/barista-components/formatters/src/duration/duration-functions-tests/transform-result.spec.ts
  libs/barista-components/formatters/src/duration/duration.spec.ts
  libs/barista-components/formatters/src/duration/duration.ts
  libs/barista-components/formatters/src/formatted-value.ts
  libs/barista-components/formatters/src/formatters-module.ts
  libs/barista-components/formatters/src/rate/rate-formatter.ts
  libs/examples/src/formatters/formatters-duration-example/formatters-duration-example.html
  libs/examples/src/formatters/formatters-duration-example/formatters-duration-example.ts
  libs/examples/src/formatters/formatters-examples.module.ts
Labels: pr: merge-ready, target: minor

#749 chore: Ignore yargs snyk
  .snyk
Labels: pr: merge-ready, target: minor, target: patch

#754 chore: Upgrade tslint and tslint-plugin-prettier dependencies to work together
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#758 barista: Add components to barrel file
  libs/examples/src/alert/index.ts
  libs/examples/src/autocomplete/index.ts
  libs/examples/src/bar-indicator/index.ts
  libs/examples/src/breadcrumbs/index.ts
  libs/examples/src/button-group/index.ts
  libs/examples/src/button/index.ts
  libs/examples/src/card/index.ts
  libs/examples/src/chart/index.ts
  libs/examples/src/checkbox/index.ts
  libs/examples/src/confirmation-dialog/index.ts
  libs/examples/src/consumption/index.ts
  libs/examples/src/container-breakpoint-observer/index.ts
  libs/examples/src/context-dialog/index.ts
  libs/examples/src/copy-to-clipboard/index.ts
  libs/examples/src/cta-card/index.ts
  libs/examples/src/drawer/index.ts
  libs/examples/src/empty-state/index.ts
  libs/examples/src/event-chart/index.ts
  libs/examples/src/expandable-panel/index.ts
  libs/examples/src/expandable-section/index.ts
  libs/examples/src/expandable-text/index.ts
  libs/examples/src/filter-field/index.ts
  libs/examples/src/form-field/index.ts
  libs/examples/src/formatters/index.ts
  libs/examples/src/highlight/index.ts
  libs/examples/src/icon/index.ts
  libs/examples/src/index.ts
  libs/examples/src/info-group/index.ts
  libs/examples/src/inline-editor/index.ts
  libs/examples/src/input/index.ts
  libs/examples/src/key-value-list/index.ts
  libs/examples/src/legend/index.ts
  libs/examples/src/link/index.ts
  libs/examples/src/loading-distractor/index.ts
  libs/examples/src/menu/index.ts
  libs/examples/src/micro-chart/index.ts
  libs/examples/src/overlay/index.ts
  libs/examples/src/pagination/index.ts
  libs/examples/src/progress-bar/index.ts
  libs/examples/src/progress-circle/index.ts
  libs/examples/src/radial-chart/index.ts
  libs/examples/src/radio/index.ts
  libs/examples/src/secondary-nav/index.ts
  libs/examples/src/select/index.ts
  libs/examples/src/show-more/index.ts
  libs/examples/src/sidenav/index.ts
  libs/examples/src/stepper/index.ts
  libs/examples/src/switch/index.ts
  libs/examples/src/table/index.ts
  libs/examples/src/tabs/index.ts
  libs/examples/src/tag/index.ts
  libs/examples/src/tile/index.ts
  libs/examples/src/timeline-chart/index.ts
  libs/examples/src/toast/index.ts
  libs/examples/src/toggle-button-group/index.ts
  libs/examples/src/top-bar-navigation/index.ts
  libs/examples/src/tree-table/index.ts
Labels: pr: merge-ready, target: minor, target: patch

#753 Barista/contributor images
  apps/barista-design-system/src/pages/single-page/components/contributors/contributors.html
  apps/barista-design-system/src/pages/single-page/components/contributors/contributors.ts
Labels: pr: merge-ready, target: minor, target: patch

#759 Fixes an issue where the live examples where not rendered in AOT
  .github/workflows/barista-preview.yml
  apps/barista-design-system/src/components/live-example/live-example.ts
  now-preview.json
Labels: pr: merge-ready, target: minor, target: patch

#762 barista: Fixes an outdated link in the footer
  apps/barista-design-system/src/app/components/footer/footer.html
Labels: pr: merge-ready, target: minor, target: patch

#767 barista: Fix links to recently visited pages.
  apps/barista-design-system/src/shared/services/recently-ordered.service.ts
Labels: pr: merge-ready, target: minor, target: patch

#757 chore: Removed my code ownership.
  .github/CODEOWNERS
  libs/barista-components/alert/barista.json
  libs/barista-components/card/barista.json
  libs/barista-components/expandable-panel/barista.json
  libs/barista-components/expandable-section/barista.json
  libs/barista-components/info-group/barista.json
  libs/barista-components/radial-chart/barista.json
  libs/barista-components/show-more/barista.json
  libs/barista-components/switch/barista.json
  libs/barista-components/table/barista.json
  libs/barista-components/tile/barista.json
Labels: pr: merge-ready, target: minor, target: patch

#730 Deprecate Time-Formatter
  libs/barista-components/formatters/README.md
  libs/barista-components/formatters/index.ts
  libs/barista-components/formatters/src/formatters-module.ts
  libs/barista-components/formatters/src/time-deprecated/time-formatter.ts
  libs/barista-components/formatters/src/time-deprecated/time.spec.ts
  libs/barista-components/formatters/src/time-deprecated/time.ts
Labels: pr: merge-ready, target: minor

#763 barista: Replace clipboard service with CDK clipboard.
  apps/barista-design-system/src/components/color-component/color.ts
  apps/barista-design-system/src/components/components.module.ts
  apps/barista-design-system/src/components/headline-link/headline-link.ts
  apps/barista-design-system/src/components/live-example/live-example.ts
  apps/barista-design-system/src/shared/services/copy-to-clipboard.service.spec.ts
  apps/barista-design-system/src/shared/services/copy-to-clipboard.service.ts
Labels: design-system, pr: merge-ready, target: minor, target: patch

#773 barista: Fixes an issue where the tables example was missing.
  apps/barista-design-system/src/components/live-example/live-example.ts
Labels: design-system, pr: merge-ready, target: minor, target: patch

#775 chore: Update code owners for alert component.
  .github/CODEOWNERS
  libs/barista-components/alert/barista.json
Labels: pr: merge-ready, target: minor, target: patch

#787 fix(filter-field): Fixes an issue with the free-text submission.
  apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#784 fix(top-bar-navigation): Highlight top bar actions with keyboard focus.
  libs/barista-components/top-bar-navigation/src/top-bar-navigation.scss
  libs/barista-components/top-bar-navigation/src/top-bar-navigation.spec.ts
  libs/barista-components/top-bar-navigation/src/top-bar-navigation.ts
Labels: pr: needs-cherry-pick

#783 Fixes an issue where the task runner was failing with the affected commands.
  angular.json
  libs/barista-components/schematics/src/ng-add/__snapshots__/ng-add.spec.ts.snap
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#746 Copy to clipboard: move to CDK instead of current API
  libs/barista-components/copy-to-clipboard/src/copy-to-clipboard-module.ts
  libs/barista-components/copy-to-clipboard/src/copy-to-clipboard.html
  libs/barista-components/copy-to-clipboard/src/copy-to-clipboard.ts
Labels: pr: merge-ready, target: minor, target: patch

#761 barista: Use images instead of inline svgs for icons.
  apps/barista-design-system/src/app/app.html
  apps/barista-design-system/src/app/components/footer/footer.html
  apps/barista-design-system/src/app/components/scroll-to-top/scroll-to-top.html
  apps/barista-design-system/src/app/components/scroll-to-top/scroll-to-top.scss
  apps/barista-design-system/src/assets/arrow-up-white.svg
  apps/barista-design-system/src/assets/behance-white.svg
  apps/barista-design-system/src/assets/dribbble-white.svg
  apps/barista-design-system/src/assets/favorite-white.svg
  apps/barista-design-system/src/assets/github-white.svg
  apps/barista-design-system/src/assets/incident-white.svg
  apps/barista-design-system/src/assets/laboratory-white.svg
  apps/barista-design-system/src/assets/list-view.svg
  apps/barista-design-system/src/assets/maintenance-royalblue.svg
  apps/barista-design-system/src/assets/tile-view.svg
  apps/barista-design-system/src/pages/overview-page/components/tile/tile.html
  apps/barista-design-system/src/pages/overview-page/components/tile/tile.scss
  apps/barista-design-system/src/pages/overview-page/overview-page.html
  apps/barista-design-system/src/pages/overview-page/overview-page.scss
  apps/barista-design-system/src/pages/single-page/components/icon-overview-content/icon-overview-content.ts
Labels: design-system, pr: merge-ready, target: minor, target: patch

#794 barista: Simplify breadcrumbs creation.
  apps/barista-design-system/src/app/app.ts
Labels: pr: merge-ready, target: minor, target: patch

#782 chore: browserslist update
  package.json
Labels: pr: needs-cherry-pick

#797 barista: Fixes an issue where not all fills were removed from icon strings.
  libs/tools/barista/src/builder/icons.ts
Labels: design-system, pr: merge-ready, target: minor, target: patch

#778 Build/create docker build image
  .circleci/config.yml
  .dockerignore
  Dockerfile
  entrypoint.sh
Labels: pr: merge-ready, target: minor, target: patch

#806 fix(copy-to-clipboard): Fixes an issue where copied text is undefined
  libs/barista-components/copy-to-clipboard/src/copy-to-clipboard.ts
Labels: bug, pr: merge-ready, target: minor, target: patch

#594 feat(chart): Add animation for chart heatfield.
  apps/dev/src/chart/chart-demo.component.html
  libs/barista-components/chart/src/heatfield/chart-heatfield-config.ts
  libs/barista-components/chart/src/heatfield/chart-heatfield.html
  libs/barista-components/chart/src/heatfield/chart-heatfield.scss
  libs/barista-components/chart/src/heatfield/chart-heatfield.spec.ts
  libs/barista-components/chart/src/heatfield/chart-heatfield.ts
  libs/barista-components/core/src/animations/fade-animation.ts
  libs/barista-components/core/src/animations/index.ts
Labels: feature, pr: needs-cherry-pick

#804 Expandable-text: Set default background
  libs/barista-components/expandable-text/src/expandable-text.scss
Labels: pr: merge-ready, target: minor, target: patch

#803 Overlay: Fix mousemove
  libs/barista-components/overlay/src/mouse-follow-position-strategy.ts
  libs/barista-components/overlay/src/overlay-ref.ts
  libs/barista-components/overlay/src/overlay-trigger.ts
  libs/barista-components/overlay/src/overlay.ts
Labels: pr: merge-ready, target: minor, target: patch
