Repository dynatrace-oss/barista, pull requests merged in 2020-07, with the labels that each got.

#1195 chore: Upgrade angular and nrwl dependencies
  angular.json
  libs/barista-components/schematics/src/ng-add/__snapshots__/ng-add.spec.ts.snap
  libs/fluid-elements/jest.config.js
  libs/testing/custom-element/jest.config.js
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#1214 chore: Update shareable examples packages.
  libs/tools/shareable-examples/src/templates/package-shareable-example.json.template
Labels: pr: merge-ready, target: minor, target: patch

#1199 chore: Added tailwind output to design tokens generation.
  angular.json
  libs/workspace/builders.json
  libs/workspace/src/builders/design-tokens/package/build.ts
  libs/workspace/src/builders/design-tokens/tailwindcss/build.ts
  libs/workspace/src/builders/design-tokens/tailwindcss/index.ts
  libs/workspace/src/builders/design-tokens/tailwindcss/schema.json
  libs/workspace/src/builders/design-tokens/tailwindcss/schema.ts
  libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-color-group-config.ts
  libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-font-config.ts
  libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-spacing-config.ts
  libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-tailwind-config.ts
  libs/workspace/webpack.config.js
  package-lock.json
  package.json
Labels: next, pr: merge-ready, target: minor, target: patch

#1218 chore(snyk): Remove outdated snyk ignores and extend lodash ignore
  .snyk
Labels: pr: merge-ready, target: minor, target: patch

#1216 chore(README): Fixes an outdated link
  README.md
Labels: pr: merge-ready, target: minor, target: patch

#1220 chore: Fixes an issue with the tailwind config generation.
  libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-color-group-config.spec.ts
  libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-color-group-config.ts
  libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-font-config.spec.ts
  libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-font-config.ts
  libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-spacing-config.spec.ts
Labels: pr: merge-ready, target: minor, target: patch

#1224 chore: Add ds commit type for the design system
  CONTRIBUTING.md
  tools/pull-request-labeler/src/interfaces/commit-message.ts
  tools/pull-request-labeler/src/utils/process-commit-messages.spec.ts
Labels: pr: merge-ready, target: minor, target: patch

#1221 barista: Fixes an issue with the TOC not being generated on strapi-only pages.
  apps/barista-design-system/src/shared/services/scroll-spy.service.ts
  libs/tools/barista/src/builder/strapi.ts
Labels: pr: merge-ready, target: minor, target: patch

#1228 barista: Fixes an issue in the publish script.
  .deployment/barista/Jenkinsfile
  .deployment/barista/nginx/sites-available/barista-internal.conf
Labels: pr: merge-ready, target: minor, target: patch

#1116 feat(schematics): Add example component generation.
  libs/workspace/collection.json
  libs/workspace/src/schematics/dt-component-example/README.md
  libs/workspace/src/schematics/dt-component-example/__snapshots__/index.spec.ts.snap
  libs/workspace/src/schematics/dt-component-example/files/__component@dasherize__-__name@dasherize__-example.html
  libs/workspace/src/schematics/dt-component-example/files/__component@dasherize__-__name@dasherize__-example.ts
  libs/workspace/src/schematics/dt-component-example/fixtures/index.ts.fixture
  libs/workspace/src/schematics/dt-component-example/fixtures/test-component-examples.module.ts.fixture
  libs/workspace/src/schematics/dt-component-example/index.spec.ts
  libs/workspace/src/schematics/dt-component-example/index.ts
  libs/workspace/src/schematics/dt-component-example/schema.json
  libs/workspace/src/schematics/dt-component-example/schema.ts
  libs/workspace/src/utils/common-utils.ts
  libs/workspace/webpack.config.js
Labels: pr: merge-ready, target: minor

#1233 chore: Fixes nginx routing for the design-system app.
  .deployment/barista/Jenkinsfile
  .deployment/barista/nginx/sites-available/barista-internal.conf
Labels: pr: merge-ready, target: minor, target: patch

#1239 chore: Fixes an issue where tags were not defined for affected e2e.
  libs/workspace/src/builders/affected-e2e/build.ts
Labels: pr: merge-ready, target: minor, target: patch

#1232 style(confirmation-dialog) add top margin for .dt-confirmation-dialog-actions
  libs/barista-components/confirmation-dialog/src/confirmation-dialog-state/confirmation-dialog-state.scss
Labels: pr: merge-ready, target: minor, target: patch

#1189 feat(sunburst-chart): Add ariaLabel and responsiveness
  .github/CODEOWNERS
  apps/components-e2e/src/components/sunburst-chart/sunburst-chart.e2e.ts
  apps/components-e2e/src/components/sunburst-chart/sunburst-chart.po.ts
  apps/dev/src/sunburst-chart/sunburst-chart-demo.component.html
  apps/dev/src/sunburst-chart/sunburst-chart-demo.component.ts
  libs/barista-components/sunburst-chart/README.md
  libs/barista-components/sunburst-chart/barista.json
  libs/barista-components/sunburst-chart/src/sunburst-chart-segment.html
  libs/barista-components/sunburst-chart/src/sunburst-chart-segment.scss
  libs/barista-components/sunburst-chart/src/sunburst-chart-segment.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.html
  libs/barista-components/sunburst-chart/src/sunburst-chart.module.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.scss
  libs/barista-components/sunburst-chart/src/sunburst-chart.spec.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.util.spec.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.util.ts
Labels: pr: merge-ready, pr: needs-cherry-pick, target: minor

#1247 ds: Fix baseHref for next apps
  .deployment/barista/Jenkinsfile
  angular.json
  apps/next/src/app/app.module.ts
  libs/shared/data-access-strapi/src/lib/page.service.ts
Labels: pr: merge-ready, target: minor, target: patch

#1241 chore: Update dependency to barista icons to ^7.3
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#1249 chore: Fix package to lock file inconsistencies.
  package-lock.json
Labels: pr: merge-ready, target: minor, target: patch

#1255 chore: Correct e2e test command to be runnable without CIRCLECI token
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#1263 ci: Fix failing stylelint and workspace lint
  libs/design-tokens-ui/input/BUILD.bazel
  libs/design-tokens-ui/style/BUILD.bazel
  package-lock.json
Labels: pr: merge-ready, target: minor, target: patch

#1260 fix(stacked-series-chart): Sanitize axis ticks position
  libs/barista-components/stacked-series-chart/src/stacked-series-chart-bar.scss
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.html
Labels: pr: merge-ready, pr: needs-cherry-pick, target: minor, target: patch

#1248 ds: Fixes an issue with missing table styling.
  apps/barista-design-system/src/styles/global/_base.scss
Labels: pr: merge-ready, target: minor, target: patch

#1266 chore(ci): Parameterize Bazel version
  .circleci/config.yml
  .deployment/workspace-bazel.Dockerfile
  package-lock.json
  tools/bazel_build_cache/setup_ci_build_cache.sh
Labels: pr: merge-ready, target: minor, target: patch

#1269 chore: Finally fix the routing for next
  .dockerignore
  angular.json
  apps/next/src/app/app.module.ts
  apps/next/src/environments/environment.prod.ts
  apps/next/src/environments/environment.ts
Labels: pr: merge-ready, target: minor, target: patch

#1261 chore(checkbox): Added custom property proxies.
  libs/fluid-elements/checkbox/README.md
  libs/fluid-elements/checkbox/src/lib/checkbox.scss
  libs/fluid-elements/checkbox/src/lib/checkbox.ts
Labels: pr: merge-ready, target: minor, target: patch

#1271 docs: Prettify the title of the stacked series chart.
  libs/barista-components/stacked-series-chart/barista.json
Labels: pr: merge-ready, target: minor, target: patch

#1253 fix(filter-field): Fixes an issue with validation flickering on free text.
  libs/barista-components/filter-field/src/filter-field-validation.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#1265 chore: Update design tokens and tailwind config.
  libs/shared/design-tokens/generated/aliases/palette-source.alias.json
  libs/shared/design-tokens/generated/aliases/palette.alias.json
  libs/shared/design-tokens/generated/global/palette.json
  libs/shared/design-tokens/generated/global/palette.scss
  libs/shared/design-tokens/generated/global/palette.ts
  libs/shared/design-tokens/generated/global/theme.json
  libs/shared/design-tokens/generated/global/theme.scss
  libs/shared/design-tokens/generated/global/theme.ts
  libs/shared/design-tokens/generated/global/typography.json
  libs/shared/design-tokens/generated/patterns/button.json
  libs/shared/design-tokens/src/lib/aliases/palette-source.alias.yml
  libs/shared/design-tokens/src/lib/aliases/palette.alias.yml
  libs/workspace/src/builders/design-tokens/tailwindcss/utils/generate-tailwind-config.ts
Labels: pr: merge-ready, target: minor, target: patch

#1277 fix(radio): Fixes an issue where the radio-group interfered with other groups.
  libs/barista-components/radio/src/radio-group.ts
  libs/barista-components/radio/src/radio.spec.ts
  libs/barista-components/radio/src/radio.ts
Labels: pr: merge-ready, target: minor, target: patch

#1289 fix(combobox): Fixes an issue with setting the value not updating the…
  libs/barista-components/experimental/combobox/src/combobox.spec.ts
  libs/barista-components/experimental/combobox/src/combobox.ts
Labels: pr: merge-ready, target: minor, target: patch

#1275 [table] limit dtIndicator styles inheritance
  libs/barista-components/table/src/expandable/_expandable-row-theme.scss
  libs/barista-components/table/src/expandable/expandable-row.scss
Labels: bug, pr: needs-cherry-pick, target: minor, target: patch

#1288 fix(sunburst-chart): Fixes an issue with missing types dependency.
  libs/barista-components/sunburst-chart/src/sunburst-chart.util.ts
Labels: pr: merge-ready, target: minor, target: patch

#1267 fix(filter-field): Fixes an issue with the infix when deleting a filter while in flight.
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#1286 feat(progress-bar): Switched theming to custom properties.
  libs/barista-components/progress-bar/src/_progress-bar-theme.scss
  libs/barista-components/progress-bar/src/progress-bar.scss
  libs/barista-components/style/themes.scss
Labels: pr: merge-ready, target: minor

#1285 barista: Removes the deprecated search-page
  apps/barista-design-system/src/pages/.search-page/components/search/index.ts
  apps/barista-design-system/src/pages/.search-page/components/search/search.html
  apps/barista-design-system/src/pages/.search-page/components/search/search.scss
  apps/barista-design-system/src/pages/.search-page/components/search/search.ts
  apps/barista-design-system/src/pages/.search-page/search-page.html
  apps/barista-design-system/src/pages/.search-page/search-page.module.ts
  apps/barista-design-system/src/pages/.search-page/search-page.scss
  apps/barista-design-system/src/pages/.search-page/search-page.ts
Labels: pr: merge-ready, target: minor, target: patch

#1279 Design Systems: refactor shared things
  apps/barista-design-system/src/app/app.module.ts
  apps/barista-design-system/src/app/app.ts
  apps/barista-design-system/src/app/components/nav/nav.ts
  apps/barista-design-system/src/pages/decision-graph-page/components/ba-decision-graph/ba-decision-graph.module.ts
  apps/barista-design-system/src/pages/decision-graph-page/components/ba-decision-graph/ba-decision-graph.spec.ts
  apps/barista-design-system/src/pages/decision-graph-page/components/ba-decision-graph/ba-decision-graph.ts
  apps/barista-design-system/src/pages/decision-graph-page/decision-graph-page.module.ts
  apps/barista-design-system/src/pages/decision-graph-page/decision-graph-page.ts
  apps/barista-design-system/src/pages/error-page/error-page.ts
  apps/barista-design-system/src/pages/index-page/index-page.module.ts
  apps/barista-design-system/src/pages/index-page/index-page.ts
  apps/barista-design-system/src/pages/overview-page/overview-page.module.ts
  apps/barista-design-system/src/pages/overview-page/overview-page.ts
  apps/barista-design-system/src/pages/single-page/single-page.module.ts
  apps/barista-design-system/src/pages/single-page/single-page.ts
  apps/next/src/app/app.component.scss
  apps/next/src/app/app.module.ts
  apps/next/src/app/app.routing.module.ts
  apps/next/src/app/components/nav/nav.scss
  apps/next/src/app/pages/error-page/error-page.html
  apps/next/src/app/pages/error-page/error-page.module.ts
  apps/next/src/app/pages/error-page/error-page.ts
  apps/next/src/app/pages/index-page/index-page.html
  apps/next/src/app/pages/index-page/index-page.module.ts
  apps/next/src/app/pages/index-page/index-page.ts
  apps/next/src/app/pages/single-page/single-page.module.ts
  apps/next/src/app/pages/single-page/single-page.ts
  apps/next/src/app/styles/_page.scss
  apps/next/src/styles.scss
  libs/shared/data-access-strapi/src/lib/page-guard.ts
  libs/shared/data-access-strapi/src/lib/page.service.ts
  libs/shared/design-system/interfaces/src/lib/next-definitions.ts
Labels: pr: merge-ready, target: minor, target: patch

#1272 feat(tile): Switched theming to custom properties.
  libs/barista-components/tile/src/_tile-theme.scss
  libs/barista-components/tile/src/tile.scss
Labels: pr: needs-cherry-pick, target: minor, target: patch

#1303 Fluid checkbox prevent scroll
  apps/fluid-dev/src/pages/checkbox/checkbox-page.component.html
  libs/fluid-elements/checkbox/src/lib/checkbox.spec.ts
  libs/fluid-elements/checkbox/src/lib/checkbox.ts
Labels: pr: merge-ready, target: minor, target: patch

#1306 chore: Package.json versions for shareable examples are now in sync.
  libs/tools/shareable-examples/src/templates/package-shareable-example.json.template
  libs/tools/shareable-examples/src/utils/get-boilerplate-files.ts
Labels: pr: merge-ready, target: minor, target: patch

#1292 style(select): Fixes border issue when select is used inside form-field
  libs/barista-components/select/src/select.scss
Labels: pr: needs-cherry-pick, target: minor, target: patch

#1295 style: Unifying placeholder color for input, select and combobox
  libs/barista-components/core/src/style/_form-control.scss
  libs/barista-components/core/src/style/_variables.scss
  libs/barista-components/experimental/combobox/src/combobox.scss
  libs/barista-components/input/src/input.scss
  libs/barista-components/select/src/select.scss
Labels: pr: needs-cherry-pick, target: minor, target: patch

#1243 Extend examples with tools
  .circleci/config.yml
  .deployment/barista/Jenkinsfile
  .github/workflows/barista-preview.yml
  .gitignore
  angular.json
  apps/demos/src/app-routing.module.template
  apps/demos/src/app-routing.module.ts
  apps/demos/src/nav-items.template
  apps/demos/src/nav-items.ts
  libs/tools/barista/src/main.ts
  libs/tools/barista/src/utils/examples.ts
  libs/tools/barista/src/utils/metadata.ts
  libs/tools/examples-tools/README.md
  libs/tools/examples-tools/src/generate-examples-lib-barrel.ts
  libs/tools/examples-tools/src/generate-examples-lib-module.ts
  libs/tools/examples-tools/src/generate-nav-items.ts
  libs/tools/examples-tools/src/generate-routing-module.ts
  libs/tools/examples-tools/src/main.ts
  libs/tools/examples-tools/src/util.ts
  libs/tools/examples-tools/tsconfig.json
  libs/tools/examples-tools/tslint.json
  libs/workspace/src/schematics/dt-component-example/__snapshots__/index.spec.ts.snap
  libs/workspace/src/schematics/dt-component-example/example-tools.utils.ts
  libs/workspace/src/schematics/dt-component-example/fixtures/app-routing.module.ts.fixture
  libs/workspace/src/schematics/dt-component-example/fixtures/examples.module.ts.fixture
  libs/workspace/src/schematics/dt-component-example/fixtures/examplesIndex.ts.fixtures
  libs/workspace/src/schematics/dt-component-example/fixtures/nav-items.ts.fixture
  libs/workspace/src/schematics/dt-component-example/index.spec.ts
  libs/workspace/src/schematics/dt-component-example/index.ts
  libs/workspace/src/schematics/utils/ast-utils.ts
  nx.json
  package.json
Labels: pr: merge-ready, target: minor

#1302 fix(filter-field): Fixes an issue with the error validation when trying to submit an empty value.
  apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#1301 feat(formatters): Added maxPrecision parameter to count formatters to…
  libs/barista-components/formatters/README.md
  libs/barista-components/formatters/src/count/count-formatter.ts
  libs/barista-components/formatters/src/count/count.spec.ts
  libs/barista-components/formatters/src/count/count.ts
  libs/barista-components/formatters/src/number-formatter.spec.ts
  libs/barista-components/formatters/src/number-formatter.ts
Labels: pr: merge-ready, pr: needs-cherry-pick, target: minor

#1313 chore(next): Cleans up deps for next and fluid-dev
  apps/next/src/app/pages/error-page/error-page.module.ts
  apps/next/src/app/pages/index-page/index-page.module.ts
  nx.json
Labels: pr: merge-ready, target: minor, target: patch

#1294 style(input): Fixes extra outlines when places inside form-field
  apps/dev/src/form-field/form-field-demo.component.html
  apps/dev/src/form-field/form-field-demo.component.scss
  apps/dev/src/input/input-demo.component.html
  apps/dev/src/select/select-demo.component.html
  libs/barista-components/core/src/style/_interactive-common.scss
  libs/barista-components/form-field/src/form-field.scss
Labels: pr: needs-cherry-pick, target: minor, target: patch

#1310 chore(bazel): Bazelify Bar-Indicator
  angular.json
  libs/barista-components/bar-indicator/BUILD.bazel
  libs/barista-components/bar-indicator/jest.config.js
  libs/barista-components/bar-indicator/jest.config.json
  libs/barista-components/bar-indicator/tsconfig.json
  libs/barista-components/bar-indicator/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1309 chore(bazel): Bazelify Breadcrumbs
  angular.json
  libs/barista-components/breadcrumbs/BUILD.bazel
  libs/barista-components/breadcrumbs/jest.config.js
  libs/barista-components/breadcrumbs/jest.config.json
  libs/barista-components/breadcrumbs/tsconfig.json
  libs/barista-components/breadcrumbs/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1308 chore(bazel): Bazelify Button Group
  angular.json
  libs/barista-components/button-group/BUILD.bazel
  libs/barista-components/button-group/jest.config.js
  libs/barista-components/button-group/jest.config.json
  libs/barista-components/button-group/tsconfig.json
  libs/barista-components/button-group/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1300 chore(switch): Implementation of the fluid switch component.
  angular.json
  apps/fluid-dev/src/app/app.component.html
  apps/fluid-dev/src/app/app.routing.module.ts
  apps/fluid-dev/src/pages/switch/switch-page.component.html
  apps/fluid-dev/src/pages/switch/switch-page.component.scss
  apps/fluid-dev/src/pages/switch/switch-page.component.ts
  apps/fluid-dev/src/pages/switch/switch-page.module.ts
  libs/fluid-elements/switch/.stylelintrc
  libs/fluid-elements/switch/jest.config.js
  libs/fluid-elements/switch/src/index.ts
  libs/fluid-elements/switch/src/lib/switch-events.ts
  libs/fluid-elements/switch/src/lib/switch.scss
  libs/fluid-elements/switch/src/lib/switch.spec.ts
  libs/fluid-elements/switch/src/lib/switch.ts
  libs/fluid-elements/switch/tsconfig.json
  libs/fluid-elements/switch/tsconfig.lib.json
  libs/fluid-elements/switch/tsconfig.spec.json
  libs/fluid-elements/switch/tslint.json
  nx.json
  tsconfig.json
Labels: pr: merge-ready, target: minor, target: patch

#1307 chore(bazel): Bazelify Card
  angular.json
  libs/barista-components/card/BUILD.bazel
  libs/barista-components/card/jest.config.js
  libs/barista-components/card/jest.config.json
  libs/barista-components/card/tsconfig.json
  libs/barista-components/card/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1311 chore(bazel): Bazelify Autocomplete and its dependencies
  angular.json
  libs/barista-components/autocomplete/BUILD.bazel
  libs/barista-components/autocomplete/jest.config.js
  libs/barista-components/autocomplete/jest.config.json
  libs/barista-components/autocomplete/tsconfig.json
  libs/barista-components/autocomplete/tsconfig.lib.json
  libs/barista-components/form-field/BUILD.bazel
  libs/barista-components/form-field/jest.config.json
  libs/barista-components/form-field/src/test-setup.ts
  libs/barista-components/form-field/tsconfig.json
  libs/barista-components/form-field/tsconfig.lib.json
  libs/barista-components/form-field/tsconfig.spec.json
  libs/barista-components/input/BUILD.bazel
  libs/barista-components/input/jest.config.js
  libs/barista-components/input/jest.config.json
  libs/barista-components/input/tsconfig.json
  libs/barista-components/input/tsconfig.lib.json
  libs/barista-components/style/BUILD.bazel
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1312 chore(bazel): Bazelify Alert Component
  angular.json
  libs/barista-components/alert/BUILD.bazel
  libs/barista-components/alert/jest.config.js
  libs/barista-components/alert/jest.config.json
  libs/barista-components/alert/tsconfig.json
  libs/barista-components/alert/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1323 chore(bazel): Bazelify theming library
  angular.json
  libs/barista-components/theming/BUILD.bazel
  libs/barista-components/theming/jest.config.js
  libs/barista-components/theming/jest.config.json
  libs/barista-components/theming/tsconfig.json
  libs/barista-components/theming/tsconfig.lib.json
  tools/bazel_rules/ng_module_macro.bzl
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1320 ci(bazel): Bazelify tile component.
  angular.json
  libs/barista-components/tile/BUILD.bazel
  libs/barista-components/tile/jest.config.js
  libs/barista-components/tile/jest.config.json
  libs/barista-components/tile/src/chart-colors.ts
  libs/barista-components/tile/tsconfig.json
  libs/barista-components/tile/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1317 fix(filter-field): Fixes an issue where the range stayed open when datasource updated.
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#1334 chore(bazel): Bazelify tabs.
  angular.json
  libs/barista-components/tabs/BUILD.bazel
  libs/barista-components/tabs/jest.config.js
  libs/barista-components/tabs/jest.config.json
  libs/barista-components/tabs/tsconfig.json
  libs/barista-components/tabs/tsconfig.lib.json
  tools/bazel_rules/jest/jest-resolver.js
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1337 chore(bazel): Bazelify key-value-list
  angular.json
  libs/barista-components/key-value-list/BUILD.bazel
  libs/barista-components/key-value-list/jest.config.js
  libs/barista-components/key-value-list/jest.config.json
  libs/barista-components/key-value-list/tsconfig.json
  libs/barista-components/key-value-list/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1341 chore(bazel): Bazelify formatters.
  angular.json
  libs/barista-components/formatters/BUILD.bazel
  libs/barista-components/formatters/jest.config.js
  libs/barista-components/formatters/jest.config.json
  libs/barista-components/formatters/src/date/date-range.spec.ts
  libs/barista-components/formatters/tsconfig.json
  libs/barista-components/formatters/tsconfig.lib.json
  tools/bazel_rules/jest/jest_macro.bzl
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1338 chore(bazel): Bazelify overlay component.
  angular.json
  libs/barista-components/overlay/BUILD.bazel
  libs/barista-components/overlay/jest.config.js
  libs/barista-components/overlay/jest.config.json
  libs/barista-components/overlay/tsconfig.json
  libs/barista-components/overlay/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1344 build(e2e): Fixes an issue where the affected-e2e failed, when no components were affected.
  libs/workspace/src/builders/affected-e2e/build.ts
Labels: pr: merge-ready, target: minor, target: patch

#1316 chore(transformer): Adds transformation step adding classes to headlines
  libs/tools/barista/src/builder/strapi.ts
  libs/tools/barista/src/transform.spec.ts
  libs/tools/barista/src/transform.ts
Labels: pr: merge-ready, target: minor, target: patch

#1345 chore(bazel): Bazelify loading distractor.
  angular.json
  libs/barista-components/loading-distractor/BUILD.bazel
  libs/barista-components/loading-distractor/jest.config.js
  libs/barista-components/loading-distractor/jest.config.json
  libs/barista-components/loading-distractor/tsconfig.json
  libs/barista-components/loading-distractor/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1343 ci(bazel): Add junit xml output for stylelint.
  apps/components-e2e/BUILD.bazel
  apps/fluid-dev/BUILD.bazel
  libs/examples/BUILD.bazel
  libs/fluid-elements/tab-group/BUILD.bazel
  tools/bazel_rules/index.bzl
  tools/bazel_rules/stylelint/BUILD.bazel
  tools/bazel_rules/stylelint/junit-formatter/index.ts
  tools/bazel_rules/stylelint/junit-formatter/junit-formatter.ts
  tools/bazel_rules/stylelint/junit-formatter/parse-suite.ts
  tools/bazel_rules/stylelint/junit-formatter/parsed-suite.interface.ts
  tools/bazel_rules/stylelint/run-stylelint.ts
  tools/bazel_rules/stylelint/stylelint_macro.bzl
  tools/bazel_rules/stylelint_macro.bzl
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1347 test(sunburst-chart): Fixes an issue with flaky tests on hover.
  apps/components-e2e/src/components/sunburst-chart/sunburst-chart.e2e.ts
  apps/components-e2e/src/components/sunburst-chart/sunburst-chart.html
  apps/components-e2e/src/components/sunburst-chart/sunburst-chart.po.ts
Labels: pr: merge-ready, target: minor, target: patch

#1325 chore(bazel): Bazelify tag component.
  angular.json
  libs/barista-components/tag/BUILD.bazel
  libs/barista-components/tag/jest.config.js
  libs/barista-components/tag/jest.config.json
  libs/barista-components/tag/tsconfig.json
  libs/barista-components/tag/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1278 Next(top-nav): Section generator
  apps/next/src/app/components/nav/nav.html
  apps/next/src/app/components/nav/nav.ts
  libs/shared/data-access-strapi/src/lib/page.service.ts
  libs/tools/barista/src/builder/strapi.ts
  libs/tools/barista/src/main.ts
  libs/tools/barista/src/types.ts
Labels: pr: merge-ready, target: minor, target: patch

#1348 ci(bazel): Fixes an issue on forked pull requrests.
  tools/bazel_build_cache/setup_ci_build_cache.sh
Labels: pr: merge-ready, target: minor, target: patch

#1355 ci(bazel): Fix build cache regex on ci.
  tools/bazel_build_cache/setup_ci_build_cache.sh
Labels: pr: merge-ready, target: minor, target: patch

#1356 fix(next): Fixes the page service import in the next apps nav component
  apps/next/src/app/components/nav/nav.ts
Labels: bug, next, pr: merge-ready, target: minor, target: patch

#1254 Next(content): Mock Overview content
  apps/next/src/app/pages/single-page/single-page.html
  apps/next/src/app/pages/single-page/single-page.module.ts
  apps/next/src/app/pages/single-page/single-page.scss
  apps/next/src/app/pages/single-page/single-page.ts
  apps/next/src/styles.scss
  apps/next/tsconfig.app.json
  nx.json
Labels: pr: merge-ready, target: minor, target: patch

#1274 feat(indicator): Switched theming to custom properties.
  libs/barista-components/indicator/src/indicator-theme.scss
  libs/barista-components/indicator/src/indicator.scss
Labels: pr: merge-ready, target: minor

#1342 chore: Extend demos sidebar filter to example-names and recovery of filtered key.
  apps/demos/src/side-nav.component.html
  apps/demos/src/side-nav.component.ts
Labels: pr: merge-ready, target: minor, target: patch

#1360 Fixes an issue that was introduced through rebase strategy
  libs/barista-components/indicator/BUILD.bazel
  libs/barista-components/style/BUILD.bazel
Labels: pr: merge-ready, target: minor, target: patch

#1350 Chore/fixes keyboard tests tab
  angular.json
  libs/fluid-elements/checkbox/src/lib/checkbox.spec.ts
  libs/fluid-elements/checkbox/src/lib/checkbox.ts
  libs/fluid-elements/checkbox/tsconfig.lib.json
  libs/fluid-elements/switch/src/lib/switch.spec.ts
  libs/fluid-elements/switch/src/lib/switch.ts
  libs/fluid-elements/switch/tsconfig.lib.json
  libs/fluid-elements/tab-group/src/lib/tab-group.spec.ts
  libs/fluid-elements/tab-group/src/lib/tab-group.ts
  libs/fluid-elements/tab-group/tsconfig.lib.json
  libs/shared/keycodes/README.md
  libs/shared/keycodes/src/index.ts
  libs/shared/keycodes/src/lib/keycodes.ts
  libs/shared/keycodes/tsconfig.json
  libs/shared/keycodes/tsconfig.lib.json
  libs/shared/keycodes/tslint.json
  libs/testing/browser/src/lib/dispatch-events.ts
  libs/testing/browser/src/lib/event-objects.ts
  nx.json
  tsconfig.json
Labels: pr: merge-ready, target: minor, target: patch

#1362 chore(ci): Change ownership of repocache folder to enable write acces…
  .deployment/workspace-bazel.Dockerfile
Labels: pr: merge-ready, target: minor, target: patch

#1361 chore(bazel): Update rules_nodejs to version 2.0.0
  WORKSPACE
  package-lock.json
  package.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1364 fix(quick-filter): Fixes an issue where an ECAC error was thrown.
  libs/barista-components/experimental/quick-filter/src/quick-filter.spec.ts
  libs/barista-components/experimental/quick-filter/src/quick-filter.ts
Labels: pr: merge-ready, target: minor, target: patch

#1369 ds: Fixes an issue with fetching categories.
  libs/tools/barista/src/builder/strapi.ts
Labels: pr: merge-ready, target: minor, target: patch

#1367 feat(radio): Switched theming to custom properties.
  libs/barista-components/radio/src/_radio-theme.scss
  libs/barista-components/radio/src/radio.scss
Labels: pr: merge-ready, target: minor

#1359 ci: Switch to large instead of x-large containers
  .circleci/config.yml
Labels: pr: merge-ready, target: minor, target: patch

#1370 ci(bazel): Changes shell command invocation to fix fork skip check fo…
  .circleci/bazel.rc
  .circleci/config.yml
  tools/bazel_build_cache/setup_ci_build_cache.sh
Labels: pr: needs-cherry-pick, target: minor, target: patch

#1336 Adds the value property to the checkboxes and a README to the switch webcomponent
  apps/fluid-dev/src/pages/checkbox/checkbox-page.component.html
  apps/fluid-dev/src/pages/switch/switch-page.component.html
  libs/fluid-elements/checkbox/README.md
  libs/fluid-elements/checkbox/src/lib/checkbox.spec.ts
  libs/fluid-elements/checkbox/src/lib/checkbox.ts
  libs/fluid-elements/switch/README.md
  libs/fluid-elements/switch/src/lib/switch.spec.ts
  libs/fluid-elements/switch/src/lib/switch.ts
Labels: next, pr: merge-ready, target: minor, target: patch

#1365 fix(container-breakdown-observer): Fixes an issue where query parsing…
  libs/barista-components/container-breakpoint-observer/src/query.spec.ts
  libs/barista-components/container-breakpoint-observer/src/query.ts
Labels: pr: needs-cherry-pick, target: minor, target: patch

#1351 barista: Modifying isChild condition for avoiding opening wrong nodes
  libs/barista-components/sunburst-chart/src/sunburst-chart.mock.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.util.spec.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.util.ts
Labels: pr: needs-cherry-pick, target: minor, target: patch

#1071 feat(checkbox-table): Add checkbox column and selection handling
  apps/dev/src/table/table-demo.component.html
  apps/dev/src/table/table-demo.component.ts
  libs/barista-components/checkbox/src/checkbox.ts
  libs/barista-components/table/README.md
  libs/barista-components/table/index.ts
  libs/barista-components/table/src/expandable/expandable-row.ts
  libs/barista-components/table/src/selection/index.ts
  libs/barista-components/table/src/selection/selection.ts
  libs/barista-components/table/src/selection/selector.spec.ts
  libs/barista-components/table/src/selection/selectors.scss
  libs/barista-components/table/src/selection/selectors.ts
  libs/barista-components/table/src/table-data-source.spec.ts
  libs/barista-components/table/src/table-data-source.ts
  libs/barista-components/table/src/table-module.ts
  libs/barista-components/table/src/table.ts
  libs/examples/src/index.ts
  libs/examples/src/table/index.ts
  libs/examples/src/table/table-examples.module.ts
  libs/examples/src/table/table-selection-example/table-selection-example.css
  libs/examples/src/table/table-selection-example/table-selection-example.html
  libs/examples/src/table/table-selection-example/table-selection-example.ts
Labels: pr: needs-cherry-pick, target: minor

#1372 fix(table): Fixes an issue where an expandable-row had a broken style after table-sorting.
  libs/barista-components/table/src/expandable/expandable-row.html
  libs/barista-components/table/src/expandable/expandable-row.ts
Labels: pr: merge-ready, target: minor, target: patch

#1357 chart(theming): Changed chart heatfield theming to custom properties.
  libs/barista-components/chart/src/heatfield/_chart-heatfield-theme.scss
  libs/barista-components/chart/src/heatfield/chart-heatfield.scss
Labels: pr: merge-ready, target: minor

#1339 feat(copy-to-clipboard): Switch theming to custom properties.
  libs/barista-components/copy-to-clipboard/src/copy-to-clipboard-theme.scss
  libs/barista-components/copy-to-clipboard/src/copy-to-clipboard.scss
Labels: pr: merge-ready, target: minor

#1324 feat(progress-circle): Switched theming to custom properties.
  libs/barista-components/progress-circle/src/_progress-circle-theme.scss
  libs/barista-components/progress-circle/src/progress-circle.scss
Labels: pr: merge-ready, target: minor

#1328 feat(consumption): Switched consumption theming to custom properties.
  libs/barista-components/consumption/src/_consumption-theme.scss
  libs/barista-components/consumption/src/consumption.scss
Labels: pr: merge-ready, target: minor

#1384 chore(quick-filter): Fixes the example in stackblitz.
  libs/examples/src/quick-filter/quick-filter-default-example/quick-filter-default-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#1385 fix(theming): Fixes an issue where custom properties were not set to default.
  libs/barista-components/style/themes.scss
Labels: pr: merge-ready, target: minor, target: patch

#1387 chore: Remove extract loader dependency
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#1382 Chore/tab custom proxies
  libs/fluid-elements/tab-group/src/lib/tab/tab.ts
Labels: pr: merge-ready, target: minor, target: patch

#1381 fix(formatters): Fix setting maxPrecision to negative number and input >= 1
  libs/barista-components/formatters/src/number-formatter.spec.ts
  libs/barista-components/formatters/src/number-formatter.ts
Labels: pr: merge-ready, target: minor, target: patch

#1390 fix(bundle): Fixes imports between submodules in the compiled bundle.
  angular.json
  libs/barista-components/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1389 chore: Send slack notification when barista build fails.
  .deployment/barista/Jenkinsfile
Labels: pr: merge-ready, target: minor, target: patch

#1400 Chore linting fixes
  .prettierignore
  documentation/linting.md
  libs/tools/linting/src/test/rules/dt-button-no-empty-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-card-direct-children-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-card-needs-title-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-card-no-empty-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-context-dialog-alt-text-rule/test.ts.lint
  libs/tools/linting/src/test/rules/dt-icon-button-alt-text-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-icon-button-needs-icon-rule/test.ts.lint
  libs/tools/linting/src/test/rules/dt-icon-button-needs-icon-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-inline-editor-alt-text-rule/test.ts.lint
  libs/tools/linting/src/test/rules/dt-nested-button-is-icon-button-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-tab-content-no-empty-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-tab-group-requires-tabs-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-tab-label-no-empty-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-tab-requires-content-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-tab-requires-label-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-tile-direct-children-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-tile-icon-needs-icon-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-tile-needs-icon-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-tile-needs-title-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-tile-no-empty-rule/tslint.json
  libs/tools/linting/src/test/rules/dt-toggle-button-group-item-is-button-rule/test.ts.lint
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#1373 feat(show-more): Changed theming to custom properties.
  libs/barista-components/show-more/src/_show-more-theme.scss
  libs/barista-components/show-more/src/show-more.scss
Labels: pr: merge-ready, target: minor
