Repository dynatrace-oss/barista, pull requests merged in 2020-05, with the labels that each got.

#895 barista/Element losing focus bug fix
  apps/barista-design-system/src/pages/single-page/components/icon-overview-content/icon-overview-content.ts
Labels: pr: merge-ready, target: minor, target: patch

#929 Removed Table in use headline
  libs/barista-components/table/README.md
Labels: bug, pr: merge-ready, target: minor, target: patch

#942 feat(event-chart): Use duration pipe in axis
  libs/barista-components/event-chart/src/event-chart-module.ts
  libs/barista-components/event-chart/src/event-chart.spec.ts
  libs/barista-components/event-chart/src/event-chart.ts
Labels: pr: needs-cherry-pick

#930 chore: The body should be expandable for scrollblocking to actually work
  apps/demos/src/main.scss
  apps/dev/src/main.scss
Labels: pr: merge-ready, target: minor, target: patch

#952 Fix confirmation-dialog openChanged typo to openChange in its readme
  libs/barista-components/context-dialog/README.md
Labels: pr: merge-ready, target: minor, target: patch

#954 chore: Add fork instruction to contributing guide
  CONTRIBUTING.md
Labels: pr: merge-ready, target: minor, target: patch

#961 fix(autocomplete): Fixes an issue with the positioning of the overlay.
  libs/barista-components/autocomplete/src/autocomplete-trigger.ts
Labels: pr: merge-ready, target: minor, target: patch

#972 fix(empty-state): Fixed ssr-rendering for the empty-state component.
  libs/barista-components/empty-state/src/empty-state.ts
Labels: pr: merge-ready, target: minor, target: patch

#973 style: Darkened disabled color to ensure better contrast.
  libs/barista-components/core/src/style/_variables.scss
Labels: pr: needs-cherry-pick

#969 chore: Update peer dependency of barista-icons to >5.0.0
  libs/barista-components/package.json
Labels: target: major

#968 fix(filter-field): Fixes an issue with filter field usage in forms.
  apps/components-e2e/src/components/filter-field/filter-field.html
  apps/components-e2e/src/components/filter-field/filter-field.ts
  libs/barista-components/filter-field/src/filter-field.html
  libs/barista-components/filter-field/src/filter-field.ts
Labels: P1, bug, pr: merge-ready, target: minor, target: patch

#976 build: Fix failing ngcc due to ngcc parallel mode.
  .circleci/config.yml
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#979 CI: Fixes an issue where nothing was available to run on this node
  libs/workspace/src/scripts/run-parallel.ts
  libs/workspace/src/scripts/util/split-array-into-chunks.spec.ts
Labels: pr: merge-ready, target: minor, target: patch

#931 Update highcharts
  apps/components-e2e/src/components/chart/chart-base.ts
  apps/components-e2e/src/components/chart/chart/chart.ts
  apps/components-e2e/src/components/chart/pie-chart/pie-chart.ts
  apps/components-e2e/src/components/drawer/drawer.ts
  apps/dev/src/table/table-demo.component.ts
  libs/barista-components/chart/index.ts
  libs/barista-components/chart/src/chart-options.ts
  libs/barista-components/chart/src/chart.spec.ts
  libs/barista-components/chart/src/chart.ts
  libs/barista-components/chart/src/heatfield/chart-heatfield.spec.ts
  libs/barista-components/chart/src/heatfield/chart-heatfield.ts
  libs/barista-components/chart/src/highcharts/highcharts-tooltip-extensions.spec.ts
  libs/barista-components/chart/src/highcharts/highcharts-tooltip-extensions.ts
  libs/barista-components/chart/src/highcharts/highcharts-tooltip-types.ts
  libs/barista-components/chart/src/highcharts/highcharts-util.ts
  libs/barista-components/chart/src/range/range.ts
  libs/barista-components/chart/src/selection-area/selection-area.spec.ts
  libs/barista-components/chart/src/selection-area/selection-area.ts
  libs/barista-components/chart/src/timestamp/timestamp.ts
  libs/barista-components/chart/src/tooltip/chart-tooltip.spec.ts
  libs/barista-components/chart/src/tooltip/chart-tooltip.ts
  libs/barista-components/micro-chart/src/micro-chart-options.ts
  libs/barista-components/micro-chart/src/micro-chart-util.spec.ts
  libs/barista-components/micro-chart/src/micro-chart-util.ts
  libs/barista-components/micro-chart/src/micro-chart.spec.ts
  libs/barista-components/micro-chart/src/micro-chart.ts
  libs/examples/src/chart/chart-area-example/chart-area-example.ts
  libs/examples/src/chart/chart-bar-example/chart-bar-example.ts
  libs/examples/src/chart/chart-behavior-switch-example/chart-behavior-switch-example.ts
  libs/examples/src/chart/chart-categorized-example/chart-categorized-example.ts
  libs/examples/src/chart/chart-data-utils.ts
  libs/examples/src/chart/chart-default-example/chart-default-example.ts
  libs/examples/src/chart/chart-donut-example/chart-donut-example.ts
  libs/examples/src/chart/chart-heatfield-example/chart-heatfield-example.ts
  libs/examples/src/chart/chart-heatfield-multiple-example/chart-heatfield-multiple-example.ts
  libs/examples/src/chart/chart-line-example/chart-line-example.ts
  libs/examples/src/chart/chart-line-with-gaps-example/chart-line-with-gaps-example.ts
  libs/examples/src/chart/chart-loading-example/chart-loading-example.ts
  libs/examples/src/chart/chart-min-max-example/chart-min-max-example.ts
  libs/examples/src/chart/chart-ordered-colors-example/chart-ordered-colors-example.ts
  libs/examples/src/chart/chart-pie-example/chart-pie-example.ts
  libs/examples/src/chart/chart-selection-area-default-example/chart-selection-area-default-example.ts
  libs/examples/src/chart/chart-stream-example/chart-stream-example.ts
  libs/examples/src/micro-chart/micro-chart-columns-example/micro-chart-columns-example.ts
  libs/examples/src/micro-chart/micro-chart-columns-interpolated-example/micro-chart-columns-interpolated-example.ts
  libs/examples/src/micro-chart/micro-chart-default-example/micro-chart-default-example.ts
  libs/examples/src/micro-chart/micro-chart-interpolated-example/micro-chart-interpolated-example.ts
  libs/examples/src/micro-chart/micro-chart-stream-example/micro-chart-stream-example.ts
  libs/testing/fixtures/src/lib/chart/generate-area-range-data.ts
  libs/testing/fixtures/src/lib/chart/generate-data.ts
  package-lock.json
  package.json
Labels: pr: merge-ready, target: major

#920 feat(button): Changed button theming to custom properties
  libs/barista-components/button/src/_button-theme.scss
  libs/barista-components/button/src/button.scss
  libs/barista-components/style/main.scss
  libs/barista-components/style/themes.scss
Labels: pr: merge-ready, target: minor

#987 chore(workspace): Add initial WORKSPACE configuration for bazel.
  .bazelignore
  .bazelversion
  .gitignore
  BUILD.bazel
  WORKSPACE
  package-lock.json
  package.json
Labels: bazel 🥦, pr: merge-ready, target: minor, target: patch

#1006 ci(slack-release-notifier): Fix slack API error on long changelogs
  tools/slack-release-notifier/src/main.ts
  tools/slack-release-notifier/src/utils/fancify-text.ts
  tools/slack-release-notifier/src/utils/text-conversion.ts
Labels: pr: merge-ready, target: minor, target: patch

#1000 Fixes an issue where the production internal configuration was missing
  angular.json
Labels: bug, pr: merge-ready, target: minor, target: patch

#1008 chore(schematics): Reworks needle to handle aria label bindings corre…
  libs/barista-components/schematics/src/migrations/update-7-0-0/__snapshots__/update-7-0-0.spec.ts.snap
  libs/barista-components/schematics/src/migrations/update-7-0-0/config/template-replacements.ts
  libs/barista-components/schematics/src/migrations/update-7-0-0/update-7-0-0.spec.ts
Labels: pr: merge-ready, target: minor, target: patch

#1002 build(preview): Fixed barista preview deployments.
  .github/workflows/barista-preview.yml
Labels: pr: merge-ready, target: minor, target: patch

#1014 fix(sunburst-chart,radial-chart): Fix css custom properties on template
  libs/barista-components/radial-chart/src/radial-chart.html
  libs/barista-components/radial-chart/src/radial-chart.ts
  libs/barista-components/sunburst-chart/README.md
  libs/barista-components/sunburst-chart/src/sunburst-chart.html
  libs/barista-components/sunburst-chart/src/sunburst-chart.scss
  libs/barista-components/sunburst-chart/src/sunburst-chart.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.util.ts
Labels: pr: merge-ready, target: major

#1012 chore(workspace): Add buildifier
  BUILD.bazel
  WORKSPACE
  libs/shared/node/BUILD.bazel
  libs/workspace/BUILD.bazel
  package-lock.json
  package.json
Labels: bazel 🥦, target: major

#1023 fix(button): Fixes the regression that button colors changed due to t…
  libs/barista-components/button/src/_button-theme.scss
Labels: pr: merge-ready, target: minor, target: patch

#1031 barista(builder): Fixes an issue with the index file generation.
  .deployment/barista/barista-internal.Dockerfile
  libs/workspace/src/builders/barista-build/builder.spec.ts
  libs/workspace/src/builders/barista-build/builder.ts
  libs/workspace/src/builders/barista-build/renderer.spec.ts
  libs/workspace/src/builders/barista-build/renderer.ts
  libs/workspace/src/test-setup.ts
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#1032 fix(core): Fixes issue with the `isNumber` util function
  libs/barista-components/core/src/util/platform-util.ts
  libs/barista-components/core/src/util/type-util.spec.ts
  libs/barista-components/core/src/util/type-util.ts
  libs/barista-components/formatters/src/bits/bits.ts
  libs/barista-components/formatters/src/bytes/bytes.ts
  libs/barista-components/formatters/src/bytes/kilobytes.ts
  libs/barista-components/formatters/src/bytes/megabytes.ts
  libs/barista-components/formatters/src/count/count.ts
  libs/barista-components/formatters/src/duration/duration.ts
  libs/barista-components/formatters/src/percent/percent.ts
  libs/barista-components/formatters/src/rate/rate.ts
  libs/barista-components/pagination/src/pagination.ts
  libs/barista-components/table/src/simple-columns/simple-number-column.ts
Labels: pr: merge-ready, target: major

#1039 build(workspace): Fix affected linting on windows.
  libs/workspace/src/builders/stylelint/read-files.ts
Labels: pr: merge-ready, target: minor, target: patch

#1045 build(a11y): Fixes an issue with running accessibility tests on windows.
  angular.json
Labels: pr: merge-ready, target: minor, target: patch

#1049 chore(chart): Change DtChartSeries types to match supported chart types
  libs/barista-components/chart/src/chart.ts
  libs/examples/src/chart/chart-loading-example/chart-loading-example.ts
  libs/examples/src/chart/chart-stream-example/chart-stream-example.ts
Labels: target: major

#1033 chore(release): Fixed peer deps refs in package.json for bundle.
  libs/barista-components/package.json
Labels: target: major

#1050 fix(table): Fixes an issue where the table tried to render after it was destroyed
  libs/barista-components/table/src/cell.ts
  libs/barista-components/table/src/table-data-source.ts
  libs/barista-components/table/src/table.ts
Labels: pr: merge-ready, target: minor, target: patch

#1029 feat(filter-field): Types
  apps/components-e2e/src/components/filter-field/filter-field.ts
  apps/dev/src/filter-field/filter-field-demo.component.ts
  libs/barista-components/experimental/quick-filter/src/quick-filter-data-source.ts
  libs/barista-components/experimental/quick-filter/src/state/actions.ts
  libs/barista-components/experimental/quick-filter/src/state/effects.ts
  libs/barista-components/experimental/quick-filter/src/state/selectors.ts
  libs/barista-components/filter-field/src/filter-field-data-source.ts
  libs/barista-components/filter-field/src/filter-field-default-data-source.ts
  libs/barista-components/filter-field/src/filter-field-util.spec.ts
  libs/barista-components/filter-field/src/filter-field-util.ts
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
  libs/barista-components/filter-field/src/types.ts
  libs/examples/src/filter-field/filter-field-async-example/filter-field-async-example.ts
  libs/examples/src/filter-field/filter-field-clearall-example/filter-field-clearall-example.ts
  libs/examples/src/filter-field/filter-field-default-example/filter-field-default-example.ts
  libs/examples/src/filter-field/filter-field-disabled-example/filter-field-disabled-example.ts
  libs/examples/src/filter-field/filter-field-distinct-example/filter-field-distinct-example.ts
  libs/examples/src/filter-field/filter-field-programmatic-filters-example/filter-field-programmatic-filters-example.ts
  libs/examples/src/filter-field/filter-field-readonly-non-editable-tags-example/filter-field-readonly-non-editable-tags-example.ts
  libs/examples/src/filter-field/filter-field-unique-example/filter-field-unique-example.ts
Labels: feature, target: major

#1054 chore: Remove unused readFile reference
  libs/workspace/src/builders/barista-build/renderer.ts
Labels: pr: merge-ready, target: minor, target: patch

#1026 feat(card): Changes styling to use custom properties
  libs/barista-components/card/src/_card-theme.scss
  libs/barista-components/card/src/card.scss
Labels: pr: merge-ready, target: minor

#1022 feat(breadcrumbs): Changes styling to use custom properties
  libs/barista-components/breadcrumbs/src/_breadcrumbs-theme.scss
  libs/barista-components/breadcrumbs/src/breadcrumbs.scss
  libs/barista-components/style/main.scss
  libs/barista-components/style/themes.scss
Labels: pr: merge-ready, target: minor

#1016 feat(bar-indicator): Changes styling to use custom properties
  libs/barista-components/bar-indicator/src/_bar-indicator-theme.scss
  libs/barista-components/bar-indicator/src/bar-indicator.scss
Labels: pr: merge-ready, target: minor

#1030 feat(checkbox): Changes styling to use custom properties
  libs/barista-components/checkbox/src/_checkbox-theme.scss
  libs/barista-components/checkbox/src/checkbox.scss
Labels: pr: merge-ready, target: minor

#1064 chore(filter-field): Make initial datasource set optional again.
  libs/barista-components/filter-field/src/filter-field-default-data-source.ts
Labels: target: major

#1062 chore: Run previews only on pull requests within the repo.
  .github/workflows/barista-preview.yml
Labels: pr: merge-ready, target: minor, target: patch

#985 barista docs - Filter Field validator example
  apps/demos/src/barista-examples.a11y.ts
  libs/barista-components/filter-field/README.md
  libs/examples/src/filter-field/filter-field-examples.module.ts
  libs/examples/src/filter-field/filter-field-validator-example/filter-field-validator-example.html
  libs/examples/src/filter-field/filter-field-validator-example/filter-field-validator-example.ts
  libs/examples/src/filter-field/index.ts
  libs/examples/src/index.ts
Labels: pr: merge-ready, target: minor, target: patch

#974 feat(confirmation-dialog): Restyle confirmation dialog + add wiggle a…
  apps/dev/src/confirmation-dialog/confirmation-dialog-demo.component.html
  apps/dev/src/confirmation-dialog/confirmation-dialog-demo.component.scss
  apps/dev/src/confirmation-dialog/confirmation-dialog-demo.component.ts
  libs/barista-components/confirmation-dialog/README.md
  libs/barista-components/confirmation-dialog/src/_confirmation-dialog-responsive.scss
  libs/barista-components/confirmation-dialog/src/confirmation-dialog-constants.ts
  libs/barista-components/confirmation-dialog/src/confirmation-dialog-state/confirmation-dialog-state.html
  libs/barista-components/confirmation-dialog/src/confirmation-dialog-state/confirmation-dialog-state.scss
  libs/barista-components/confirmation-dialog/src/confirmation-dialog-state/confirmation-dialog-state.ts
  libs/barista-components/confirmation-dialog/src/confirmation-dialog.html
  libs/barista-components/confirmation-dialog/src/confirmation-dialog.scss
  libs/barista-components/confirmation-dialog/src/confirmation-dialog.spec.ts
  libs/barista-components/confirmation-dialog/src/confirmation-dialog.ts
Labels: pr: merge-ready, target: minor

#1041 build(design-tokens): Added dependency-tree analyzer and builder for design tokens.
  angular.json
  libs/workspace/builders.json
  libs/workspace/src/builders/design-tokens/dependency-tree/__snapshots__/dependency-graph.spec.ts.snap
  libs/workspace/src/builders/design-tokens/dependency-tree/add-component-dependencies.spec.ts
  libs/workspace/src/builders/design-tokens/dependency-tree/add-component-dependencies.ts
  libs/workspace/src/builders/design-tokens/dependency-tree/add-tokens-to-alias-dependencies.spec.ts
  libs/workspace/src/builders/design-tokens/dependency-tree/add-tokens-to-alias-dependencies.ts
  libs/workspace/src/builders/design-tokens/dependency-tree/build.ts
  libs/workspace/src/builders/design-tokens/dependency-tree/dependency-graph.spec.ts
  libs/workspace/src/builders/design-tokens/dependency-tree/dependency-graph.ts
  libs/workspace/src/builders/design-tokens/dependency-tree/find-source-files.ts
  libs/workspace/src/builders/design-tokens/dependency-tree/index.ts
  libs/workspace/src/builders/design-tokens/dependency-tree/schema.json
  libs/workspace/src/builders/design-tokens/dependency-tree/schema.ts
  libs/workspace/webpack.config.js
  package.json
Labels: next, pr: merge-ready, target: minor, target: patch

#1078 chore(filter-field): Fix datasource in example is no longer generic
  libs/examples/src/filter-field/filter-field-validator-example/filter-field-validator-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#1047 feat(sunburst-chart): Add E2E
  apps/components-e2e/src/app/app.routing.module.ts
  apps/components-e2e/src/components/sunburst-chart/sunburst-chart.e2e.ts
  apps/components-e2e/src/components/sunburst-chart/sunburst-chart.html
  apps/components-e2e/src/components/sunburst-chart/sunburst-chart.module.ts
  apps/components-e2e/src/components/sunburst-chart/sunburst-chart.po.ts
  apps/components-e2e/src/components/sunburst-chart/sunburst-chart.ts
  apps/dev/src/sunburst/sunburst-demo-data.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.html
Labels: pr: merge-ready

#1079 chore: Extend support for barista-icons up to version 7
  libs/barista-components/package.json
Labels: pr: merge-ready

#1068 docs(migration): Add migration guide for 6 to 7
  documentation/migration-guide.json
  documentation/migration-guide.md
Labels: pr: merge-ready, target: minor, target: patch

#1021 barista(filter-field): Add partial option.
  apps/demos/src/barista-examples.a11y.ts
  apps/dev/src/filter-field/filter-field-demo.component.html
  apps/dev/src/filter-field/filter-field-demo.component.ts
  apps/dev/src/filter-field/testdata.ts
  libs/barista-components/experimental/quick-filter/src/quick-filter-default-data-source.ts
  libs/barista-components/experimental/quick-filter/src/state/reducer.spec.ts
  libs/barista-components/filter-field/README.md
  libs/barista-components/filter-field/src/filter-field-default-data-source.ts
  libs/barista-components/filter-field/src/filter-field-util.spec.ts
  libs/barista-components/filter-field/src/filter-field-util.ts
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
  libs/barista-components/filter-field/src/types.ts
  libs/examples/src/filter-field/filter-field-examples.module.ts
  libs/examples/src/filter-field/filter-field-partial-example/filter-field-partial-example.html
  libs/examples/src/filter-field/filter-field-partial-example/filter-field-partial-example.ts
  libs/examples/src/filter-field/index.ts
  libs/examples/src/index.ts
Labels: target: major

#1015 chore(schematics): Dt e2e schematic
  .prettierignore
  angular.json
  libs/barista-components/schematics/src/testing/workspace.ts
  libs/workspace/collection.json
  libs/workspace/src/schematics/dt-component-e2e/README.md
  libs/workspace/src/schematics/dt-component-e2e/__snapshots__/index.spec.ts.snap
  libs/workspace/src/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.e2e.ts
  libs/workspace/src/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.html
  libs/workspace/src/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.module.ts
  libs/workspace/src/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.po.ts
  libs/workspace/src/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.ts
  libs/workspace/src/schematics/dt-component-e2e/fixtures/alert.fixture.ts
  libs/workspace/src/schematics/dt-component-e2e/fixtures/app.routing.module.ts.fixture.ts
  libs/workspace/src/schematics/dt-component-e2e/index.spec.ts
  libs/workspace/src/schematics/dt-component-e2e/index.ts
  libs/workspace/src/schematics/dt-component-e2e/schema.json
  libs/workspace/src/schematics/dt-component-e2e/schema.ts
  libs/workspace/src/schematics/utils/ast-utils.ts
  libs/workspace/src/schematics/utils/change.ts
  libs/workspace/tsconfig.json
  libs/workspace/tsconfig.lib.json
  libs/workspace/webpack.config.js
  tools/schematics/utils/ast-utils.ts
Labels: target: major

#924 feat(table): Add order functionality to table.
  apps/components-e2e/src/app/app.routing.module.ts
  apps/components-e2e/src/components/table-order/table-order-expandable/table-expandable.html
  apps/components-e2e/src/components/table-order/table-order-expandable/table-expandable.ts
  apps/components-e2e/src/components/table-order/table-order/table.html
  apps/components-e2e/src/components/table-order/table-order/table.ts
  apps/components-e2e/src/components/table-order/table.e2e.ts
  apps/components-e2e/src/components/table-order/table.module.ts
  apps/components-e2e/src/components/table-order/table.po.ts
  apps/dev/src/app.module.ts
  apps/dev/src/devapp-routing.module.ts
  apps/dev/src/devapp.component.ts
  apps/dev/src/table-order/table-order-demo.component.html
  apps/dev/src/table-order/table-order-demo.component.scss
  apps/dev/src/table-order/table-order-demo.component.ts
  libs/barista-components/package.json
  libs/barista-components/table/README.md
  libs/barista-components/table/index.ts
  libs/barista-components/table/src/order/order-cell.html
  libs/barista-components/table/src/order/order-cell.scss
  libs/barista-components/table/src/order/order-cell.ts
  libs/barista-components/table/src/order/order-directive.ts
  libs/barista-components/table/src/row.ts
  libs/barista-components/table/src/simple-columns/index.ts
  libs/barista-components/table/src/simple-columns/simple-column.scss
  libs/barista-components/table/src/simple-columns/simple-order-column.html
  libs/barista-components/table/src/simple-columns/simple-order-column.spec.ts
  libs/barista-components/table/src/simple-columns/simple-order-column.ts
  libs/barista-components/table/src/table-module.ts
  libs/barista-components/table/src/table-order-data-source.ts
  libs/examples/src/index.ts
  libs/examples/src/table/index.ts
  libs/examples/src/table/table-examples.module.ts
  libs/examples/src/table/table-order-column-example/table-order-column-example.html
  libs/examples/src/table/table-order-column-example/table-order-column-example.scss
  libs/examples/src/table/table-order-column-example/table-order-column-example.ts
  libs/examples/src/table/table-order-expandable-example/table-order-expandable-example.html
  libs/examples/src/table/table-order-expandable-example/table-order-expandable-example.scss
  libs/examples/src/table/table-order-expandable-example/table-order-expandable-example.ts
  libs/examples/src/table/table-order-observable-example/table-order-observable-example.html
  libs/examples/src/table/table-order-observable-example/table-order-observable-example.ts
  package-lock.json
  package.json
Labels: target: major

#1080 test(table): Fixes an issue where drag table e2e tests did not work in edge.
  apps/components-e2e/src/components/table-order/table.po.ts
Labels: target: major

#1085 fix(button): Increases specificity for anchor button selectors
  libs/barista-components/button/src/_button-theme.scss
Labels: target: minor, target: patch

#1088 chore: Fixes data accessor for ux decisiongraph nodes
  libs/tools/barista/src/generators/ux-decision-graph.ts
  libs/tools/barista/src/types.ts
Labels: documentation, pr: merge-ready, target: minor, target: patch

#1089 barista: Fix prerendering for index page content.
  apps/barista-design-system/src/app/app.routing.module.ts
Labels: pr: merge-ready, target: minor, target: patch

#1094 docs: fix typo in getting started code example
  documentation/getting-started.md
Labels: pr: needs-cherry-pick
