Repository dynatrace-oss/barista, pull requests merged in 2020-09, with the labels that each got.

#1391 fix(option): Fixes multiple selected bug when using keyboard and mouse
  apps/components-e2e/src/components/autocomplete/autocomplete.e2e.ts
  apps/components-e2e/src/components/autocomplete/autocomplete.po.ts
  apps/components-e2e/src/components/select/select.e2e.ts
  apps/components-e2e/src/components/select/select.po.ts
  apps/dev/src/select/select-demo.component.html
  libs/barista-components/autocomplete/src/autocomplete.ts
  libs/barista-components/core/src/option/option.scss
  libs/barista-components/core/src/option/option.ts
  libs/barista-components/select/src/select.ts
Labels: pr: merge-ready, target: minor, target: patch

#1510 chore: Adds aria support for the tab and tab-group
  libs/fluid-elements/tab-group/src/lib/tab-events.ts
  libs/fluid-elements/tab-group/src/lib/tab-group/tab-group.spec.ts
  libs/fluid-elements/tab-group/src/lib/tab-group/tab-group.ts
  libs/fluid-elements/tab-group/src/lib/tab/tab.spec.ts
  libs/fluid-elements/tab-group/src/lib/tab/tab.ts
Labels: pr: merge-ready, target: minor, target: patch

#1546 build(drawer): Bazelify Drawer component
  angular.json
  libs/barista-components/drawer/BUILD.bazel
  libs/barista-components/drawer/jest.config.js
  libs/barista-components/drawer/jest.config.json
  libs/barista-components/drawer/tsconfig.json
  libs/barista-components/drawer/tsconfig.lib.json
  tools/bazel_rules/BUILD.bazel
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1514 build(fluid-button): Add jest tests for fluid button
  angular.json
  libs/fluid-elements/button/BUILD.bazel
  libs/fluid-elements/button/jest.config.js
  libs/fluid-elements/button/jest.config.json
  package-lock.json
  package.json
  tools/bazel_rules/jest/BUILD.bazel
  tools/bazel_rules/jest/babel.config.js
  tools/bazel_rules/jest/jest-resolver.js
  tools/bazel_rules/jest/jest-runner.js
  tools/bazel_rules/jest/jest_macro.bzl
Labels: bazel, next, pr: merge-ready, target: minor, target: patch

#1549 build(fluid-checkbox): Bazelify fluid-checkbox
  angular.json
  libs/fluid-elements/checkbox/BUILD.bazel
  libs/shared/keycodes/BUILD.bazel
  libs/shared/keycodes/index.ts
  libs/workspace/src/builders/elements/package/build.ts
  tsconfig.base.json
Labels: bazel, next, pr: merge-ready, target: minor, target: patch

#1448 ds: Use installed instead of checked-out icons as icon-page source
  .deployment/barista/internal/Jenkinsfile
  .deployment/barista/public/Jenkinsfile
  environments/barista-environment.ts
Labels: pr: merge-ready, target: minor, target: patch

#1561 ci: Update bazelrc flags
  .bazelrc
Labels: pr: merge-ready, target: minor, target: patch

#1562 build(bazel): Fix npm install on windows.
  WORKSPACE
  rules_nodejs-npm-install+2.0.3.patch
Labels: pr: merge-ready, target: minor, target: patch

#1564 fix(tree-table): Fixes overflow when info-group contains long texts
  apps/dev/src/tree-table/tree-table-demo.component.ts
  libs/barista-components/tree-table/README.md
  libs/barista-components/tree-table/src/tree-table-row.scss
  libs/examples/src/tree-table/tree-table-default-example/tree-table-default-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#1575 docs: Improve the local dev setup section.
  DEVELOPMENT.md
Labels: pr: merge-ready, target: minor, target: patch

#1578 Fix a regression that was introduced with the update to the new typescript version.
  libs/barista-components/button-group/src/button-group.ts
  libs/barista-components/core/src/common-behaviours/color.ts
Labels: pr: merge-ready, target: minor, target: patch

#1581 Release stage/8.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pr: merge-ready

#1585 fix(filter-field): Fixed UX problem where text that wasn't applied to the filter would remain after losing focus.
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#1610 build(micro-chart): Bazelify micro-chart component.
  angular.json
  libs/barista-components/micro-chart/BUILD.bazel
  libs/barista-components/micro-chart/jest.config.js
  libs/barista-components/micro-chart/jest.config.json
  libs/barista-components/micro-chart/tsconfig.json
  libs/barista-components/micro-chart/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1608 build(inline-editor): Bazelify inline-editor component.
  angular.json
  libs/barista-components/inline-editor/BUILD.bazel
  libs/barista-components/inline-editor/jest.config.js
  libs/barista-components/inline-editor/jest.config.json
  libs/barista-components/inline-editor/tsconfig.json
  libs/barista-components/inline-editor/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1606 build(indicator): Bazelify indicator component.
  angular.json
  libs/barista-components/indicator/BUILD.bazel
  libs/barista-components/indicator/jest.config.js
  libs/barista-components/indicator/jest.config.json
  libs/barista-components/indicator/tsconfig.json
  libs/barista-components/indicator/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1607 build(info-group): Bazelify info-group component
  angular.json
  libs/barista-components/info-group/BUILD.bazel
  libs/barista-components/info-group/jest.config.js
  libs/barista-components/info-group/jest.config.json
  libs/barista-components/info-group/tsconfig.json
  libs/barista-components/info-group/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1594 build(expandable-panel): Bazelify expandable-panel component
  angular.json
  libs/barista-components/expandable-panel/BUILD.bazel
  libs/barista-components/expandable-panel/jest.config.js
  libs/barista-components/expandable-panel/jest.config.json
  libs/barista-components/expandable-panel/tsconfig.json
  libs/barista-components/expandable-panel/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1604 build(copy-to-clipboard): Bazelify copy-to-clipboard component
  angular.json
  libs/barista-components/copy-to-clipboard/BUILD.bazel
  libs/barista-components/copy-to-clipboard/jest.config.js
  libs/barista-components/copy-to-clipboard/jest.config.json
  libs/barista-components/copy-to-clipboard/tsconfig.json
  libs/barista-components/copy-to-clipboard/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1609 build(menu): Bazelify menu component.
  angular.json
  libs/barista-components/menu/BUILD.bazel
  libs/barista-components/menu/jest.config.js
  libs/barista-components/menu/jest.config.json
  libs/barista-components/menu/tsconfig.json
  libs/barista-components/menu/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1603 build(container-breakpoint-observer): Bazelify container-breakpoint-observer component
  angular.json
  libs/barista-components/container-breakpoint-observer/BUILD.bazel
  libs/barista-components/container-breakpoint-observer/jest.config.js
  libs/barista-components/container-breakpoint-observer/jest.config.json
  libs/barista-components/container-breakpoint-observer/tsconfig.json
  libs/barista-components/container-breakpoint-observer/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1588 build(context-dialog): Bazelify context-dialog component
  angular.json
  libs/barista-components/context-dialog/BUILD.bazel
  libs/barista-components/context-dialog/jest.config.js
  libs/barista-components/context-dialog/jest.config.json
  libs/barista-components/context-dialog/tsconfig.json
  libs/barista-components/context-dialog/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1599 build(quick-filter): Bazelify quick-filter component
  angular.json
  libs/barista-components/experimental/quick-filter/BUILD.bazel
  libs/barista-components/experimental/quick-filter/jest.config.js
  libs/barista-components/experimental/quick-filter/jest.config.json
  libs/barista-components/experimental/quick-filter/tsconfig.json
  libs/barista-components/experimental/quick-filter/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1602 build(legend): Bazelify legend component.
  angular.json
  libs/barista-components/legend/BUILD.bazel
  libs/barista-components/legend/jest.config.js
  libs/barista-components/legend/jest.config.json
  libs/barista-components/legend/tsconfig.json
  libs/barista-components/legend/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1593 build(empty-state): Bazelify empty-state component
  angular.json
  libs/barista-components/empty-state/BUILD.bazel
  libs/barista-components/empty-state/jest.config.js
  libs/barista-components/empty-state/jest.config.json
  libs/barista-components/empty-state/tsconfig.json
  libs/barista-components/empty-state/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1597 chore: Adds arrow-down and -up support for the getNextGroupItemIndex …
  libs/fluid-elements/core/src/lib/keyboard/get-next-group-item-index.spec.ts
  libs/fluid-elements/core/src/lib/keyboard/get-next-group-item-index.ts
Labels: pr: merge-ready, target: minor, target: patch

#1601 build(pagination): Bazelify pagination component.
  angular.json
  libs/barista-components/pagination/BUILD.bazel
  libs/barista-components/pagination/jest.config.js
  libs/barista-components/pagination/jest.config.json
  libs/barista-components/pagination/tsconfig.json
  libs/barista-components/pagination/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1598 docs(drawer): Added information about collapsing into overlay mode if the drawer is less than 1024 pixels wide.
  libs/barista-components/drawer/README.md
Labels: documentation, pr: merge-ready, target: minor, target: patch

#1605 [combobox] Attempt to fix combobox
  libs/barista-components/experimental/combobox/src/combobox.ts
Labels: pr: merge-ready, target: minor, target: patch

#1621 fix(filter-field): Fixes an issue where custom tag parsers are not applied on filters set initially.
  apps/dev/src/filter-field/filter-field-demo.component.html
  apps/dev/src/filter-field/filter-field-demo.component.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#1623 ci(bazel): Bazelify expandable-section.
  angular.json
  libs/barista-components/expandable-section/BUILD.bazel
  libs/barista-components/expandable-section/jest.config.js
  libs/barista-components/expandable-section/jest.config.json
  libs/barista-components/expandable-section/src/expandable-section.ts
  libs/barista-components/expandable-section/tsconfig.json
  libs/barista-components/expandable-section/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1629 build(design-tokens): Fix bazel build on windows
  tools/design-tokens/build/src/utils/find-common-root-path.ts
Labels: pr: merge-ready, target: minor, target: patch

#1625 fix(filter-field): Fixes an issue where suggestions are not displayed in MS Edge
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/highlight/src/highlight.ts
Labels: pr: merge-ready, pr: needs-cherry-pick

#1622 ci(design-tokens-ui): Build and deploy Design Tokens UI with vercel.
  .deployment/design-tokens-ui/vercel.json
  .github/.bazelrc
  .github/workflows/design-tokens-ui.yml
Labels: pr: merge-ready, target: minor, target: patch

#1650 Revert "fix(filter-field): Fixed UX problem where text that wasn't applied to the filter would remain after losing focus."
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, pr: needs-cherry-pick

#1627 WebComponents: Adds PropertyValue to aria labeling and fixes disabled in button-group
  apps/fluid-dev/src/pages/button-group/button-group-page.component.html
  libs/fluid-elements/button-group/README.md
  libs/fluid-elements/button-group/src/lib/button-group-item/button-group-item.ts
  libs/fluid-elements/button-group/src/lib/button-group/button-group.spec.ts
  libs/fluid-elements/button-group/src/lib/button-group/button-group.ts
  libs/fluid-elements/checkbox/src/lib/checkbox.ts
  libs/fluid-elements/switch/src/lib/switch.ts
  libs/fluid-elements/tab-group/src/lib/tab/tab.ts
Labels: pr: merge-ready, target: minor, target: patch

#1630 feat(alert): Introduce `info` severity type.
  apps/dev/src/alert/alert-demo.component.html
  apps/dev/src/alert/alert-demo.component.scss
  libs/barista-components/alert/README.md
  libs/barista-components/alert/src/_alert-theme.scss
  libs/barista-components/alert/src/alert.html
  libs/barista-components/alert/src/alert.ts
  libs/examples/src/alert/alert-interactive-example/alert-interactive-example.html
Labels: pr: merge-ready, pr: needs-cherry-pick

#1567 feat(fluid-popover): Introduce FluidPopover as WebComponent.
  .circleci/config.yml
  angular.json
  apps/fluid-dev/src/app/app.component.html
  apps/fluid-dev/src/app/app.routing.module.ts
  apps/fluid-dev/src/pages/popover/popover-page.component.html
  apps/fluid-dev/src/pages/popover/popover-page.component.scss
  apps/fluid-dev/src/pages/popover/popover-page.component.ts
  apps/fluid-dev/src/pages/popover/popover-page.module.ts
  libs/fluid-elements/popover/BUILD.bazel
  libs/fluid-elements/popover/README.md
  libs/fluid-elements/popover/jest.config.json
  libs/fluid-elements/popover/package.json
  libs/fluid-elements/popover/src/index.ts
  libs/fluid-elements/popover/src/lib/popover.spec.ts
  libs/fluid-elements/popover/src/lib/popover.ts
  libs/fluid-elements/popover/tsconfig.json
  libs/fluid-elements/popover/tsconfig.lib.json
  libs/fluid-elements/popover/tsconfig.spec.json
  libs/fluid-elements/popover/tslint.json
  nx.json
  package-lock.json
  package.json
  tools/bazel_rules/jest/BUILD.bazel
  tools/bazel_rules/jest/jest-resolver.js
  tools/bazel_rules/jest/jest_macro.bzl
  tsconfig.base.json
Labels: pr: merge-ready, pr: needs-cherry-pick

#1626 TreeTable e2e test
  apps/components-e2e/src/components/tree-table/tree-table.e2e.ts
  apps/components-e2e/src/components/tree-table/tree-table.po.ts
  apps/components-e2e/src/components/tree-table/tree-table.ts
  apps/dev/src/tree-table/tree-table-demo.component.ts
  libs/barista-components/tree-table/src/tree-table-row.scss
  libs/barista-components/tree-table/src/tree-table-toggle-cell.html
  libs/barista-components/tree-table/src/tree-table-toggle-cell.scss
Labels: pr: merge-ready, target: minor, target: patch

#1620 chore: Remove the customizable tooltip references from the micro-chart doc
  libs/barista-components/micro-chart/README.md
  libs/examples/src/micro-chart/micro-chart-columns-example/micro-chart-columns-example.html
  libs/examples/src/micro-chart/micro-chart-columns-interpolated-example/micro-chart-columns-interpolated-example.html
  libs/examples/src/micro-chart/micro-chart-default-example/micro-chart-default-example.html
  libs/examples/src/micro-chart/micro-chart-interpolated-example/micro-chart-interpolated-example.html
  libs/examples/src/micro-chart/micro-chart-stream-example/micro-chart-stream-example.html
Labels: pr: merge-ready, target: minor, target: patch

#1579 Fixes an issue where bazel could not create runfiles on windows.
  .bazelrc
  .circleci/config.yml
  WORKSPACE
  package-lock.json
  package.json
  patches/jest-haste-map+26.1.0.patch
  patches/stylelint+13.2.1.patch
  postinstall.js
  rules_nodejs-launcher+2.0.3.patch
  tools/bazel_rules/jest/jest-resolver.js
  tools/bazel_rules/jest/jest-runner.js
  tools/bazel_rules/stylelint/junit-formatter/parse-suite.ts
  tools/bazel_rules/stylelint/run-stylelint.ts
  tools/bazel_rules/stylelint/stylelint_macro.bzl
  tools/scripts/README.md
  tools/scripts/stylelint.js
  tools/scripts/utils/execute-bazel.js
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1660 chore(fluid-popover): Remove max-height of fluid popover container.
  libs/fluid-elements/popover/src/lib/popover.ts
Labels: pr: merge-ready, pr: needs-cherry-pick

#1566 Feat/fluid icon as webcomponent
  angular.json
  apps/fluid-dev/src/app/app.component.html
  apps/fluid-dev/src/app/app.routing.module.ts
  apps/fluid-dev/src/pages/icon/icon-page.component.html
  apps/fluid-dev/src/pages/icon/icon-page.component.scss
  apps/fluid-dev/src/pages/icon/icon-page.component.ts
  apps/fluid-dev/src/pages/icon/icon-page.module.ts
  libs/fluid-elements/icon/BUILD.bazel
  libs/fluid-elements/icon/README.md
  libs/fluid-elements/icon/jest.config.json
  libs/fluid-elements/icon/package.json
  libs/fluid-elements/icon/src/index.ts
  libs/fluid-elements/icon/src/lib/icon.spec.ts
  libs/fluid-elements/icon/src/lib/icon.ts
  libs/fluid-elements/icon/tsconfig.json
  libs/fluid-elements/icon/tsconfig.lib.json
  libs/fluid-elements/icon/tsconfig.spec.json
  libs/fluid-elements/icon/tslint.json
  nx.json
  tsconfig.base.json
Labels: pr: merge-ready, pr: needs-cherry-pick

#1659 chore(fluid-input): Update fluid input padding and icon color.
  libs/fluid-elements/input/src/lib/input.styles.ts
Labels: pr: merge-ready, pr: needs-cherry-pick
