Repository dynatrace-oss/barista, pull requests merged in 2020-02, with the labels that each got.

#521 Add snyk policy file for known vulnerability.
  .snyk
  package-lock.json
  package.json
Labels: P1, pr: merge-ready, target: minor, target: patch

#525 fix(tag-add): Fixes tag add label when zoom is lower that 100%
  components/tag/src/tag-add/tag-add.scss
Labels: pr: merge-ready, target: minor, target: patch

#520 feat(filter-field): Added highlighting of the currend input value to the options.
  components/filter-field/src/filter-field-module.ts
  components/filter-field/src/filter-field.html
Labels: pr: merge-ready, target: minor

#515 Create barista preview
  .github/workflows/barista-preview.yml
Labels: pr: merge-ready, target: minor, target: patch

#508 docs: Added new pr workflow to contributing documentation.
  CONTRIBUTING.md
Labels: pr: merge-ready, target: minor, target: patch

#516 build: Disable logging the build progress.
  angular.json
Labels: pr: merge-ready, target: minor, target: patch

#437 fix(filter-field): Fixes an issue with inconsistent clearAll functionality
  apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
  apps/components-e2e/src/components/filter-field/filter-field.html
  apps/components-e2e/src/components/filter-field/filter-field.po.ts
  apps/components-e2e/src/components/filter-field/filter-field.ts
  components/filter-field/src/filter-field.html
  components/filter-field/src/filter-field.scss
  components/filter-field/src/filter-field.spec.ts
Labels: bug, pr: merge-ready, target: minor, target: patch

#523 fix(legend): Fixes issue whether the legend item does not work with the new ivy engine.
  components/legend/src/legend-item.ts
Labels: pr: merge-ready, target: minor, target: patch

#429 Barista/create color component
  angular.json
  apps/barista/src/assets/checkmark-white.svg
  apps/barista/src/components/color-component/color.html
  apps/barista/src/components/color-component/color.scss
  apps/barista/src/components/color-component/color.ts
  apps/barista/src/components/color-grid/color-grid.html
  apps/barista/src/components/color-grid/color-grid.ts
  apps/barista/src/components/components.module.ts
  apps/barista/src/components/layout-grid/layout-grid-item.html
  apps/barista/src/components/layout-grid/layout-grid-item.scss
  apps/barista/src/components/layout-grid/layout-grid-item.ts
  apps/barista/src/components/layout-grid/layout-grid.html
  apps/barista/src/components/layout-grid/layout-grid.scss
  apps/barista/src/components/layout-grid/layout-grid.ts
Labels: pr: merge-ready, target: minor, target: patch

#538 perf(autocomplete): Fixes an issue when toggling multiple times a subscription is not cleaned up.
  components/autocomplete/src/autocomplete-trigger.ts
Labels: pr: merge-ready, target: minor, target: patch

#539 barista: Replace backslashes when generating the barista examples mod…
  tools/examples/src/util.ts
Labels: pr: merge-ready, target: minor, target: patch

#541 barista: Added typings for Observables in barista app.
  apps/barista/src/app.ts
  apps/barista/src/shared/location.service.ts
Labels: pr: merge-ready, target: minor, target: patch

#543 ci: Add stale issue workflow
  .github/workflows/stale.yml
Labels: feature, pr: merge-ready, target: minor, target: patch

#462 fix(autocomplete, filter-field): Fixes an issue with overlay positioning.
  components/autocomplete/src/autocomplete-trigger.ts
  components/filter-field/src/filter-field-range/filter-field-range-trigger.ts
Labels: pr: merge-ready, target: minor, target: patch

#524 Run a11y tests on our ci.
  .circleci/config.yml
  angular.json
  apps/demos/src/barista-examples.a11y.ts
  apps/demos/src/nav-items.template
  apps/demos/tsconfig.a11y.json
Labels: pr: merge-ready, target: minor, target: patch

#400 ci: Speedup ci with parallel and xlarge resource.
  .circleci/config.yml
  package.json
Labels: P1, pr: merge-ready, target: minor, target: patch

#547 fix(filter-field): Fixes an issue where options set on an async autocomplete are shown.
  apps/components-e2e/src/components/filter-field/filter-field.po.ts
  apps/dev/src/filter-field/testdata.ts
  components/filter-field/src/filter-field.spec.ts
  components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#557 docs: Fixed links to new issue templates.
  CONTRIBUTING.md
Labels: pr: merge-ready, target: minor, target: patch

#555 barista: Add snippet-placeholders for UX content.
  components/alert/README.md
  components/bar-indicator/README.md
  components/breadcrumbs/README.md
  components/button-group/README.md
  components/button/README.md
  components/card/README.md
  components/chart/README.md
  components/checkbox/README.md
  components/confirmation-dialog/README.md
  components/consumption/README.md
  components/context-dialog/README.md
  components/copy-to-clipboard/README.md
  components/empty-state/README.md
  components/event-chart/README.md
  components/expandable-section/README.md
  components/expandable-text/README.md
  components/filter-field/README.md
  components/form-field/README.md
  components/icon/README.md
  components/info-group/README.md
  components/input/README.md
  components/key-value-list/README.md
  components/micro-chart/README.md
  components/overlay/README.md
  components/pagination/README.md
  components/progress-bar/README.md
  components/progress-circle/README.md
  components/radio/README.md
  components/secondary-nav/README.md
  components/show-more/README.md
  components/stepper/README.md
  components/switch/README.md
  components/table/README.md
  components/tabs/README.md
  components/tag/README.md
  components/tile/README.md
  components/timeline-chart/README.md
Labels: pr: merge-ready, target: minor, target: patch

#558 chore(release): Open pull request after stage release.
  tools/release/src/stage-release/stage-release.ts
Labels: pr: merge-ready, target: minor, target: patch

#571 barista: Extract shared interface from environment files.
  tools/environments/barista-environment.interface.ts
  tools/environments/barista-environment.prod.ts
  tools/environments/barista-environment.ts
Labels: pr: merge-ready, target: minor, target: patch

#575 barista: Added typings, that seem to be needed to run e2e tests …
  apps/components-e2e/src/components/chart/chart-base.ts
Labels: pr: merge-ready, target: minor, target: patch

#576 docs(confirmation-dialog): Added UX snippet for animation section.
  components/confirmation-dialog/README.md
Labels: pr: merge-ready, target: minor, target: patch

#581 chore(examples): Fixes broken loading-distractor module import.
  libs/examples/src/loading-distractor/loading-distractor-examples.module.ts
Labels: pr: merge-ready, target: minor, target: patch

#379 feat(filter-field): Add input to disable the whole filter field
  apps/dev/src/filter-field/filter-field-demo.component.html
  apps/dev/src/filter-field/filter-field-demo.component.ts
  components/filter-field/README.md
  components/filter-field/src/filter-field-tag/filter-field-tag.ts
  components/filter-field/src/filter-field.html
  components/filter-field/src/filter-field.scss
  components/filter-field/src/filter-field.spec.ts
  components/filter-field/src/filter-field.ts
  libs/examples/src/filter-field/filter-field-disabled-example/filter-field-disabled-example.html
  libs/examples/src/filter-field/filter-field-disabled-example/filter-field-disabled-example.ts
  libs/examples/src/filter-field/filter-field-examples.module.ts
Labels: pr: merge-ready, target: minor

#591 fix(table): Fixed invalid fill color for favorite-column icon
  components/table/src/simple-columns/favorite-column.scss
Labels: bug, pr: merge-ready, target: minor, target: patch

#585 fix(chart): Fixes an issue where the tooltip stayed open when the chart was destroyed.
  components/chart/src/chart.ts
Labels: pr: merge-ready, target: minor, target: patch

#574 fix(legend): Fixes an issue with small spaces between legends.
  components/legend/README.md
  components/legend/src/legend.scss
Labels: pr: merge-ready, target: minor, target: patch

#582 fix(favorite-column): Favorite column is not modifying the datasource…
  components/table/src/simple-columns/favorite-column.ts
  components/table/src/simple-columns/simple-column.spec.ts
  libs/examples/src/table/table-favorite-column-example/table-favorite-column-example.html
  libs/examples/src/table/table-favorite-column-example/table-favorite-column-example.ts
  libs/examples/src/table/table-favorite-column-no-header-example/table-favorite-column-no-header-example.html
  libs/examples/src/table/table-favorite-column-no-header-example/table-favorite-column-no-header-example.ts
Labels: bug, pr: merge-ready, target: minor, target: patch

#592 fix(filter-field): Fixes alignment of filter field tags.
  components/filter-field/src/filter-field-tag/filter-field-tag.scss
  components/filter-field/src/filter-field.scss
Labels: pr: merge-ready, target: minor, target: patch

#589 chore: Cleanup sonar bugs
  apps/barista/src/shared/scroll-spy.service.ts
  components/core/src/util/compare-util.spec.ts
  components/micro-chart/src/micro-chart.spec.ts
  components/tag/src/tag.scss
  components/theming/src/theme.ts
  libs/examples/src/cta-card/cta-card-closable-example/cta-card-closable-example.html
  libs/examples/src/drawer/drawer-nested-example/drawer-nested-example.html
  libs/examples/src/icon/icon-all-example/icon-all-example.scss
  libs/examples/src/select/select-complex-value-example/select-complex-value-example.html
  libs/examples/src/select/select-forms-example/select-forms-example.html
  libs/examples/src/select/select-value-example/select-value-example.html
  libs/examples/src/table/table-sorting-example/table-sorting-example.ts
  tools/barista/src/generators/category-navigation.ts
Labels: pr: merge-ready, target: minor, target: patch

#427 fix(tag-list): No longer shows 0 more
  apps/components-e2e/src/app/app.routing.module.ts
  apps/components-e2e/src/components/tag-list/tag-list.e2e.ts
  apps/components-e2e/src/components/tag-list/tag-list.html
  apps/components-e2e/src/components/tag-list/tag-list.module.ts
  apps/components-e2e/src/components/tag-list/tag-list.ts
  apps/dev/src/tag/tag-demo.component.ts
  components/tag/src/tag-list/tag-list.html
  components/tag/src/tag-list/tag-list.spec.ts
  components/tag/src/tag-list/tag-list.ts
Labels: pr: merge-ready, target: minor, target: patch

#546 barista: Reorganize types and interfaces for Barista app and tools.
  apps/barista/src/app.ts
  apps/barista/src/layout/smalltile/smalltile.ts
  apps/barista/src/pages/icon-overview-page/icon-overview-page.ts
  apps/barista/src/pages/index-page/index-page.ts
  apps/barista/src/pages/overview-page/overview-page.ts
  apps/barista/src/pages/single-page/single-page.ts
  apps/barista/src/shared/page-contents.ts
  apps/barista/src/shared/page.service.ts
  apps/barista/src/shared/recently-ordered.service.ts
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/src/builder/components.ts
  tools/barista/src/builder/homepage.ts
  tools/barista/src/builder/icons.ts
  tools/barista/src/builder/strapi.ts
  tools/barista/src/generators/category-navigation.ts
  tools/barista/src/main.ts
  tools/barista/src/transform.spec.ts
  tools/barista/src/transform.ts
  tools/barista/src/types.ts
  tools/barista/src/utils/fetch-strapi-content.ts
Labels: pr: merge-ready, target: minor, target: patch

#572 barista(color-grid): Added colorlist input to the color-grid.
  apps/barista/src/components/color-grid/color-grid.ts
Labels: pr: merge-ready, target: minor, target: patch

#549 feat(empty-state): Allow custom empty-states
  components/empty-state/README.md
  components/empty-state/src/empty-state-module.ts
  components/empty-state/src/empty-state.ts
  components/table/README.md
  components/table/src/table.html
  components/table/src/table.spec.ts
  libs/examples/src/empty-state/empty-state-custom-empty-state-table-example/empty-state-custom-empty-state-table-example.html
  libs/examples/src/empty-state/empty-state-custom-empty-state-table-example/empty-state-custom-empty-state-table-example.ts
  libs/examples/src/empty-state/empty-state-examples.module.ts
Labels: needs-cherry-pick, pr: merge-ready, target: minor

#522 chore: Enable distributed caching for nx commands.
  .prettierignore
  apps/components-e2e/src/components/chart/chart/chart.ts
  apps/components-e2e/src/components/chart/highcharts/chart-highcharts-ui.ts
  apps/universal-ssr/src/main.ts
  components/autocomplete/src/autocomplete-trigger.ts
  components/breadcrumbs/src/breadcrumbs.ts
  components/button-group/src/button-group.ts
  components/chart/index.ts
  components/chart/src/chart.spec.ts
  components/chart/src/chart.ts
  components/chart/src/range/range.ts
  components/chart/src/selection-area/selection-area.ts
  components/chart/src/selection-area/streams.spec.ts
  components/chart/src/timestamp/timestamp.ts
  components/chart/src/tooltip/chart-tooltip.spec.ts
  components/core/src/overlay/flexible-connected-position-strategy.ts
  components/drawer/src/drawer-container.ts
  components/empty-state/src/empty-state.ts
  components/filter-field/src/filter-field-range/filter-field-range.ts
  components/filter-field/src/filter-field-validation.ts
  components/filter-field/src/filter-field.ts
  components/inline-editor/src/inline-editor.ts
  components/micro-chart/src/micro-chart-util.spec.ts
  components/micro-chart/src/micro-chart.spec.ts
  components/micro-chart/src/micro-chart.ts
  components/pagination/src/pagination-calculate-pages.spec.ts
  components/pagination/src/pagination.spec.ts
  components/radio/src/radio-group.ts
  components/radio/src/radio.spec.ts
  components/schematics/src/ng-add/__snapshots__/ng-add.spec.ts.snap
  components/schematics/src/ng-update/tests/legacy-imports-rule.spec.ts
  components/select/src/select.spec.ts
  components/select/src/select.ts
  components/stepper/src/stepper.spec.ts
  components/table/src/cell.ts
  components/table/src/header/header-cell.ts
  components/tag/src/tag-list/tag-list.ts
  components/toast/src/toast.spec.ts
  components/toggle-button-group/src/toggle-button-group.ts
  libs/examples/src/table/table-show-more-example/table-show-more-example.ts
  nx.json
  package-lock.json
  package.json
  tools/builders/packager/copy-assets.ts
  tools/examples/src/main.ts
  tools/examples/src/metadata.ts
  tools/examples/src/util.ts
  tools/release/src/git/verify-github-status.ts
  tools/release/src/prompts.ts
  tools/release/src/utils/merge-node-streams.ts
  tools/shareable-examples/src/utils/get-component-selector-from-source-file.ts
  tools/shareable-examples/src/utils/get-template-and-style-files-from-component-source-file.ts
  tools/shared/src/utils/ast.ts
Labels: pr: merge-ready, target: minor, target: patch

#553 Fix bounding calculation of tag-list and more button
  apps/components-e2e/src/components/tag-list/tag-list.e2e.ts
  apps/dev/src/tag/tag-demo.component.ts
  components/tag/src/tag-list/tag-list.html
  components/tag/src/tag-list/tag-list.scss
  components/tag/src/tag-list/tag-list.spec.ts
  components/tag/src/tag-list/tag-list.ts
Labels: pr: merge-ready, target: minor, target: patch

#597 chore: Fixes an issue with the custom empty state example.
  libs/examples/src/empty-state/empty-state-custom-empty-state-table-example/empty-state-custom-empty-state-table-example.ts
  libs/examples/src/empty-state/empty-state-examples.module.ts
  tools/shareable-examples/src/utils/get-classname-from-file.spec.ts
  tools/shareable-examples/src/utils/get-classname-from-source-file.ts
  tools/shareable-examples/src/utils/get-component-selector-from-source-file.ts
  tools/shareable-examples/src/utils/get-example-module.ts
Labels: pr: merge-ready, target: minor, target: patch

#598 barista: Fix typo in stackblitz link
  apps/barista/src/components/live-example/live-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#599 chore: Fixes deep link routing in barista-previews.
  .github/workflows/barista-preview.yml
  now-preview.json
Labels: pr: merge-ready, target: minor, target: patch

#527 Update dtNoFocusedTestsRule to check for testcafe e2e fixture.only
  angular.json
  tools/tslint-rules/src/dtAnnotateInternalFieldsRule.ts
  tools/tslint-rules/src/dtDocsImportBaristaRule.ts
  tools/tslint-rules/src/dtDocumentPublicFieldsRule.ts
  tools/tslint-rules/src/dtInternalFieldsUnderscoreRule.ts
  tools/tslint-rules/src/dtNoFocusedTestsRule.ts
  tools/tslint-rules/src/dtRequireLicenseBannerRule.ts
  tools/tslint-rules/src/tsLoaderRule.js
  tools/tslint-rules/src/utils.ts
  tools/tslint-rules/tsconfig.json
  tools/tslint-rules/tslint.json
  tslint.json
Labels: P2, pr: merge-ready, target: minor, target: patch

#385 Refactor/cleanup old dependencies
  .github/CODEOWNERS
  components/schematics/src/ng-update/tests/root-imports.spec.ts
  components/schematics/src/testing/test-app.ts
  package-lock.json
  package.json
  tools/gulp/build-config.ts
  tools/gulp/gulpfile.ts
  tools/gulp/tasks/breaking-changes.ts
  tools/gulp/tasks/clean.ts
  tools/gulp/tasks/schematics.ts
  tools/gulp/tasks/ts-linting-rules.ts
  tools/gulp/tasks/universal.ts
  tools/gulp/tsconfig.json
  tools/gulp/util/examples-metadata.ts
  tools/gulp/util/file-replacer.ts
  tools/gulp/util/metadata-fixer.ts
  tools/gulp/util/ngc-compile.ts
  tools/gulp/util/replace-version-placeholder.ts
  tools/gulp/util/task-runner.ts
  tools/gulp/util/tsc-compile.ts
  tools/tslint-rules/src/dtAnnotateInternalFieldsRule.ts
  tools/tslint-rules/src/dtDocsImportBaristaRule.ts
  tools/tslint-rules/src/dtDocumentPublicFieldsRule.ts
  tools/tslint-rules/src/dtInternalFieldsUnderscoreRule.ts
  tools/tslint-rules/src/dtNoFocusedTestsRule.ts
  tools/tslint-rules/tsconfig.json
Labels: P2, pr: merge-ready, target: minor, target: patch

#604 Add contributors shield to our README.md.
  README.md
Labels: pr: merge-ready, target: minor, target: patch

#612 docs(table): reorganized UX snippets for expandable row.
  components/table/README.md
Labels: pr: merge-ready, pr: needs-cherry-pick

#607 fix(tag-list): Fixes an issue where the taglist did not get updated within a tree table.
  apps/dev/src/tree-table/tree-table-demo.component.html
  apps/dev/src/tree-table/tree-table-demo.component.ts
  components/tag/src/tag-list/tag-list.ts
Labels: pr: merge-ready, target: minor, target: patch

#613 chore: Confirm default options for preview deployment in interactive mode.
  .github/workflows/barista-preview.yml
Labels: pr: merge-ready, target: minor, target: patch

#611 feat(chart): Show crosshair for selection area only over plot background.
  components/chart/src/chart.scss
Labels: pr: merge-ready, target: minor

#605 fix(drawer): Fixes an issue where the drawer backdrop did not overlay breadcrumbs elements.
  components/drawer/src/drawer-container.scss
Labels: pr: merge-ready, target: minor, target: patch

#596 chore(expandable-table): Move expandable cell to the left.
  components/table/src/expandable/expandable-cell.scss
  libs/examples/src/table/table-expandable-rows-example/table-expandable-rows-example.html
  libs/examples/src/table/table-responsive-example/table-responsive-example.html
Labels: pr: merge-ready, target: minor, target: patch

#616 fix(event-chart): Round time labels in x-axis
  components/event-chart/index.ts
  components/event-chart/src/event-chart.spec.ts
  components/event-chart/src/event-chart.ts
Labels: pr: merge-ready, pr: needs-cherry-pick, target: minor, target: patch

#615 refactor(table): Refactored dependencies between the table and the simple columns.
  components/table/src/simple-columns/simple-column-base.ts
  components/table/src/table.ts
Labels: pr: merge-ready, target: minor, target: patch

#610 fix(chart): Fixes an issue with the overlay of the selection area not updating.
  apps/components-e2e/src/components/chart/selection-area/selection-area.e2e.ts
  apps/components-e2e/src/components/chart/selection-area/selection-area.html
  apps/components-e2e/src/components/chart/selection-area/selection-area.po.ts
  apps/components-e2e/src/components/chart/selection-area/selection-area.ts
  apps/dev/src/chart/chart-demo.component.html
  apps/dev/src/chart/chart-demo.component.ts
  components/chart/src/selection-area/selection-area.ts
Labels: pr: merge-ready, target: minor, target: patch

#620 fix(table): Fixes an issue where the sorting did not update when active binding was updated.
  components/table/src/sort/sort.spec.ts
  components/table/src/sort/sort.ts
Labels: pr: merge-ready, target: minor, target: patch

#625 fix(event-chart): Add legend color and pattern for filtered.
  components/event-chart/src/_event-chart-constants.scss
  components/event-chart/src/event-chart-legend.scss
  components/event-chart/src/event-chart.scss
  libs/examples/src/event-chart/event-chart-legend-example/event-chart-legend-example.html
Labels: pr: merge-ready, target: minor, target: patch

#459 feat(context-dialog): Added footer to context dialog.
  apps/components-e2e/src/components/context-dialog/context-dialog.e2e.ts
  components/context-dialog/README.md
  components/context-dialog/src/context-dialog-module.ts
  components/context-dialog/src/context-dialog.html
  components/context-dialog/src/context-dialog.scss
  components/context-dialog/src/context-dialog.spec.ts
  components/context-dialog/src/context-dialog.ts
  components/context-dialog/src/footer/context-dialog-footer.html
  components/context-dialog/src/footer/context-dialog-footer.scss
  components/context-dialog/src/footer/context-dialog-footer.ts
  components/context-dialog/src/header/context-dialog-header.scss
  libs/examples/src/context-dialog/context-dialog-examples.module.ts
  libs/examples/src/context-dialog/context-dialog-footer-example/context-dialog-footer-example.html
  libs/examples/src/context-dialog/context-dialog-footer-example/context-dialog-footer-example.scss
  libs/examples/src/context-dialog/context-dialog-footer-example/context-dialog-footer-example.ts
Labels: pr: merge-ready, target: minor

#622 test(event-chart): Adjusted a path equality test to be less restrictive.
  components/event-chart/src/event-chart.spec.ts
Labels: pr: merge-ready, target: minor, target: patch

#631 barista: Add guidelines to navigation and add descriptions to overvie…
  apps/barista/src/pages/overview-page/overview-page.html
  apps/barista/src/pages/overview-page/overview-page.scss
  tools/barista/src/generators/category-navigation.ts
Labels: pr: merge-ready, target: minor, target: patch

#432 fix: Timestamp/range being re-opened on window resize.
  apps/components-e2e/src/components/chart/selection-area/selection-area.e2e.ts
  components/chart/src/selection-area/selection-area.ts
Labels: pr: merge-ready, pr: needs-cherry-pick, target: minor, target: patch

#630 docs(getting-started): Add manual installation guide again.
  documentation/getting-started.md
Labels: pr: merge-ready, target: minor, target: patch

#635 barista: Add missing dependencies to page builder
  tools/barista/Dockerfile
Labels: pr: merge-ready, target: minor, target: patch

#636 chore(context-dialog): Rename aria-label input for the close button t…
  libs/examples/src/context-dialog/context-dialog-footer-example/context-dialog-footer-example.html
Labels: pr: merge-ready, target: minor, target: patch

#638 fix(drawer): Fixes an issue where drawer backdrop was overlaying the drawer body
  apps/components-e2e/src/components/drawer/drawer.e2e.ts
  apps/components-e2e/src/components/drawer/drawer.html
  apps/components-e2e/src/components/drawer/drawer.scss
  apps/components-e2e/src/components/drawer/drawer.ts
  components/drawer/src/drawer-container.scss
  components/drawer/src/drawer.scss
Labels: P1, bug, pr: merge-ready, target: minor, target: patch

#641 barista: Fix links to contributors github pages on strapi pages.
  apps/barista/src/layout/contributors/contributors.html
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  tools/barista/src/builder/strapi.ts
Labels: pr: merge-ready, target: minor, target: patch

#643 chore(release): Fixes a wrong import in our stage relase script.
  tools/release/src/stage-release/stage-release.ts
Labels: pr: merge-ready, target: minor, target: patch

#645 chore: Bump version to 6.0.0-rc.0 w/ changelog
  CHANGELOG.md
  package-lock.json
  package.json
Labels: target: major

#652 Fixes a regression where the lintrules where missing in the bundle
  tools/linting/tsconfig.json
  tools/linting/tslint.json
Labels: P1, bug

#661 Fixed flaky e2e tests for the radial chart.
  apps/components-e2e/src/components/radial-chart/radial-chart.e2e.ts
Labels: P2

#667 build(bundle): Fixes asset folder not being there
  angular.json
Labels: pr: merge-ready, target: minor, target: patch
