Repository dynatrace-oss/barista, pull requests merged in 2020-10, with the labels that each got.

#1662 fix(quick-filter): Use internal uid for the filter generation.
  apps/components-e2e/src/components/filter-field/filter-field.module.ts
  apps/components-e2e/src/components/quick-filter/quick-filter-async/quick-filter-async.html
  apps/components-e2e/src/components/quick-filter/quick-filter-async/quick-filter-async.ts
  apps/components-e2e/src/components/quick-filter/quick-filter-initial-data/quick-filter-initial-data.html
  apps/components-e2e/src/components/quick-filter/quick-filter-initial-data/quick-filter-initial-data.ts
  apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
  apps/components-e2e/src/components/quick-filter/quick-filter.module.ts
  apps/components-e2e/src/components/quick-filter/quick-filter/quick-filter.ts
  apps/components-e2e/src/components/quick-filter/util.ts
  libs/barista-components/experimental/quick-filter/BUILD.bazel
  libs/barista-components/experimental/quick-filter/src/quick-filter-group.html
  libs/barista-components/experimental/quick-filter/src/quick-filter-group.ts
  libs/barista-components/experimental/quick-filter/src/quick-filter-utils.ts
  libs/barista-components/experimental/quick-filter/src/quick-filter.spec.ts
  libs/barista-components/experimental/quick-filter/src/quick-filter.ts
  libs/barista-components/experimental/quick-filter/src/state/actions.ts
  libs/barista-components/experimental/quick-filter/src/state/effects.ts
  libs/barista-components/experimental/quick-filter/src/state/reducer.spec.ts
  libs/barista-components/experimental/quick-filter/src/state/reducer.ts
  libs/barista-components/experimental/quick-filter/src/state/selectors.ts
  libs/barista-components/experimental/quick-filter/src/state/store.ts
  libs/barista-components/filter-field/index.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#1677 chore(schematics): Cleanup unused files, and correct an error message.
  libs/examples/src/examples.module.template
  libs/examples/src/index.template
  libs/tools/barista/src/main.ts
Labels: pr: merge-ready, target: minor, target: patch

#1676 fix(event-chart): Display human readable time
  apps/dev/src/event-chart/big-time-test-data.ts
  apps/dev/src/event-chart/event-chart-demo.component.ts
  libs/barista-components/event-chart/src/event-chart.spec.ts
  libs/barista-components/event-chart/src/event-chart.ts
Labels: pr: merge-ready, target: minor, target: patch

#1663 chore(fluid-virtual-scroll): Virtual scroll container as web-component.
  angular.json
  apps/fluid-dev/src/app/app.component.html
  apps/fluid-dev/src/app/app.routing.module.ts
  apps/fluid-dev/src/pages/virtual-scroll-container/virtual-scroll-container-page.component.html
  apps/fluid-dev/src/pages/virtual-scroll-container/virtual-scroll-container-page.component.scss
  apps/fluid-dev/src/pages/virtual-scroll-container/virtual-scroll-container-page.component.ts
  apps/fluid-dev/src/pages/virtual-scroll-container/virtual-scroll-container-page.module.ts
  libs/fluid-elements/popover/src/lib/popover.ts
  libs/fluid-elements/virtual-scroll-container/BUILD.bazel
  libs/fluid-elements/virtual-scroll-container/README.md
  libs/fluid-elements/virtual-scroll-container/jest.config.json
  libs/fluid-elements/virtual-scroll-container/package.json
  libs/fluid-elements/virtual-scroll-container/src/index.ts
  libs/fluid-elements/virtual-scroll-container/src/lib/virtual-scroll-container.ts
  libs/fluid-elements/virtual-scroll-container/src/lib/virtual-scroll-events.ts
  libs/fluid-elements/virtual-scroll-container/src/lib/virtual-scroll-state.ts
  libs/fluid-elements/virtual-scroll-container/src/lib/virtual-scroll-utils.spec.ts
  libs/fluid-elements/virtual-scroll-container/src/lib/virtual-scroll-utils.ts
  libs/fluid-elements/virtual-scroll-container/tsconfig.json
  libs/fluid-elements/virtual-scroll-container/tsconfig.lib.json
  libs/fluid-elements/virtual-scroll-container/tsconfig.spec.json
  libs/fluid-elements/virtual-scroll-container/tslint.json
  nx.json
  tsconfig.base.json
Labels: pr: merge-ready, target: minor, target: patch

#1679 fix(chart): Fix dynamic heatfield generation that was not possible.
  apps/components-e2e/src/components/chart/chart.module.ts
  apps/components-e2e/src/components/chart/heatfield/heatfield.e2e.ts
  apps/components-e2e/src/components/chart/heatfield/heatfield.html
  apps/components-e2e/src/components/chart/heatfield/heatfield.ts
  libs/barista-components/chart/src/chart.spec.ts
  libs/barista-components/chart/src/chart.ts
  libs/barista-components/chart/src/heatfield/chart-heatfield.ts
Labels: pr: merge-ready, target: minor, target: patch

#1665 Convert worksapce schematics for nx
  libs/workspace/README.md
  libs/workspace/collection.json
  libs/workspace/src/schematics/dt-component-dev/README.md
  libs/workspace/src/schematics/dt-component-e2e/README.md
  libs/workspace/src/schematics/dt-component-example/README.md
  libs/workspace/tsconfig.json
  libs/workspace/tsconfig.lib.json
  libs/workspace/webpack.config.js
  tools/schematics/dt-component-dev/README.md
  tools/schematics/dt-component-dev/__snapshots__/index.spec.ts.snap
  tools/schematics/dt-component-dev/files/apps/dev/src/__name@dasherize__/__name@dasherize__-demo.component.html
  tools/schematics/dt-component-dev/files/apps/dev/src/__name@dasherize__/__name@dasherize__-demo.component.scss
  tools/schematics/dt-component-dev/files/apps/dev/src/__name@dasherize__/__name@dasherize__-demo.component.ts
  tools/schematics/dt-component-dev/fixtures/alert-demo.component.fixture
  tools/schematics/dt-component-dev/fixtures/app.module.ts.fixture
  tools/schematics/dt-component-dev/fixtures/devapp-routing.module.fixture
  tools/schematics/dt-component-dev/fixtures/devapp.component.ts.fixture
  tools/schematics/dt-component-dev/index.spec.ts
  tools/schematics/dt-component-dev/index.ts
  tools/schematics/dt-component-dev/schema.json
  tools/schematics/dt-component-dev/schema.ts
  tools/schematics/dt-component-e2e/README.md
  tools/schematics/dt-component-e2e/__snapshots__/index.spec.ts.snap
  tools/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.e2e.ts
  tools/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.html
  tools/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.module.ts
  tools/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.po.ts
  tools/schematics/dt-component-e2e/files/apps/components-e2e/src/components/__name@dasherize__/__name@dasherize__.ts
  tools/schematics/dt-component-e2e/fixtures/alert.fixture.ts
  tools/schematics/dt-component-e2e/fixtures/app.routing.module.ts.fixture.ts
  tools/schematics/dt-component-e2e/index.spec.ts
  tools/schematics/dt-component-e2e/index.ts
  tools/schematics/dt-component-e2e/schema.json
  tools/schematics/dt-component-e2e/schema.ts
  tools/schematics/dt-component-example/README.md
  tools/schematics/dt-component-example/__snapshots__/index.spec.ts.snap
  tools/schematics/dt-component-example/example-tools.utils.ts
  tools/schematics/dt-component-example/files/__component@dasherize__-__name@dasherize__-example.html
  tools/schematics/dt-component-example/files/__component@dasherize__-__name@dasherize__-example.ts
  tools/schematics/dt-component-example/fixtures/app-routing.module.ts.fixture
  tools/schematics/dt-component-example/fixtures/examples.module.ts.fixture
  tools/schematics/dt-component-example/fixtures/examplesIndex.ts.fixtures
  tools/schematics/dt-component-example/fixtures/faulty.fixture
  tools/schematics/dt-component-example/fixtures/index.ts.fixture
  tools/schematics/dt-component-example/fixtures/nav-items.ts.fixture
  tools/schematics/dt-component-example/fixtures/test-component-examples.module.ts.fixture
  tools/schematics/dt-component-example/fixtures/test-test-example.fixture
  tools/schematics/dt-component-example/index.spec.ts
  tools/schematics/dt-component-example/index.ts
  tools/schematics/dt-component-example/schema.json
  tools/schematics/dt-component-example/schema.ts
  tools/schematics/utils/ast-utils.ts
  tools/schematics/utils/change.ts
  tools/schematics/utils/common-utils.ts
  tools/schematics/utils/schematics-utils.ts
  tools/schematics/utils/test-utils.ts
  tools/tsconfig.tools.json
Labels: pr: merge-ready, target: minor, target: patch

#1691 chore(barista): Add workaround for PNG icon downloads on Firefox
  apps/barista-design-system/src/components/icon-color-wheel/icon-color-wheel.ts
Labels: pr: merge-ready, target: minor, target: patch

#1694 build(secondary-nav): Bazelify secondary-nav component
  angular.json
  libs/barista-components/secondary-nav/BUILD.bazel
  libs/barista-components/secondary-nav/jest.config.js
  libs/barista-components/secondary-nav/jest.config.json
  libs/barista-components/secondary-nav/tsconfig.json
  libs/barista-components/secondary-nav/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1693 build(progress-circle): Bazelify progress-circle component
  angular.json
  libs/barista-components/progress-circle/BUILD.bazel
  libs/barista-components/progress-circle/jest.config.js
  libs/barista-components/progress-circle/jest.config.json
  libs/barista-components/progress-circle/tsconfig.json
  libs/barista-components/progress-circle/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1692 build(progress-bar): Bazelify progress-bar component
  angular.json
  libs/barista-components/progress-bar/BUILD.bazel
  libs/barista-components/progress-bar/jest.config.js
  libs/barista-components/progress-bar/jest.config.json
  libs/barista-components/progress-bar/tsconfig.json
  libs/barista-components/progress-bar/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1695 build(stacked-series-chart): Bazelify stacked-series-chart component
  angular.json
  libs/barista-components/stacked-series-chart/BUILD.bazel
  libs/barista-components/stacked-series-chart/jest.config.js
  libs/barista-components/stacked-series-chart/jest.config.json
  libs/barista-components/stacked-series-chart/tsconfig.json
  libs/barista-components/stacked-series-chart/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1696 build(stepper): Bazelify stepper component.
  angular.json
  libs/barista-components/stepper/BUILD.bazel
  libs/barista-components/stepper/jest.config.js
  libs/barista-components/stepper/jest.config.json
  libs/barista-components/stepper/tsconfig.json
  libs/barista-components/stepper/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1697 build(sunburst-chart): Bazelify sunburst-chart component.
  angular.json
  libs/barista-components/sunburst-chart/BUILD.bazel
  libs/barista-components/sunburst-chart/jest.config.js
  libs/barista-components/sunburst-chart/jest.config.json
  libs/barista-components/sunburst-chart/tsconfig.json
  libs/barista-components/sunburst-chart/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1702 build(top-bar-navigation): Bazelify top-bar-navigation component
  angular.json
  libs/barista-components/top-bar-navigation/BUILD.bazel
  libs/barista-components/top-bar-navigation/jest.config.js
  libs/barista-components/top-bar-navigation/jest.config.json
  libs/barista-components/top-bar-navigation/tsconfig.json
  libs/barista-components/top-bar-navigation/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1701 build(toggle-button-group): Bazelify toggle-button-group component.
  angular.json
  libs/barista-components/toggle-button-group/BUILD.bazel
  libs/barista-components/toggle-button-group/jest.config.js
  libs/barista-components/toggle-button-group/jest.config.json
  libs/barista-components/toggle-button-group/tsconfig.json
  libs/barista-components/toggle-button-group/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1700 build(toast): Bazelify toast component.
  angular.json
  libs/barista-components/toast/BUILD.bazel
  libs/barista-components/toast/jest.config.js
  libs/barista-components/toast/jest.config.json
  libs/barista-components/toast/tsconfig.json
  libs/barista-components/toast/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1699 build(timeline-chart): Bazelify timeline-chart component.
  angular.json
  libs/barista-components/timeline-chart/BUILD.bazel
  libs/barista-components/timeline-chart/jest.config.js
  libs/barista-components/timeline-chart/jest.config.json
  libs/barista-components/timeline-chart/tsconfig.json
  libs/barista-components/timeline-chart/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1714 barista: Breadcrumbs are no longer work in progress.
  libs/barista-components/breadcrumbs/barista.json
Labels: pr: merge-ready, target: minor, target: patch

#1723 build(drawer-table): Bazelify drawer-table component.
  angular.json
  libs/barista-components/experimental/drawer-table/BUILD.bazel
  libs/barista-components/experimental/drawer-table/jest.config.js
  libs/barista-components/experimental/drawer-table/jest.config.json
  libs/barista-components/experimental/drawer-table/tsconfig.json
  libs/barista-components/experimental/drawer-table/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1717 build(consumption): Bazelify consumption component.
  angular.json
  libs/barista-components/consumption/BUILD.bazel
  libs/barista-components/consumption/jest.config.js
  libs/barista-components/consumption/jest.config.json
  libs/barista-components/consumption/tsconfig.json
  libs/barista-components/consumption/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1708 fix(tree-table): Reverts changes causing unwanted behaviour expanding text on hover
  libs/barista-components/tree-table/README.md
  libs/barista-components/tree-table/src/tree-table-row.scss
  libs/barista-components/tree-table/src/tree-table-toggle-cell.html
  libs/barista-components/tree-table/src/tree-table-toggle-cell.scss
Labels: pr: merge-ready, target: minor, target: patch

#1720 build(show-more): Bazelify show-more component.
  angular.json
  libs/barista-components/show-more/BUILD.bazel
  libs/barista-components/show-more/jest.config.js
  libs/barista-components/show-more/jest.config.json
  libs/barista-components/show-more/tsconfig.json
  libs/barista-components/show-more/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1722 build(combobox): Bazelify combobox component.
  angular.json
  libs/barista-components/experimental/combobox/BUILD.bazel
  libs/barista-components/experimental/combobox/jest.config.js
  libs/barista-components/experimental/combobox/jest.config.json
  libs/barista-components/experimental/combobox/tsconfig.json
  libs/barista-components/experimental/combobox/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1721 build(tree-table): Bazelify tree-table component.
  angular.json
  libs/barista-components/tree-table/BUILD.bazel
  libs/barista-components/tree-table/jest.config.js
  libs/barista-components/tree-table/jest.config.json
  libs/barista-components/tree-table/tsconfig.json
  libs/barista-components/tree-table/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1703 build(slider): Bazelify slider component.
  angular.json
  libs/barista-components/slider/BUILD.bazel
  libs/barista-components/slider/jest.config.js
  libs/barista-components/slider/jest.config.json
  libs/barista-components/slider/src/slider.spec.ts
  libs/barista-components/slider/tsconfig.json
  libs/barista-components/slider/tsconfig.lib.json
Labels: pr: merge-ready, target: minor, target: patch

#1719 build(radial-chart): Bazelify radial-chart component.
  angular.json
  libs/barista-components/radial-chart/BUILD.bazel
  libs/barista-components/radial-chart/jest.config.js
  libs/barista-components/radial-chart/jest.config.json
  libs/barista-components/radial-chart/tsconfig.json
  libs/barista-components/radial-chart/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1718 build(event-chart): Bazelify event-chart component.
  angular.json
  libs/barista-components/event-chart/BUILD.bazel
  libs/barista-components/event-chart/jest.config.js
  libs/barista-components/event-chart/jest.config.json
  libs/barista-components/event-chart/tsconfig.json
  libs/barista-components/event-chart/tsconfig.lib.json
Labels: bazel, pr: merge-ready, target: minor, target: patch

#1716 fix(option): Fixes truncate issue in firefox
  libs/barista-components/autocomplete/src/autocomplete.scss
  libs/barista-components/core/src/option/option.html
  libs/barista-components/core/src/option/option.scss
  libs/barista-components/core/src/option/option.ts
Labels: pr: merge-ready, target: minor, target: patch

#1690 fix(a11y): Fixes flaky combobox a11y test and changes aria attribute in button-group-item
  apps/components-e2e/src/components/button-group/button-group.e2e.ts
  apps/components-e2e/src/components/button-group/button-group.po.ts
  libs/barista-components/button-group/README.md
  libs/barista-components/button-group/src/_button-group-item-theme.scss
  libs/barista-components/button-group/src/button-group.ts
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#1713 feat(quick-filter): Add show more for options.
  apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
  apps/components-e2e/src/components/quick-filter/quick-filter.module.ts
  apps/components-e2e/src/components/quick-filter/quick-filter.po.ts
  libs/barista-components/experimental/quick-filter/README.md
  libs/barista-components/experimental/quick-filter/src/quick-filter-default-data-source.ts
  libs/barista-components/experimental/quick-filter/src/quick-filter-group.html
  libs/barista-components/experimental/quick-filter/src/quick-filter-group.scss
  libs/barista-components/experimental/quick-filter/src/quick-filter-group.ts
  libs/barista-components/experimental/quick-filter/src/quick-filter.html
  libs/barista-components/experimental/quick-filter/src/quick-filter.module.ts
  libs/barista-components/experimental/quick-filter/src/quick-filter.scss
  libs/barista-components/experimental/quick-filter/src/quick-filter.ts
  libs/barista-components/experimental/quick-filter/src/state/actions.ts
  libs/barista-components/experimental/quick-filter/src/state/reducer.ts
  libs/barista-components/experimental/quick-filter/src/state/selectors.ts
  libs/barista-components/experimental/quick-filter/src/state/store.ts
  libs/examples/src/quick-filter/custom-show-more/custom-show-more.html
  libs/examples/src/quick-filter/custom-show-more/custom-show-more.ts
  libs/examples/src/quick-filter/index.ts
  libs/examples/src/quick-filter/quick-filter-default-example/quick-filter-default-example.ts
  libs/examples/src/quick-filter/quick-filter-examples.module.ts
Labels: pr: merge-ready, target: minor, target: patch

#1732 ci: Set build status for master branch
  README.md
Labels: pr: merge-ready, target: minor, target: patch

#1710 refactor(expandable-section): Switch to custom properties for theming.
  libs/barista-components/expandable-section/BUILD.bazel
  libs/barista-components/expandable-section/src/_expandable-section-theme.scss
  libs/barista-components/expandable-section/src/expandable-section.scss
  libs/examples/src/expandable-section/expandable-section-dark-example/expandable-section-dark-example.html
Labels: pr: merge-ready, target: minor, target: patch

#1673 feat(radial-chart): Add interaction to legend
  apps/components-e2e/src/components/radial-chart/radial-chart.e2e.ts
  apps/components-e2e/src/components/radial-chart/radial-chart.po.ts
  libs/barista-components/overlay/src/overlay-trigger.ts
  libs/barista-components/radial-chart/README.md
  libs/barista-components/radial-chart/src/radial-chart-path.html
  libs/barista-components/radial-chart/src/radial-chart-path.ts
  libs/barista-components/radial-chart/src/radial-chart-series.ts
  libs/barista-components/radial-chart/src/radial-chart.html
  libs/barista-components/radial-chart/src/radial-chart.scss
  libs/barista-components/radial-chart/src/radial-chart.ts
Labels: pr: merge-ready, target: minor

#1743 fix(context-dialog): Focuses the first tabbable element inside the overlay con…
  libs/barista-components/context-dialog/src/context-dialog.html
  libs/barista-components/context-dialog/src/context-dialog.ts
Labels: pr: merge-ready, target: minor, target: patch

#1741 fix(table, tree-table, stepper): Fixes breaking changes from @angular/cdk
  libs/barista-components/stepper/src/stepper.ts
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#1755 fix(quick-filter): Fixes a bug that didn't show any options when the …
  libs/barista-components/experimental/quick-filter/src/quick-filter.ts
Labels: pr: merge-ready, target: minor, target: patch

#1749 Ci/check cache hits
  .buildkite/baristaPipeline.yml
  .buildkite/baristacli.py
  postinstall.js
Labels: pr: merge-ready, target: minor, target: patch

#1758 ci: Build with bazel on windows
  .buildkite/baristaPipeline.yml
Labels: pr: merge-ready, target: minor, target: patch

#1759 ci: Speed up build because package-lock.json has changes after build.…
  package-lock.json
Labels: pr: merge-ready, target: minor, target: patch

#1768 ci: Shutdown bazel server after build on windows
  .buildkite/baristaPipeline.yml
Labels: pr: merge-ready, target: minor, target: patch

#1765 chore(quickfilter): Unify example structure of quickfilter to match guidelines.
  apps/components-e2e/src/components/quick-filter/quick-filter.module.ts
  apps/demos/src/app-routing.module.ts
  apps/demos/src/barista-examples.a11y.ts
  apps/demos/src/nav-items.ts
  libs/examples/src/index.ts
  libs/examples/src/quick-filter/BUILD.bazel
  libs/examples/src/quick-filter/index.ts
  libs/examples/src/quick-filter/quick-filter-custom-show-more-example/quick-filter-custom-show-more-example.html
  libs/examples/src/quick-filter/quick-filter-custom-show-more-example/quick-filter-custom-show-more-example.ts
  libs/examples/src/quick-filter/quick-filter-examples.module.ts
Labels: pr: merge-ready, target: minor, target: patch

#1767 feat(quick-filter): Make the quick filter component stable.
  angular.json
  apps/components-e2e/src/components/quick-filter/BUILD.bazel
  apps/components-e2e/src/components/quick-filter/quick-filter-async/quick-filter-async.ts
  apps/components-e2e/src/components/quick-filter/quick-filter-initial-data/quick-filter-initial-data.ts
  apps/components-e2e/src/components/quick-filter/quick-filter.module.ts
  apps/components-e2e/src/components/quick-filter/quick-filter/quick-filter.ts
  apps/universal/src/app/barista.module.ts
  apps/universal/src/app/kitchen-sink/kitchen-sink.ts
  libs/barista-components/config.bzl
  libs/barista-components/experimental/quick-filter/tslint.json
  libs/barista-components/quick-filter/BUILD.bazel
  libs/barista-components/quick-filter/README.md
  libs/barista-components/quick-filter/barista.json
  libs/barista-components/quick-filter/index.ts
  libs/barista-components/quick-filter/jest.config.json
  libs/barista-components/quick-filter/package.json
  libs/barista-components/quick-filter/src/quick-filter-data-source.ts
  libs/barista-components/quick-filter/src/quick-filter-default-data-source.ts
  libs/barista-components/quick-filter/src/quick-filter-group.html
  libs/barista-components/quick-filter/src/quick-filter-group.scss
  libs/barista-components/quick-filter/src/quick-filter-group.ts
  libs/barista-components/quick-filter/src/quick-filter-utils.ts
  libs/barista-components/quick-filter/src/quick-filter.html
  libs/barista-components/quick-filter/src/quick-filter.module.ts
  libs/barista-components/quick-filter/src/quick-filter.scss
  libs/barista-components/quick-filter/src/quick-filter.spec.ts
  libs/barista-components/quick-filter/src/quick-filter.ts
  libs/barista-components/quick-filter/src/state/actions.ts
  libs/barista-components/quick-filter/src/state/effects.ts
  libs/barista-components/quick-filter/src/state/reducer.ts
  libs/barista-components/quick-filter/src/state/selectors.ts
  libs/barista-components/quick-filter/src/state/store.ts
  libs/barista-components/quick-filter/src/test-setup.ts
  libs/barista-components/quick-filter/tsconfig.json
  libs/barista-components/quick-filter/tsconfig.lib.json
  libs/barista-components/quick-filter/tsconfig.spec.json
  libs/barista-components/quick-filter/tslint.json
  libs/examples/src/quick-filter/BUILD.bazel
  libs/examples/src/quick-filter/quick-filter-custom-show-more-example/quick-filter-custom-show-more-example.ts
  libs/examples/src/quick-filter/quick-filter-default-example/quick-filter-default-example.ts
  libs/examples/src/quick-filter/quick-filter-examples.module.ts
  tsconfig.base.json
Labels: pr: merge-ready, target: minor

#1770 chore(tag): Adjust remove tag example to be more interactive.
  libs/examples/src/tag/tag-removable-example/tag-removable-example.html
  libs/examples/src/tag/tag-removable-example/tag-removable-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#1771 build: Bump Angular to 10.2
  WORKSPACE
  package-lock.json
  package.json
  patches/@angular+bazel+10.0.6.patch
Labels: pr: merge-ready, target: minor, target: patch
