Repository dynatrace-oss/barista, pull requests merged in 2020-12, with the labels that each got.

#1853 feat(highlight): Switched theming to custom properties.
  apps/dev/src/highlight/highlight-demo.component.html
  apps/dev/src/main.scss
  libs/barista-components/highlight/BUILD.bazel
  libs/barista-components/highlight/src/_highlight-theme.scss
  libs/barista-components/highlight/src/highlight.scss
Labels: pr: merge-ready, target: minor

#1856 feat(form-field): Switched theming to custom properties.
  apps/dev/src/form-field/form-field-demo.component.html
  libs/barista-components/form-field/BUILD.bazel
  libs/barista-components/form-field/src/_form-field-theme.scss
  libs/barista-components/form-field/src/form-field.scss
Labels: pr: merge-ready, target: minor

#1855 feat(toggle-button-group): Switched theming to custom properties.
  libs/barista-components/toggle-button-group/BUILD.bazel
  libs/barista-components/toggle-button-group/src/_toggle-button-item-theme.scss
  libs/barista-components/toggle-button-group/src/toggle-button-item.scss
Labels: pr: merge-ready, target: minor

#1854 feat(tabs): Switched theming to custom properties.
  libs/barista-components/tabs/BUILD.bazel
  libs/barista-components/tabs/src/_tab-group-theme.scss
  libs/barista-components/tabs/src/tab-group.scss
Labels: pr: merge-ready, target: minor

#1857 fix(drawer): Fixes an issue where changeDetection was not triggered.
  libs/barista-components/drawer/src/drawer.ts
Labels: pr: merge-ready, target: minor, target: patch

#1851 feat(quick-filter): Expose the filter-field loading through the quickfilter.
  libs/barista-components/quick-filter/README.md
  libs/barista-components/quick-filter/src/quick-filter.html
  libs/barista-components/quick-filter/src/quick-filter.ts
Labels: pr: merge-ready, target: minor

#1840 feat: Custom properties for row(s).
  libs/barista-components/table/src/_row-theme.scss
  libs/barista-components/table/src/expandable/_expandable-row-theme.scss
  libs/barista-components/table/src/expandable/expandable-row.scss
  libs/barista-components/table/src/row.scss
  libs/barista-components/tree-table/BUILD.bazel
  libs/barista-components/tree-table/src/_tree-table-row-theme.scss
  libs/barista-components/tree-table/src/tree-table-row.scss
Labels: pr: merge-ready, target: minor

#1861 fix(checkbox): Removes outside spacing on the right of the label.
  libs/barista-components/checkbox/src/checkbox.scss
Labels: pr: merge-ready, target: minor, target: patch

#1860 fix(table): Fixes an issue with a ViewContainer error on destroy.
  libs/barista-components/table/src/table.ts
Labels: pr: merge-ready, target: minor, target: patch

#1852 Fix quickfilter overflowing
  libs/barista-components/quick-filter/src/quick-filter.scss
Labels: pr: merge-ready, target: minor, target: patch

#1850 barista: New search ui and adaption to new search endpoint.
  apps/barista-design-system/src/app/app.module.ts
  apps/barista-design-system/src/app/components/search/index.ts
  apps/barista-design-system/src/app/components/search/search-result-item.html
  apps/barista-design-system/src/app/components/search/search-result-item.scss
  apps/barista-design-system/src/app/components/search/search-result-item.ts
  apps/barista-design-system/src/app/components/search/search.html
  apps/barista-design-system/src/app/components/search/search.scss
  apps/barista-design-system/src/app/components/search/search.ts
  apps/barista-design-system/src/shared/services/search.service.ts
  libs/shared/design-system/interfaces/src/lib/barista/barista-backend-api-definitions.ts
Labels: pr: merge-ready, target: minor, target: patch

#1862 chore: Removed lit-plugin from vscode extension recommendations.
  .vscode/extensions.json
Labels: pr: merge-ready, target: minor, target: patch

#1863 fix(context-dialog): Fixes a weird combination of our interal overlay…
  libs/barista-components/context-dialog/src/context-dialog.ts
Labels: pr: merge-ready, target: minor, target: patch

#1868 fix(combobox): Fixes an issue with programmatic setting of the value to null.
  apps/components-e2e/src/components/combobox/combobox.e2e.ts
  apps/components-e2e/src/components/combobox/combobox.html
  apps/components-e2e/src/components/combobox/combobox.po.ts
  apps/components-e2e/src/components/combobox/combobox.ts
  libs/barista-components/experimental/combobox/src/combobox.ts
Labels: pr: merge-ready, target: minor, target: patch

#1869 fix(chart): Fixes an edge case where the event data from highcharts c…
  libs/barista-components/chart/src/chart.ts
  libs/barista-components/chart/src/tooltip/chart-tooltip.ts
Labels: pr: merge-ready, target: minor, target: patch

#1871 fix(expandable-section): Fixes an issue where nesting expandable sections resulted in wrong visual state.
  libs/barista-components/expandable-section/src/expandable-section.scss
  libs/barista-components/expandable-section/src/expandable-section.ts
Labels: pr: merge-ready, target: minor, target: patch

#1875 fix(radial-chart): Set cursor pointer on hover
  libs/barista-components/radial-chart/src/radial-chart-path.scss
Labels: pr: merge-ready, target: minor, target: patch

#1874 feat(core): Adjusted warning, error and recovered colors to be more accessible.
  libs/barista-components/core/src/style/_variables.scss
  libs/barista-components/style/main.scss
  libs/barista-components/style/themes.scss
Labels: pr: merge-ready, target: minor

#1876 feat(table, tree-table): Increase width of row indicator to improve v…
  libs/barista-components/core/src/style/_table.scss
  libs/barista-components/table/src/_table-mixins.scss
  libs/barista-components/tree-table/src/tree-table-row.scss
  libs/barista-components/tree-table/src/tree-table-toggle-cell.scss
Labels: pr: merge-ready, target: minor

#1873 fix(quick filter): Selected option get lost if they are not within max items size
  apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
  apps/dev/src/app.module.ts
  apps/dev/src/devapp-routing.module.ts
  apps/dev/src/devapp.component.ts
  apps/dev/src/dt-components.module.ts
  apps/dev/src/quick-filter/quick-filter-demo.component.html
  apps/dev/src/quick-filter/quick-filter-demo.component.scss
  apps/dev/src/quick-filter/quick-filter-demo.component.ts
  libs/barista-components/quick-filter/src/quick-filter-group.ts
Labels: pr: needs-cherry-pick

#1881 fix(combobox): Fixes an issue where an exception was thrown when load…
  libs/barista-components/experimental/combobox/src/combobox.spec.ts
  libs/barista-components/experimental/combobox/src/combobox.ts
Labels: pr: merge-ready, target: minor, target: patch

#1882 chore: Delay snyk yargs warning until angular 11 upgrade.
  .snyk
Labels: pr: merge-ready, target: minor, target: patch

#1859 feat(filter-field): Interaction-state
  apps/dev/src/filter-field/filter-field-demo.component.ts
  libs/barista-components/filter-field/README.md
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
  libs/examples/src/filter-field/BUILD.bazel
  libs/examples/src/filter-field/filter-field-unique-example/filter-field-unique-example.ts
Labels: pr: merge-ready, target: minor
