Repository dynatrace-oss/barista, pull requests merged in 2020-06, with the labels that each got.

#1095 docs(info-group): Removes outdated `dt-info-group-content`
  libs/barista-components/info-group/README.md
Labels: documentation, pr: merge-ready, target: minor, target: patch

#1092 build: Update editorconfig to reflect the bazel styleguide.
  .editorconfig
  .gitignore
Labels: pr: merge-ready, target: minor, target: patch

#1090 chore: Remove lodash imports.
  apps/barista-design-system/src/pages/decision-graph-page/components/ba-decision-graph/ba-decision-graph-node/ba-decision-graph-node.ts
  apps/barista-design-system/src/pages/decision-graph-page/components/ba-decision-graph/ba-decision-graph.ts
  apps/design-tokens-ui/src/services/palette/palette-source.service.ts
  apps/dev/src/micro-chart/micro-chart-demo.component.ts
  libs/tools/linting/tslint-self.json
  libs/workspace/tslint.json
  tslint.json
Labels: pr: merge-ready, target: minor, target: patch

#1084 feat(button-group): Changed styling to custom properties.
  libs/barista-components/button-group/src/_button-group-item-theme.scss
  libs/barista-components/button-group/src/button-group-item.scss
Labels: pr: merge-ready, target: minor

#1105 fix(filter-field): Fixes an issue where the range caused an error after its destruction.
  libs/barista-components/filter-field/src/filter-field-range/filter-field-range-trigger.ts
Labels: pr: merge-ready, target: minor, target: patch

#1107 fix(button): Increases specificity even more on links since source or…
  libs/barista-components/button/src/_button-theme.scss
Labels: pr: merge-ready, target: minor, target: patch

#1098 fix(filter-field): Fixes an issue where tags where not disabled when the filter-field was.
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.html
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.ts
  libs/barista-components/filter-field/src/filter-field.html
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#1106 ci: Add rollup rule for bazel
  .vscode/settings.json
  libs/workspace/src/builders/barista-build/BUILD.bazel
  libs/workspace/src/builders/barista-build/renderer.ts
  package-lock.json
  package.json
  tools/bazel_rules/BUILD.bazel
  tools/bazel_rules/helpers.bzl
  tools/bazel_rules/index.bzl
  tools/bazel_rules/rollup/BUILD.bazel
  tools/bazel_rules/rollup/rollup.bzl
  tools/bazel_rules/rollup/rollup.config.js
Labels: bazel 🥦, pr: merge-ready, target: minor, target: patch

#1108 chore: Simplify changelog concatenation and fix synchronizing bug
  libs/tools/release/src/changelog/changelog.spec.ts
  libs/tools/release/src/changelog/changelog.ts
  libs/tools/release/src/changelog/get-new-changelog.ts
  libs/tools/release/src/utils/concatenate-node-streams.spec.ts
  libs/tools/release/src/utils/concatenate-node-streams.ts
Labels: pr: merge-ready, target: minor, target: patch

#1112 chore: Add HttpClientModule when running ng-add schematic.
  libs/barista-components/schematics/src/ng-add/__snapshots__/ng-add.spec.ts.snap
  libs/barista-components/schematics/src/ng-add/rules/update-ng-module-rule.ts
Labels: pr: merge-ready, target: minor, target: patch

#1123 fix(confirmation-dialog): Fixes an issue that focusAttention needs ma…
  libs/barista-components/confirmation-dialog/src/confirmation-dialog.ts
Labels: pr: merge-ready, target: minor, target: patch

#1124 feat(dependencies): Increases version range of supported barista-icon…
  libs/barista-components/package.json
Labels: pr: merge-ready, target: minor

#1130 fix(event-chart): Fixes an issue that the event chart was falsly gett…
  libs/barista-components/event-chart/src/event-chart-module.ts
  libs/barista-components/event-chart/src/event-chart.ts
Labels: pr: merge-ready, target: minor, target: patch

#1115 chore(ci): Add initial CI setup with Bazel
  .bazelrc
  .circleci/config.yml
  package.json
  tools/bazel_build_cache/cache-write-key.json.enc
  tools/bazel_build_cache/setup_ci_build_cache.sh
Labels: bazel 🥦, pr: merge-ready, target: minor, target: patch

#1145 build: Add cache version environment variable to the cache
  .circleci/config.yml
Labels: pr: merge-ready, target: minor, target: patch

#1128 feat(formatters): Exposed formatted display unit in DtFormattedValue.
  libs/barista-components/formatters/src/formatted-value.ts
Labels: pr: needs-cherry-pick

#1133 Added support for checkbox/switch as a form-field-control.
  apps/dev/src/checkbox/checkbox-demo.component.html
  apps/dev/src/switch/switch-demo.component.html
  libs/barista-components/checkbox/src/checkbox.html
  libs/barista-components/checkbox/src/checkbox.ts
  libs/barista-components/form-field/src/form-field-control.ts
  libs/barista-components/form-field/src/form-field.scss
  libs/barista-components/form-field/src/form-field.ts
  libs/barista-components/switch/src/switch.html
  libs/barista-components/switch/src/switch.ts
  libs/examples/src/index.ts
Labels: pr: merge-ready, target: minor

#1151 chore(design-tokens): Build additional metadata for consumption by the Design Tokens UI.
  angular.json
  libs/shared/design-tokens/generated/aliases/base-color.alias.json
  libs/shared/design-tokens/generated/aliases/font.alias.json
  libs/shared/design-tokens/generated/aliases/palette.alias.json
  libs/shared/design-tokens/generated/aliases/spacing.alias.json
  libs/shared/design-tokens/generated/aliases/typography.alias.json
  libs/workspace/src/builders/design-tokens/build/build.ts
  libs/workspace/src/builders/design-tokens/build/schema.json
  libs/workspace/src/builders/design-tokens/build/schema.ts
Labels: pr: merge-ready, target: minor, target: patch

#1150 ci: Try to import bazelrc.user if exists.
  .bazelrc
Labels: bazel 🥦, pr: merge-ready, target: minor, target: patch

#1163 chore: Fix module boundaries rules for library dependencies and restrict shared imports
  tslint.json
Labels: pr: merge-ready, target: minor, target: patch

#1153 radio: Added support for form-field
  apps/dev/src/radio/radio-demo.component.html
  libs/barista-components/radio/src/radio-group.ts
  libs/barista-components/radio/src/radio.html
  libs/barista-components/radio/src/radio.ts
Labels: pr: merge-ready, target: minor

#1165 fix(table): Reorder input being cut off in Firefox.
  libs/barista-components/table/src/order/order-cell.scss
Labels: pr: needs-cherry-pick

#1164 chore: Bump compatibility of barista-icons pack
  libs/barista-components/package.json
Labels: pr: merge-ready, target: minor

#1077 feat(alert): Changes styling to use custom properties.
  libs/barista-components/alert/src/_alert-theme.scss
  libs/barista-components/alert/src/alert.scss
Labels: pr: merge-ready, target: minor

#1167 docs(form-field): Added Sections for supported barista and custom controls.
  libs/barista-components/form-field/README.md
  libs/examples/src/form-field/form-field-examples.module.ts
  libs/examples/src/form-field/form-field-non-box-control-example/form-field-non-box-control-example.html
  libs/examples/src/form-field/form-field-non-box-control-example/form-field-non-box-control-example.ts
  libs/examples/src/form-field/index.ts
  libs/examples/src/index.ts
Labels: documentation, pr: merge-ready, target: minor, target: patch

#1171 chore: Use later node source to download nodejs.
  .deployment/k8s-barista-builder/Dockerfile
Labels: pr: merge-ready, target: minor, target: patch

#1174 barista: Fixes an issue with code highlighting in examples.
  angular.json
Labels: pr: merge-ready, target: minor, target: patch

#1172 build: Remove stale labels when approvals are dismissed due to update.
  tools/pull-request-labeler/src/main.ts
  tools/pull-request-labeler/src/utils/get-approval-count.ts
  tools/pull-request-labeler/src/utils/get-pull-request-reviews.ts
Labels: pr: merge-ready, target: minor, target: patch

#1111 chore: Added spacing css outlet for design tokens
  libs/shared/design-tokens/generated/global/spacing.css
  libs/shared/design-tokens/generated/global/spacing.json
  libs/shared/design-tokens/generated/global/typography.css
  libs/shared/design-tokens/generated/global/typography.json
  libs/shared/design-tokens/generated/global/typography.scss
  libs/shared/design-tokens/src/lib/global/spacing.yml
  libs/shared/design-tokens/src/lib/global/typography.yml
  libs/workspace/src/builders/design-tokens/build/build.ts
  libs/workspace/src/builders/design-tokens/build/token-converters/dt-css-spacing.ts
  libs/workspace/src/builders/design-tokens/build/token-converters/index.ts
Labels: pr: merge-ready, target: minor, target: patch

#1168 build: Skip labeler on fork pull requests.
  .github/workflows/pull-request-labeler.yml
Labels: pr: merge-ready, target: minor, target: patch

#1118 build: Add windows install, build and test checks
  .circleci/config.yml
  libs/tools/release/src/publish-release/publish-release.spec.ts
  libs/tools/release/src/utils/publish-package.spec.ts
  libs/workspace/src/builders/barista-build/renderer.spec.ts
  libs/workspace/src/builders/barista-build/utils/start-server.spec.ts
  libs/workspace/src/builders/typescript/index.ts
  libs/workspace/src/scripts/run-parallel.ts
Labels: pr: merge-ready, target: minor, target: patch

#1069 Feat/radial chart relative values
  .github/CODEOWNERS
  apps/components-e2e/src/components/radial-chart/radial-chart.e2e.ts
  apps/components-e2e/src/components/radial-chart/radial-chart.html
  apps/components-e2e/src/components/radial-chart/radial-chart.po.ts
  apps/components-e2e/src/components/radial-chart/radial-chart.ts
  apps/dev/src/radial-chart/radial-chart-demo.component.html
  apps/dev/src/radial-chart/radial-chart-demo.component.scss
  apps/dev/src/radial-chart/radial-chart-demo.component.ts
  libs/barista-components/radial-chart/README.md
  libs/barista-components/radial-chart/barista.json
  libs/barista-components/radial-chart/src/radial-chart-module.ts
  libs/barista-components/radial-chart/src/radial-chart-path.html
  libs/barista-components/radial-chart/src/radial-chart-path.scss
  libs/barista-components/radial-chart/src/radial-chart-path.ts
  libs/barista-components/radial-chart/src/radial-chart-series.ts
  libs/barista-components/radial-chart/src/radial-chart.html
  libs/barista-components/radial-chart/src/radial-chart.scss
  libs/barista-components/radial-chart/src/radial-chart.spec.ts
  libs/barista-components/radial-chart/src/radial-chart.ts
  libs/barista-components/radial-chart/src/utils/radial-chart-interfaces.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.html
  libs/barista-components/sunburst-chart/src/sunburst-chart.ts
  libs/examples/src/radial-chart/radial-chart-examples.module.ts
  libs/examples/src/radial-chart/radial-chart-legend-example/radial-chart-legend-example.html
  libs/examples/src/radial-chart/radial-chart-legend-example/radial-chart-legend-example.scss
  libs/examples/src/radial-chart/radial-chart-legend-example/radial-chart-legend-example.ts
Labels: pr: needs-cherry-pick

#1176 Chore/fluid checkbox
  angular.json
  apps/fluid-dev/src/app/app.component.html
  apps/fluid-dev/src/app/app.component.scss
  apps/fluid-dev/src/app/app.routing.module.ts
  apps/fluid-dev/src/pages/checkbox/checkbox-page.component.html
  apps/fluid-dev/src/pages/checkbox/checkbox-page.component.scss
  apps/fluid-dev/src/pages/checkbox/checkbox-page.component.ts
  apps/fluid-dev/src/pages/checkbox/checkbox-page.module.ts
  libs/fluid-elements/checkbox/.stylelintrc
  libs/fluid-elements/checkbox/README.md
  libs/fluid-elements/checkbox/jest.config.js
  libs/fluid-elements/checkbox/src/index.ts
  libs/fluid-elements/checkbox/src/lib/checkbox.scss
  libs/fluid-elements/checkbox/src/lib/checkbox.spec.ts
  libs/fluid-elements/checkbox/src/lib/checkbox.ts
  libs/fluid-elements/checkbox/tsconfig.json
  libs/fluid-elements/checkbox/tsconfig.lib.json
  libs/fluid-elements/checkbox/tsconfig.spec.json
  libs/fluid-elements/checkbox/tslint.json
  libs/shared/design-tokens/generated/global/typography.css
  libs/shared/design-tokens/generated/global/typography.json
  libs/shared/design-tokens/generated/global/typography.scss
  libs/shared/design-tokens/src/lib/global/typography.yml
  libs/workspace/src/builders/design-tokens/build/token-converters/dt-css-typography.ts
  libs/workspace/src/builders/design-tokens/build/token-converters/dt-scss-typography.ts
  nx.json
  tsconfig.json
Labels: next, pr: merge-ready, target: minor, target: patch

#1183 fix(quickfilter): Fixes an issue where the content received a scrollb…
  libs/barista-components/experimental/quick-filter/src/quick-filter.scss
Labels: pr: merge-ready, target: minor, target: patch

#1200 ci(e2e): Change e2e tests to run on circle for now
  .circleci/config.yml
Labels: pr: merge-ready, target: minor, target: patch

#1110 feat(scroll-spy): Refactor
  apps/barista-design-system/src/app/app.ts
  apps/barista-design-system/src/components/components.module.ts
  apps/barista-design-system/src/pages/single-page/components/toc/toc.html
  apps/barista-design-system/src/pages/single-page/components/toc/toc.scss
  apps/barista-design-system/src/pages/single-page/components/toc/toc.ts
  apps/barista-design-system/src/pages/single-page/single-page.html
  apps/barista-design-system/src/pages/single-page/single-page.module.ts
  apps/barista-design-system/src/pages/single-page/single-page.ts
  apps/barista-design-system/src/shared/services/scroll-spy.service.ts
  apps/barista-design-system/src/shared/services/toc.service.ts
  apps/barista-design-system/src/utils/create-component.ts
  apps/barista-design-system/tsconfig.json
  libs/shared/barista-definitions/src/lib/barista-definitions.ts
  libs/tools/barista/src/builder/components.ts
  libs/tools/barista/src/transform.spec.ts
  libs/tools/barista/src/transform.ts
Labels: pr: merge-ready, target: minor, target: patch

#1193 Fix changedetection issue simple order column
  apps/dev/src/table-order/table-order-demo.component.html
  libs/barista-components/table/README.md
  libs/barista-components/table/src/simple-columns/simple-order-column.ts
  libs/examples/src/table/table-order-column-example/table-order-column-example.html
  libs/examples/src/table/table-order-expandable-example/table-order-expandable-example.html
  libs/examples/src/table/table-order-observable-example/table-order-observable-example.html
Labels: pr: merge-ready, target: minor, target: patch

#1204 fix(button): Fixes an issue where visited a[dt-button] components had the wrong style.
  libs/barista-components/button/src/_button-theme.scss
Labels: pr: merge-ready, target: minor, target: patch

#1208 chore: Rename list variables
  apps/demos/src/barista-examples.a11y.ts
  libs/fluid-elements/jest.config.js
  libs/testing/custom-element/jest.config.js
  libs/workspace/src/scripts/run-parallel.ts
Labels: pr: merge-ready, target: minor, target: patch
