Repository dynatrace-oss/barista, pull requests merged in 2020-04, with the labels that each got.

#795 Docker build for internal barista speedup
  .circleci/config.yml
  .deployment/barista/Jenkinsfile
  .deployment/barista/barista-internal.Dockerfile
  .deployment/barista/k8s-barista-builder.Dockerfile
  .deployment/barista/nginx/nginx.conf
  .deployment/barista/nginx/sites-available/barista-internal.conf
  .deployment/entrypoint.sh
  .deployment/workspace-base.Dockerfile
  .dockerignore
  angular.json
  entrypoint.sh
  environments/barista-environment.ci.ts
Labels: design-system, pr: merge-ready, target: minor, target: patch

#793 ci(slack-release-notifier): Send automatic Slack notifications on release
  .github/workflows/slack-release-notifier.yml
  tools/slack-release-notifier/.dockerignore
  tools/slack-release-notifier/.gitignore
  tools/slack-release-notifier/Dockerfile
  tools/slack-release-notifier/entrypoint.sh
  tools/slack-release-notifier/package-lock.json
  tools/slack-release-notifier/package.json
  tools/slack-release-notifier/src/main.ts
  tools/slack-release-notifier/src/utils/convert-to-mrkdwn.ts
  tools/slack-release-notifier/src/utils/fancify-text.ts
  tools/slack-release-notifier/src/utils/release-type.ts
  tools/slack-release-notifier/tsconfig.json
  tools/slack-release-notifier/tslint.json
Labels: pr: merge-ready, target: minor, target: patch

#814 Change build target of barista to the server side rendering
  .circleci/config.yml
  .github/workflows/barista-preview.yml
  angular.json
Labels: design-system, pr: merge-ready, target: minor, target: patch

#818 ci: Increase the time for stale issues
  .github/workflows/stale.yml
Labels: pr: merge-ready, target: minor, target: patch

#822 ci: Build and Publish docker image in a separate workflow.
  .circleci/config.yml
Labels: P1, pr: merge-ready, target: minor, target: patch

#821 chore: Upgrades angular, tslint, ng-packagr, and everything connected
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#824 ci: Build the k8s-barista-builder on the internal jenkins.
  .deployment/k8s-barista-builder/Dockerfile
  .deployment/k8s-barista-builder/Jenkinsfile
Labels: design-system, pr: merge-ready, target: minor, target: patch

#819 barista: Build barista with the internal configuration file.
  .deployment/barista/Jenkinsfile
  angular.json
Labels: design-system, pr: merge-ready, target: minor, target: patch

#823 barista(search): Fixes an issue with search on overview pages.
  apps/barista-design-system/src/app/components/search/search.ts
  apps/barista-design-system/src/pages/overview-page/overview-page.ts
  apps/barista-design-system/src/shared/services/search.service.ts
Labels: pr: merge-ready, target: minor, target: patch

#834 barista: Fix recursion in production internal build target.
  angular.json
Labels: pr: merge-ready, target: minor, target: patch

#815 feat(overlay): use full screen overlay container
  libs/barista-components/overlay/README.md
  libs/barista-components/overlay/src/overlay-module.ts
  libs/examples/src/overlay/index.ts
  libs/examples/src/overlay/overlay-examples.module.ts
  libs/examples/src/overlay/overlay-fullscreen-example/overlay-fullscreen-example.html
  libs/examples/src/overlay/overlay-fullscreen-example/overlay-fullscreen-example.scss
  libs/examples/src/overlay/overlay-fullscreen-example/overlay-fullscreen-example.ts
Labels: pr: needs-cherry-pick

#826 docs(getting-started): Add a prototype section
  documentation/getting-started.md
Labels: pr: merge-ready, target: minor, target: patch

#837 fix(filter-field): Fixes an issue where the currentFilterChange event…
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#816 feat(chart-heatfield): Chart Heatfield Overlay should have a close bu…
  libs/barista-components/chart/src/heatfield/chart-heatfield.html
  libs/barista-components/chart/src/heatfield/chart-heatfield.scss
  libs/barista-components/chart/src/heatfield/chart-heatfield.spec.ts
  libs/barista-components/chart/src/heatfield/chart-heatfield.ts
Labels: pr: needs-cherry-pick

#841 ci: Make gorilla more chill
  .github/workflows/slack-barista-production-promotion.yml
Labels: pr: merge-ready, target: minor, target: patch

#805 barista: Fixes an issue where the overview pages where not built.
  libs/tools/barista/src/builder/homepage.ts
  libs/tools/barista/src/main.ts
Labels: design-system, pr: merge-ready, target: minor, target: patch

#852 ci(barista-preview): Update node_modules if the sha1sum does not match.
  .deployment/entrypoint.sh
  .github/workflows/barista-preview.yml
Labels: pr: merge-ready, target: minor, target: patch

#851 Fixes an issue where the internal icon pack was not displayed in barista
  .deployment/barista/Jenkinsfile
Labels: pr: merge-ready, target: minor, target: patch

#856 ci: Use string compare instead of the built in sha1sum compare.
  .deployment/entrypoint.sh
  .github/workflows/barista-preview.yml
Labels: pr: merge-ready, target: minor, target: patch

#855 chore: Update generated examples files to include all expamples
  libs/examples/src/index.ts
Labels: pr: merge-ready, target: minor, target: patch

#849 fix(filter-field): Fixes an issue where two filterfield flaps were open at the same time.
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#859 barista: Fix sonar violation for link rel not containing noreferrer
  apps/barista-design-system/src/components/live-example/live-example.html
Labels: pr: merge-ready, target: minor, target: patch

#633 chore: Added concepts for design tokens and web components.
  concepts/design-tokens/README.md
  concepts/web-components/README.md
Labels: next, pr: merge-ready, target: minor, target: patch

#854 fix(filter-field): Fixes a bug where the range overlay was not closed.
  apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
  apps/components-e2e/src/components/filter-field/filter-field.po.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#771 feat(chart): Added support for observable as input for options
  libs/barista-components/chart/README.md
  libs/barista-components/chart/src/chart.spec.ts
  libs/barista-components/chart/src/chart.ts
Labels: pr: needs-cherry-pick

#844 Moved the existing builders from the tools/builders to the workspace.
  .deployment/barista/Jenkinsfile
  .deployment/k8s-barista-builder/Dockerfile
  .deployment/workspace-base.Dockerfile
  .dockerignore
  .github/workflows/barista-preview.yml
  angular.json
  libs/tools/builders/builders.json
  libs/tools/builders/index.ts
  libs/tools/builders/jest.config.js
  libs/tools/builders/package.json
  libs/tools/builders/test-setup.ts
  libs/tools/builders/tsconfig.json
  libs/tools/builders/tsconfig.spec.json
  libs/tools/builders/util/json-utils.ts
  libs/tools/release/src/publish-release/publish-release.spec.ts
  libs/tools/shared/src/interfaces/package-json.ts
  libs/workspace/builders.json
  libs/workspace/src/builders/design-tokens/package/build.ts
  libs/workspace/src/builders/packager/build.ts
  libs/workspace/src/builders/packager/copy-assets.ts
  libs/workspace/src/builders/packager/index.ts
  libs/workspace/src/builders/packager/schema.json
  libs/workspace/src/builders/packager/schema.ts
  libs/workspace/src/builders/packager/sync-version.ts
  libs/workspace/src/builders/stylelint/index.ts
  libs/workspace/src/builders/stylelint/junit-formatter/existing-result.interface.ts
  libs/workspace/src/builders/stylelint/junit-formatter/index.ts
  libs/workspace/src/builders/stylelint/junit-formatter/junit-formatter.ts
  libs/workspace/src/builders/stylelint/junit-formatter/parse-exisiting-suite.ts
  libs/workspace/src/builders/stylelint/junit-formatter/parse-suite.ts
  libs/workspace/src/builders/stylelint/junit-formatter/parsed-suite.interface.ts
  libs/workspace/src/builders/stylelint/read-files.ts
  libs/workspace/src/builders/stylelint/schema.json
  libs/workspace/src/builders/stylelint/stylelint-builder-options.ts
  libs/workspace/src/builders/typescript/index.ts
  libs/workspace/src/builders/typescript/schema.json
  libs/workspace/src/builders/typescript/schema.ts
  libs/workspace/src/builders/util/json-utils.ts
  libs/workspace/tsconfig.json
  libs/workspace/tsconfig.lib.json
  libs/workspace/webpack.config.js
  nx.json
  package.json
  tsconfig.json
  tslint.json
Labels: pr: merge-ready, target: minor, target: patch

#845 refactor(filter-field): Refactored the tests to contain less repitition.
  libs/barista-components/filter-field/src/filter-field.spec.ts
Labels: pr: merge-ready, target: minor, target: patch

#860 docs(table): Improved observable and responsive examples
  libs/examples/src/table/table-observable-example/table-observable-example.html
  libs/examples/src/table/table-observable-example/table-observable-example.ts
  libs/examples/src/table/table-responsive-example/table-responsive-example.html
  libs/examples/src/table/table-responsive-example/table-responsive-example.ts
Labels: pr: needs-cherry-pick

#888 ci: Fix broken barista builder due to update of angular ngcc.
  .deployment/k8s-barista-builder/Dockerfile
  .deployment/k8s-barista-builder/Jenkinsfile
Labels: pr: merge-ready, target: minor, target: patch

#887 fix(slider): Prevent default behavior of keyboard events associated with the slider.
  libs/barista-components/slider/src/slider.ts
Labels: pr: merge-ready, target: minor, target: patch

#850 Barista icon color wheel bug
  apps/barista-design-system/src/components/icon-color-wheel/icon-color-wheel.html
  apps/barista-design-system/src/components/icon-color-wheel/icon-color-wheel.ts
Labels: pr: merge-ready, target: minor, target: patch

#791 barista(absolute-link-transformer): The added transformer converts in…
  apps/barista-design-system/src/components/components.module.ts
  apps/barista-design-system/src/components/content-link/content-link.ts
  apps/barista-design-system/src/pages/single-page/page-content.ts
  apps/barista-design-system/src/shared/services/toc.service.ts
  apps/barista-design-system/src/utils/create-component.ts
  libs/tools/barista/src/builder/components.ts
  libs/tools/barista/src/builder/icons.ts
  libs/tools/barista/src/builder/strapi.ts
  libs/tools/barista/src/transform.spec.ts
  libs/tools/barista/src/transform.ts
Labels: pr: merge-ready, target: minor, target: patch

#902 build: Cleanup old missing tsconfig paths.
  tsconfig.json
Labels: pr: merge-ready, target: minor, target: patch

#892 docs: Updates repo structure documentation in guide for developers.
  DEVELOPMENT.md
Labels: pr: needs-cherry-pick

#893 ci: Add public deployment of barista on Jenkins.
  .deployment/barista/Jenkinsfile
  .deployment/k8s-barista-builder/Dockerfile
  .github/workflows/barista-preview.yml
  .gitignore
  environments/barista-environment.ci.ts
  now.json
Labels: pr: merge-ready, target: minor, target: patch

#907 barista: Fixes the limit for strapi list queries.
  libs/tools/barista/src/utils/fetch-strapi-content.ts
Labels: design-system, pr: merge-ready, target: minor, target: patch

#904 ci: Add tests for workspace scripts.
  libs/workspace/src/scripts/affected-args.spec.ts
  libs/workspace/src/scripts/affected-args.ts
Labels: pr: merge-ready, target: minor, target: patch

#911 chore: Cleanup and remove old gulpfile.
  gulpfile.js
  package.json
Labels: pr: merge-ready, target: minor, target: patch

#663 feat(drawer-table): Added drawer-table component and example demo page
  angular.json
  apps/dev/src/app.module.ts
  apps/dev/src/devapp-routing.module.ts
  apps/dev/src/devapp.component.ts
  apps/dev/src/drawer-table/drawer-table-demo.component.html
  apps/dev/src/drawer-table/drawer-table-demo.component.ts
  apps/dev/src/dt-components.module.ts
  libs/barista-components/experimental/drawer-table/README.md
  libs/barista-components/experimental/drawer-table/barista.json
  libs/barista-components/experimental/drawer-table/index.ts
  libs/barista-components/experimental/drawer-table/jest.config.js
  libs/barista-components/experimental/drawer-table/package.json
  libs/barista-components/experimental/drawer-table/src/drawer-table-module.ts
  libs/barista-components/experimental/drawer-table/src/drawer-table.html
  libs/barista-components/experimental/drawer-table/src/drawer-table.scss
  libs/barista-components/experimental/drawer-table/src/drawer-table.spec.ts
  libs/barista-components/experimental/drawer-table/src/drawer-table.ts
  libs/barista-components/experimental/drawer-table/src/test-setup.ts
  libs/barista-components/experimental/drawer-table/tsconfig.json
  libs/barista-components/experimental/drawer-table/tsconfig.lib.json
  libs/barista-components/experimental/drawer-table/tsconfig.spec.json
  libs/barista-components/experimental/drawer-table/tslint.json
  libs/examples/src/drawer-table/drawer-table-default-example/drawer-table-default-example.html
  libs/examples/src/drawer-table/drawer-table-default-example/drawer-table-default-example.ts
  libs/examples/src/drawer-table/drawer-table-examples.module.ts
  libs/examples/src/drawer-table/index.ts
  libs/examples/src/examples.module.ts
  libs/examples/src/index.ts
  nx.json
  tsconfig.json
Labels: pr: needs-cherry-pick

#923 build: Fixes a problem where the barista build was flaky.
  .github/workflows/barista-preview.yml
  angular.json
  apps/barista-design-system/src/app/app.ts
  apps/barista-design-system/src/server.ts
  apps/barista-design-system/src/shared/services/page.service.ts
  libs/workspace/src/builders/barista-build/builder.spec.ts
  libs/workspace/src/builders/barista-build/builder.ts
  libs/workspace/src/builders/barista-build/fixtures/mock-server.js
  libs/workspace/src/builders/barista-build/prerender/render-routes.ts
  libs/workspace/src/builders/barista-build/renderer.ts
  libs/workspace/src/builders/barista-build/schema.json
  libs/workspace/src/builders/barista-build/utils/get-routes.ts
  libs/workspace/src/builders/barista-build/utils/index.ts
  libs/workspace/src/builders/barista-build/utils/render-routes.ts
  libs/workspace/src/builders/barista-build/utils/schedule-builds.ts
  libs/workspace/src/builders/barista-build/utils/start-server.spec.ts
  libs/workspace/src/builders/barista-build/utils/start-server.ts
  libs/workspace/webpack.config.js
Labels: pr: merge-ready, target: minor, target: patch

#914 barista(live-examples): Fixes an issue with the stepper examples.
  apps/barista-design-system/src/components/components.module.ts
  libs/examples/src/stepper/stepper-examples.module.ts
Labels: pr: merge-ready, target: minor, target: patch

#908 build: Cleanup old unused configs to avoid confusions.
  .deployment/barista/Jenkinsfile
  angular.json
  environments/barista-environment.ci.ts
  environments/barista-environment.prod.ts
  environments/barista-environment.ts
  tsconfig.json
Labels: pr: merge-ready, target: minor, target: patch

#870 chore(changelog): Change the order of changelog. Fix stream merging iss…
  libs/tools/release/src/changelog/__snapshots__/changelog.spec.ts.snap
  libs/tools/release/src/changelog/changelog.ts
  libs/tools/release/src/extract-release-notes.ts
  libs/tools/release/src/testing/fixtures/CHANGELOG-minimal.md
  libs/tools/release/src/testing/fixtures/CHANGELOG-release.md
  libs/tools/release/src/testing/fixtures/CHANGELOG.md
  libs/tools/release/src/utils/concatenate-node-streams.spec.ts
  libs/tools/release/src/utils/concatenate-node-streams.ts
  libs/tools/release/src/utils/merge-node-streams.ts
Labels: pr: merge-ready, target: minor, target: patch

#932 chore: Add snyk ignore for lodash
  .snyk
Labels: pr: merge-ready, target: minor, target: patch

#883 Sunburst
  .github/CODEOWNERS
  angular.json
  apps/dev/src/app.module.ts
  apps/dev/src/devapp-routing.module.ts
  apps/dev/src/devapp.component.ts
  apps/dev/src/dt-components.module.ts
  apps/dev/src/sunburst-chart/sunburst-chart-demo-data.ts
  apps/dev/src/sunburst-chart/sunburst-chart-demo.component.html
  apps/dev/src/sunburst-chart/sunburst-chart-demo.component.scss
  apps/dev/src/sunburst-chart/sunburst-chart-demo.component.ts
  apps/dev/src/sunburst/sunburst-demo-data.ts
  apps/universal/src/app/barista.module.ts
  apps/universal/src/app/kitchen-sink/kitchen-sink.html
  apps/universal/src/app/kitchen-sink/kitchen-sink.ts
  libs/barista-components/sunburst-chart/README.md
  libs/barista-components/sunburst-chart/barista.json
  libs/barista-components/sunburst-chart/index.ts
  libs/barista-components/sunburst-chart/jest.config.js
  libs/barista-components/sunburst-chart/src/sunburst-chart.directive.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.html
  libs/barista-components/sunburst-chart/src/sunburst-chart.mock.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.module.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.scss
  libs/barista-components/sunburst-chart/src/sunburst-chart.spec.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.util.spec.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.util.ts
  libs/barista-components/sunburst-chart/src/test-setup.ts
  libs/barista-components/sunburst-chart/tsconfig.json
  libs/barista-components/sunburst-chart/tsconfig.lib.json
  libs/barista-components/sunburst-chart/tsconfig.spec.json
  libs/barista-components/sunburst-chart/tslint.json
  libs/examples/src/examples.module.ts
  libs/examples/src/index.ts
  libs/examples/src/sunburst-chart/index.ts
  libs/examples/src/sunburst-chart/sunburst-chart-color-data.ts
  libs/examples/src/sunburst-chart/sunburst-chart-custom-color-example/sunburst-chart-custom-color-example.html
  libs/examples/src/sunburst-chart/sunburst-chart-custom-color-example/sunburst-chart-custom-color-example.ts
  libs/examples/src/sunburst-chart/sunburst-chart-default-data.ts
  libs/examples/src/sunburst-chart/sunburst-chart-default-example/sunburst-chart-default-example.html
  libs/examples/src/sunburst-chart/sunburst-chart-default-example/sunburst-chart-default-example.ts
  libs/examples/src/sunburst-chart/sunburst-chart-examples.module.ts
  libs/examples/src/sunburst-chart/sunburst-chart-relative-values-example/sunburst-chart-relative-values-example.html
  libs/examples/src/sunburst-chart/sunburst-chart-relative-values-example/sunburst-chart-relative-values-example.ts
  nx.json
  tsconfig.json
Labels: pr: needs-cherry-pick
