Repository dynatrace-oss/barista, pull requests merged in 2021-01, with the labels that each got.

#1901 chore: Fix dependency of slack webhook to mitigate axios security risk.
  tools/slack-release-notifier/package-lock.json
  tools/slack-release-notifier/package.json
Labels: pr: merge-ready, target: minor, target: patch

#1903 fix(chart): Added DtPlotBackgroundInfo to exported interfaces.
  libs/barista-components/chart/index.ts
  libs/barista-components/chart/src/heatfield/chart-heatfield.ts
  libs/barista-components/chart/src/tooltip/chart-tooltip-position.ts
  libs/barista-components/chart/src/tooltip/chart-tooltip.ts
  libs/barista-components/chart/src/utils.ts
  libs/examples/src/chart/chart-bar-example/chart-bar-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#1900 fix(tabs): Fixes an issue where theme custom properties were not applied correctly
  libs/barista-components/tabs/src/tab-group.scss
Labels: pr: merge-ready, target: minor, target: patch

#1909 fix(quick-filter): Fixes an issue with initial display of active items in the sidebar.
  libs/barista-components/quick-filter/src/quick-filter-group.ts
Labels: pr: merge-ready, target: minor, target: patch

#1890 feat(stacked-series-chart): Add Input to be able to select the whole stack
  apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.html
  apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.ts
  apps/dev/src/stacked-series-chart/stacked-series-chart-demo.component.html
  apps/dev/src/stacked-series-chart/stacked-series-chart-demo.component.ts
  libs/barista-components/stacked-series-chart/README.md
  libs/barista-components/stacked-series-chart/barista.json
  libs/barista-components/stacked-series-chart/index.ts
  libs/barista-components/stacked-series-chart/src/stacked-series-chart-bar.scss
  libs/barista-components/stacked-series-chart/src/stacked-series-chart-column.scss
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.html
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.scss
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.spec.ts
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.spec.ts
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.ts
Labels: pr: blocked

#1913 fix(sunburst-chart): Fix tooltip flicker on click
  apps/dev/src/sunburst-chart/sunburst-chart-demo.component.scss
  apps/dev/src/sunburst-chart/sunburst-chart-demo.component.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart-segment.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.html
  libs/barista-components/sunburst-chart/src/sunburst-chart.spec.ts
  libs/barista-components/sunburst-chart/src/sunburst-chart.ts
Labels: bug
