Repository dynatrace-oss/barista, pull requests merged in 2021-06, with the labels that each got.

#2135 feat(overlay): Adds pinnedChanged output and isOverlayPinned property.
  libs/barista-components/overlay/README.md
  libs/barista-components/overlay/src/overlay-ref.ts
  libs/barista-components/overlay/src/overlay-trigger.spec.ts
  libs/barista-components/overlay/src/overlay-trigger.ts
  libs/examples/src/overlay/overlay-default-example/overlay-default-example.html
  libs/examples/src/overlay/overlay-default-example/overlay-default-example.ts
Labels: pr: merge-ready, target: minor

#2144 feat(theming): Add critical color to theme.
  apps/dev/src/icon/icon-demo.component.html
  apps/dev/src/indicator/indicator-demo.component.ts
  libs/barista-components/core/src/common-behaviours/color.ts
  libs/barista-components/core/src/theming/_theming-core.scss
  libs/barista-components/core/src/theming/theme-definitions/_blue-theme.scss
  libs/barista-components/core/src/theming/theme-definitions/_purple-theme.scss
  libs/barista-components/core/src/theming/theme-definitions/_royalblue-theme.scss
  libs/barista-components/core/src/theming/theme-definitions/_turquoise-theme.scss
  libs/barista-components/icon/src/icon.scss
  libs/barista-components/icon/src/icon.spec.ts
  libs/barista-components/icon/src/icon.ts
  libs/barista-components/indicator/README.md
  libs/barista-components/indicator/src/indicator.scss
  libs/barista-components/indicator/src/indicator.spec.ts
  libs/barista-components/indicator/src/indicator.ts
  libs/barista-components/style/main.scss
  libs/barista-components/style/themes.scss
  libs/barista-components/table/src/cell.ts
  libs/barista-components/table/src/expandable/expandable-row.scss
  libs/barista-components/table/src/row.scss
  libs/barista-components/table/src/row.ts
  libs/barista-components/tree-table/src/tree-table-row.scss
  libs/examples/src/indicator/indicator-default-example/indicator-default-example.html
  libs/examples/src/indicator/indicator-default-example/indicator-default-example.ts
  libs/examples/src/table/table-problem-example/table-problem-example.ts
Labels: pr: merge-ready, target: minor

#2145 feat(stacked-series-chart): Adding auto scrolling on horizontal overflow
  apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.e2e.ts
  apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.html
  apps/components-e2e/src/components/stacked-series-chart/stacked-series-chart.po.ts
  libs/barista-components/stacked-series-chart/BUILD.bazel
  libs/barista-components/stacked-series-chart/src/_stacked-series-chart-theme.scss
  libs/barista-components/stacked-series-chart/src/stacked-series-chart-bar.scss
  libs/barista-components/stacked-series-chart/src/stacked-series-chart-column.scss
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.html
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.scss
Labels: pr: needs-cherry-pick

#2147 fix(context-dialog): Fixes flexible dimensions being applied correctly.
  libs/barista-components/context-dialog/src/context-dialog.html
  libs/barista-components/context-dialog/src/context-dialog.scss
  libs/barista-components/context-dialog/src/context-dialog.spec.ts
  libs/barista-components/context-dialog/src/context-dialog.ts
Labels: pr: merge-ready, target: minor, target: patch

#2150 chore(deps): Fixes vulnerability in path-parse by bumping to 1.0.7
  package-lock.json
Labels: pr: merge-ready, target: minor, target: patch

#2151 style(filter-field): Expands input element inside the filter-field in…
  libs/barista-components/filter-field/src/filter-field.html
  libs/barista-components/filter-field/src/filter-field.scss
Labels: pr: merge-ready, target: minor, target: patch

#2152 feat(filter-field): Added partial hint message flexible configuration
  libs/barista-components/filter-field/src/filter-field-default-data-source.ts
  libs/barista-components/filter-field/src/filter-field.html
  libs/barista-components/filter-field/src/filter-field.scss
  libs/barista-components/filter-field/src/types.ts
Labels: pr: needs-cherry-pick

#2165 fix(quick-filter): Trigger resize event when sidebar open state changes.
  libs/barista-components/chart/src/chart.ts
  libs/barista-components/core/src/viewport/viewport-resizer.ts
  libs/barista-components/quick-filter/src/quick-filter.html
  libs/barista-components/quick-filter/src/quick-filter.module.ts
  libs/barista-components/quick-filter/src/quick-filter.spec.ts
  libs/barista-components/quick-filter/src/quick-filter.ts
  tslint.json
Labels: pr: merge-ready, target: minor, target: patch

#2158 feat(stacked-series-chart): Show highest value in Y axis.
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.spec.ts
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.util.ts
Labels: pr: needs-cherry-pick
