Repository dynatrace-oss/barista, pull requests merged in 2021-09, with the labels that each got.

#2231 fix(filter-field): Export validator type.
  libs/barista-components/filter-field/index.ts
Labels: pr: needs-cherry-pick

#2238 Fix/filter field free text edit mode
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: needs-cherry-pick

#2232 fix(quickfilter): Fixes z-index issues with the error message.
  libs/barista-components/filter-field/src/filter-field-validation.ts
  libs/barista-components/filter-field/src/filter-field.scss
  libs/examples/src/quick-filter/BUILD.bazel
  libs/examples/src/quick-filter/quick-filter-default-example/quick-filter-default-example.ts
Labels: pr: merge-ready, target: minor, target: patch

#2248 chore(workspace): Fix snyk config.
  .snyk
Labels: pr: merge-ready, target: minor, target: patch

#2242 fix(filter-field): Fixes an issue where the filter-changes event inst…
  libs/barista-components/filter-field/src/filter-field-edit-mode.spec.ts
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#2251 feat(filter-field): Adding multiselect capabilities to complex filter type.
  apps/dev/src/filter-field/multi-select.ts
  libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-with-multiselect.spec.ts
  libs/barista-components/filter-field/src/filter-field-util.ts
  libs/examples/src/filter-field/filter-field-multi-select-example/filter-field-multi-select-example.ts
Labels: pr: needs-cherry-pick

#2257 feat(icon): Remove log for missing loading resources.
  libs/barista-components/icon/src/icon.ts
Labels: pr: merge-ready, pr: needs-cherry-pick

#2258 fix(button): Fixes anchor button disabled styles not being applied on…
  libs/barista-components/button/src/_button-theme.scss
Labels: pr: merge-ready, target: minor, target: patch

#2264 fix(table): Fixes an issue where the global selection checkbox was wrongfully checked on empty tables.
  apps/demos/src/app-routing.module.ts
  apps/demos/src/nav-items.ts
  libs/barista-components/table/src/selection/selector.spec.ts
  libs/barista-components/table/src/selection/selectors.ts
Labels: pr: merge-ready, target: minor, target: patch

#2265 fix(inline-editor): Move the error-state hints to a cdk overlay to escape overflow handling.
  libs/barista-components/inline-editor/src/inline-editor-module.ts
  libs/barista-components/inline-editor/src/inline-editor.html
  libs/barista-components/inline-editor/src/inline-editor.spec.ts
  libs/barista-components/inline-editor/src/inline-editor.ts
Labels: pr: merge-ready, target: minor, target: patch
