Repository dynatrace-oss/barista, pull requests merged in 2021-02, with the labels that each got.

#1948 feat(core,table): Introduces a new sorting behaviour which treats undefined/null values in number compares as ASC first/DESC last.
  libs/barista-components/core/src/util/compare-util.spec.ts
  libs/barista-components/core/src/util/compare-util.ts
  libs/barista-components/table/src/simple-columns/simple-column.spec.ts
Labels: pr: merge-ready, target: minor

#1919 feat(filter-field): Adds a quick input option (default search option)
  apps/components-e2e/src/components/consumption/consumption.html
  apps/components-e2e/src/components/drawer/drawer.html
  apps/components-e2e/src/components/event-chart/event-chart.ts
  apps/components-e2e/src/components/filter-field/filter-field.ts
  apps/components-e2e/src/components/quick-filter/quick-filter-async/quick-filter-async.ts
  apps/components-e2e/src/components/quick-filter/quick-filter.e2e.ts
  apps/components-e2e/src/components/quick-filter/quick-filter/quick-filter.ts
  apps/components-e2e/src/components/radial-chart/radial-chart.html
  apps/components-e2e/src/components/select/select.html
  apps/components-e2e/src/components/sunburst-chart/sunburst-chart.html
  apps/components-e2e/src/components/tree-table/tree-table.html
  apps/demos/src/app-routing.module.ts
  apps/demos/src/barista-examples.a11y.ts
  apps/demos/src/nav-items.ts
  apps/dev/src/filter-field/testdata.ts
  libs/barista-components/filter-field/README.md
  libs/barista-components/filter-field/src/filter-field-default-data-source.ts
  libs/barista-components/filter-field/src/filter-field-util.ts
  libs/barista-components/filter-field/src/filter-field.html
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
  libs/barista-components/filter-field/src/testing/filter-field-test-helpers.ts
  libs/barista-components/filter-field/src/types.ts
  libs/examples/src/filter-field/BUILD.bazel
  libs/examples/src/filter-field/filter-field-default-search-example/filter-field-default-search-example.html
  libs/examples/src/filter-field/filter-field-default-search-example/filter-field-default-search-example.ts
  libs/examples/src/filter-field/filter-field-examples.module.ts
  libs/examples/src/filter-field/filter-field-validator-example/filter-field-validator-example.ts
  libs/examples/src/filter-field/index.ts
  libs/examples/src/index.ts
Labels: pr: merge-ready, target: minor

#1952 fix(theming): Fixes an issue with out of sync recovered colors.
  libs/barista-components/core/src/theming/theme-definitions/_blue-theme.scss
  libs/barista-components/core/src/theming/theme-definitions/_purple-theme.scss
  libs/barista-components/core/src/theming/theme-definitions/_royalblue-theme.scss
  libs/barista-components/core/src/theming/theme-definitions/_turquoise-theme.scss
Labels: pr: merge-ready, target: minor, target: patch

#1953 fix(stacked-series-chart): Temporarily fixes an issue where this compo…
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
Labels: pr: merge-ready, target: minor, target: patch

#1957 fix(table): Fixes an issue with partial keyframes on expandable row.
  libs/barista-components/table/src/expandable/expandable-row.ts
Labels: pr: merge-ready, target: minor, target: patch

#1956 fix(table): Fixes an issue with the expandable row flashing when paginating a table.
  libs/barista-components/table/src/expandable/expandable-row.scss
Labels: pr: merge-ready, target: minor, target: patch

#1954 fix(filter-field): Handling asynchronous fetching for multiselect fields.
  apps/dev/src/filter-field/filter-field-demo.component.ts
  apps/dev/src/filter-field/multi-select.ts
  apps/dev/src/filter-field/testdata.ts
  libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.html
  libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.scss
  libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.ts
  libs/barista-components/filter-field/src/filter-field-util.ts
  libs/barista-components/filter-field/src/filter-field-with-multiselect.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
  libs/barista-components/filter-field/src/types.ts
Labels: pr: needs-cherry-pick

#1968 fix(breadcrumbs): Fixes an ExpressionChangedAfterChecked error on the…
  libs/barista-components/breadcrumbs/src/breadcrumbs-item.ts
  libs/barista-components/breadcrumbs/src/breadcrumbs.scss
Labels: pr: merge-ready, target: minor, target: patch

#1958 fix(stacked-series-chart): Show stack mode tooltip highlight + proper…
  apps/dev/src/stacked-series-chart/stacked-series-chart-demo.component.html
  apps/dev/src/stacked-series-chart/stacked-series-chart-demo.component.ts
  libs/barista-components/stacked-series-chart/src/stacked-series-chart-column.scss
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
Labels: pr: needs-cherry-pick

#1974 fix(expandable-section): Fixes an issue where toggling the expandable section was triggering a form submission.
  libs/barista-components/expandable-panel/src/expandable-panel-trigger.ts
Labels: pr: merge-ready, target: minor, target: patch

#1976 fix(quick-filter): Fixes default search in the quick-filter
  apps/dev/src/quick-filter/quick-filter-demo.component.ts
  libs/barista-components/quick-filter/src/quick-filter-default-data-source.ts
Labels: pr: merge-ready, target: minor, target: patch

#1977 docs: Updated command list
  DEVELOPMENT.md
Labels: pr: merge-ready, target: minor, target: patch

#1955 feat(filter-field): Keyboard support
  apps/dev/src/filter-field/filter-field-demo.component.html
  apps/dev/src/filter-field/filter-field-demo.component.ts
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.html
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.ts
  libs/barista-components/filter-field/src/filter-field.html
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
  libs/barista-components/filter-field/src/testing/filter-field-test-data.ts
  libs/barista-components/filter-field/src/testing/filter-field-test-helpers.ts
Labels: pr: merge-ready, target: minor

#1975 chore(examples): Updates examples for new angular stackblitz structure.
  libs/tools/shareable-examples/src/templates/angular.json.template
  libs/tools/shareable-examples/src/templates/package-shareable-example.json.template
  libs/tools/shareable-examples/src/templates/tsconfig.json.template
  libs/tools/shareable-examples/src/utils/get-boilerplate-files.ts
Labels: pr: merge-ready, target: minor, target: patch

#1960 fix(radial-chart): Display of rounded percentage with precision
  libs/barista-components/radial-chart/README.md
  libs/barista-components/radial-chart/src/radial-chart.html
  libs/barista-components/radial-chart/src/radial-chart.ts
  libs/barista-components/radial-chart/src/utils/radial-chart-interfaces.ts
  libs/barista-components/radial-chart/src/utils/radial-chart-utils.spec.ts
  libs/barista-components/radial-chart/src/utils/radial-chart-utils.ts
Labels: pr: needs-cherry-pick

#1984 chore(workspace): Adjust lodash transitive dependency snyk rule.
  .snyk
Labels: pr: merge-ready, target: minor, target: patch

#1978 docs(table): Fix escapes in API table formatting.
  libs/barista-components/table/README.md
Labels: pr: merge-ready, target: minor, target: patch

#1972 chore(combobox): Add example for form control usage.
  apps/demos/src/app-routing.module.ts
  apps/demos/src/barista-examples.a11y.ts
  apps/demos/src/nav-items.ts
  libs/barista-components/experimental/combobox/README.md
  libs/barista-components/experimental/combobox/src/combobox.ts
  libs/examples/src/combobox/BUILD.bazel
  libs/examples/src/combobox/combobox-examples.module.ts
  libs/examples/src/combobox/combobox-form-control-example/combobox-form-control-example.html
  libs/examples/src/combobox/combobox-form-control-example/combobox-form-control-example.ts
  libs/examples/src/combobox/index.ts
  libs/examples/src/index.ts
Labels: pr: merge-ready, target: minor, target: patch

#1987 docs(workspace): Fix escapes in API formatting.
  libs/barista-components/alert/README.md
  libs/barista-components/bar-indicator/README.md
  libs/barista-components/breadcrumbs/README.md
  libs/barista-components/button-group/README.md
  libs/barista-components/button/README.md
  libs/barista-components/confirmation-dialog/README.md
  libs/barista-components/container-breakpoint-observer/README.md
  libs/barista-components/context-dialog/README.md
  libs/barista-components/copy-to-clipboard/README.md
  libs/barista-components/drawer/README.md
  libs/barista-components/event-chart/README.md
  libs/barista-components/experimental/combobox/README.md
  libs/barista-components/formatters/README.md
  libs/barista-components/indicator/README.md
  libs/barista-components/micro-chart/README.md
  libs/barista-components/overlay/README.md
  libs/barista-components/progress-bar/README.md
  libs/barista-components/radial-chart/README.md
  libs/barista-components/radio/README.md
  libs/barista-components/select/README.md
  libs/barista-components/show-more/README.md
  libs/barista-components/stacked-series-chart/README.md
  libs/barista-components/stepper/README.md
  libs/barista-components/sunburst-chart/README.md
  libs/barista-components/tabs/README.md
Labels: pr: merge-ready, target: minor, target: patch

#1986 fix(filter-field): Improving isOptionSelected method for async values.
  libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.ts
  libs/barista-components/filter-field/src/filter-field-util.ts
  libs/barista-components/filter-field/src/filter-field-with-multiselect.spec.ts
Labels: pr: needs-cherry-pick

#1992 fix(stacked-series-chart): Clear when using stack mode.
  apps/dev/src/stacked-series-chart/stacked-series-chart-demo.component.html
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.spec.ts
  libs/barista-components/stacked-series-chart/src/stacked-series-chart.ts
Labels: pr: needs-cherry-pick

#1994 refactor: Added input typings to fix strict coercion in tag and table.
  libs/barista-components/table/src/simple-columns/simple-column-base.ts
  libs/barista-components/tag/src/tag.ts
Labels: pr: merge-ready, target: minor, target: patch

#1993 fix(combobox): Fixes an issue with the arrow positioning on safari.
  libs/barista-components/experimental/combobox/src/combobox.scss
Labels: pr: merge-ready, target: minor, target: patch

#1973 feat(filter-field): Adds seperate disabled member in tags
  apps/dev/src/filter-field/filter-field-demo.component.html
  apps/dev/src/filter-field/filter-field-demo.component.ts
  libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-with-multiselect.spec.ts
  libs/barista-components/filter-field/src/filter-field-range/filter-field-with-range.spec.ts
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.html
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.scss
  libs/barista-components/filter-field/src/filter-field-tag/filter-field-tag.ts
  libs/barista-components/filter-field/src/filter-field.html
  libs/barista-components/filter-field/src/filter-field.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
Labels: pr: merge-ready, target: minor, target: patch

#1996 refactor: Fixed strict typing input rename in table and indicator.
  libs/barista-components/indicator/src/indicator.ts
  libs/barista-components/table/src/cell.ts
Labels: pr: merge-ready, target: minor, target: patch
