Repository dynatrace-oss/barista, pull requests merged in 2021-08, with the labels that each got.

#2199 feat(filter-field): Prefills text of first level freeText node on edit
  libs/barista-components/filter-field/src/filter-field-edit-mode.spec.ts
  libs/barista-components/filter-field/src/filter-field.ts
  libs/barista-components/filter-field/src/testing/filter-field-test-data.ts
Labels: pr: merge-ready, target: minor

#2213 fix(workspace): Remove codeowner.
  .github/CODEOWNERS
Labels: pr: merge-ready, target: minor, target: patch

#2200 feat(filter-field): Add disable state to the option without group
  apps/dev/src/filter-field/testdata.ts
  libs/barista-components/filter-field/src/filter-field.html
  libs/barista-components/filter-field/src/filter-field.spec.ts
Labels: pr: needs-cherry-pick

#2207 feat(chart): Added series heatmaps options to dt chart series type
  libs/barista-components/chart/src/chart.interface.ts
Labels: pr: needs-cherry-pick

#2214 fix(filter-field): Multiselect with programmatically defined filters is not stable
  apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
  apps/components-e2e/src/components/filter-field/filter-field.ts
  libs/barista-components/filter-field/src/filter-field-util.ts
Labels: pr: needs-cherry-pick

#2215 fix(filter-field): Fix multiselect apply button disabled
  apps/components-e2e/src/components/filter-field/filter-field.e2e.ts
  libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-multi-select.ts
  libs/barista-components/filter-field/src/filter-field-multi-select/filter-field-with-multiselect.spec.ts
Labels: pr: needs-cherry-pick

#2216 fix(event-chart): Fix overlap for multiple elements
  libs/barista-components/event-chart/src/event-chart.html
  libs/barista-components/event-chart/src/event-chart.ts
  libs/barista-components/event-chart/src/merge-and-path/merge-events.spec.ts
  libs/barista-components/event-chart/src/merge-and-path/merge-events.ts
Labels: pr: needs-cherry-pick

#2194 fix(chart): Fixed chart selection area focus.
  libs/barista-components/chart/src/chart-focus-anchor.spec.ts
  libs/barista-components/chart/src/chart-focus-anchor.ts
  libs/barista-components/chart/src/chart-module.ts
  libs/barista-components/chart/src/chart.ts
  libs/barista-components/chart/src/range/range.html
  libs/barista-components/chart/src/range/range.spec.ts
  libs/barista-components/chart/src/range/range.ts
  libs/barista-components/chart/src/selection-area/selection-area.spec.ts
  libs/barista-components/chart/src/selection-area/selection-area.ts
  libs/barista-components/chart/src/timestamp/timestamp.html
  libs/barista-components/chart/src/timestamp/timestamp.ts
  libs/barista-components/chart/src/utils.ts
Labels: pr: merge-ready, target: minor, target: patch

#2223 chore: Bump version to 9.11.0 w/ changelog
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pr: merge-ready, target: minor, target: patch
